apiVersion: v1
kind: Service
metadata:
  name: organizer-db-service
spec:
  type: ClusterIP
  selector:
    app: organizer-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: organizer-db
  labels:
    app: organizer-db
spec:
  serviceName: organizer-db-service
  replicas: 1
  selector:
    matchLabels:
      app: organizer-db
  template:
    metadata:
      labels:
        app: organizer-db
    spec:
      containers:
        - name: organizer-db
          image: zago0/organizer-postgres:1.3
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: organizer-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: organizer-secrets
                  key: DB_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: organizer-secrets
                  key: DB_NAME
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: organizer-pv-storage
  volumeClaimTemplates:
    - metadata:
        name: organizer-pv-storage
      spec:
        {{- if not .Values.persistence.storageClass }}
        storageClassName: manual
        selector:
          matchLabels:
            type: {{ .Release.Namespace }}-local
        {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
