env: staging
deployments:
  - component: server
    containerPort: 3000
    envSecretRefs:
      - web-server-envs
    envVars:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: DB_HOST
        value: database-service
      - name: DB_PORT
        value: "5432"
    image: ghcr.io/b-zago/links-organizer/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: nodejs
routes:
  - host: organizer-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgAK6a+HIbNEzgouLucfakHFiNSJYBmO0B4Mi7l77uXv/TU1ZBSuvjM5kbnn+4pGXh1sn4BYbJtd193xFQI03OmxqOLzw7k5y8FCuVAY5JkHVR71ClleWgZspFFagkWLEkZudwjh4kCrU7oxyHhl02dtYLV0XsEsqJLzWRnOjMyUMSU0UJLkqPTfiQ82Ofv9PAK953dtNQhKx0Wi2Au1VL7utWVPFaEiYjfkbhTq6vVeVVL/343TGUS6Qvun+z+5h3xv36GnljbR6C6/kWLEutNUyKTxFax4zo4IZsJK443C9AHOZSSBgMJCgU0s4Ckw3tFCzTc+aClCrpq5NTPt1+Rdm1pL5rtysoeHSoThnS7M1oxmuxzBUT1UOmxm8PJ5csH0Zpik23d30G8o5nZ10D8prmxfHIXuBVlxlEZF351G3rHVJJ4vNX4vOJ+AiYzCWQt1aBi9W15SUJ/6Ra6EeYU7P1XL1uAnOY9dx4vd4OZkzcft2aF2v1K5B6LI636wX/5+8DwCZfIs5FpZlj7YYvJHffyOClH613ID3sWaj02JOxnRl1WOAbiH8oPbOmcLGZNgaXgvYKnoIuJf46joBl8TgvdaZIe14311F8zdU4E5KZ/WIngnmpY1kSjkkPpXdSsgdDqm9q7Fi3SnfbZP2kLI5rn2zZCKrez5OTDphRLK73bTrx8cGzM0RJZfH2XGB8IaQj6sN+X70w==
      POSTGRES_PASSWORD: AgCWmtxNjaevrNLFP/EbqZxrHAuV9q2rFQZPsan0VikSJ5maFCh/7GpLI4BpPJkj496OA7/8oT9Cjx11taTBY84RbkjYlkJeULer3ibIfodIouvLSLi4RTTKhJjIHn22pGxRs9j0LizH1zQWutZtl1iTK1VUIvfo1u9jW1JHURfVEQaDUgfyCAbQerh4q8lvvSBXGlEW3trE6Hza7wwLtDFAdiV2NSPLmkI2u1dxAdJTEf9tm0S/2Q2eHiQXa5qGMKmw2tV/Aqg0VebTHhML7TenQfnwFuyNpPGw4I9VOrRvU9xcgn6xJvg7HeeWSbMDg0dR5XNl39if5LPGTYdvCDC52Rf2oq/QrxX+hd7S1lAcWGmPimlyeShaxfdgU0XYpeCJXu3ucQPq2Hjc1F9YAmWzBYcqHyYDqQ/id0ptQS1x6+q+2i51BUqWWb7RPme6yqAcUUzr+an4Ygdva8YmnS1xuk33GPjDcqgaobwJy6Bp2t2NLUuTpZZzEuwhYhzjzLiHitCg96l5zb7VZVgfyQCuegnAlFYiSuul3fp/RbyD7JXCx+VxF8bWHA597AzwfkpM04TkbrWxcZlR2GPmk+IQolvnNt55yqIfqKE+niOAD/RravYFYgqUg2z1Wjr8RmSFs++qHJX66I2Y9CkXDfcO/8CAzIXrhxmKc2OWpkW9vvqwRLX7/MX2P/Snj9GIxy3Dl74N3Llr3WQZPeDfSzbcC1VcmVrwnB+tOrrx0kBdv4r9KS7/dnW8aYPzgUYpPHOitqZS9jo=
      POSTGRES_USER: AgDeCAkbNUlgOrUg6/QiL6ks2DaXlCtR/pyzz6w3v8rZvmZGHOuliwQiqNkqE0BEbk2rjPdPCuFMyH6vpjqM3MLGRFY+8LLo52nhLpSoqPSWsVvHHXi1ZRUKPQjsu8xkscudt1wnU4dKY48hv1+vFTlemMjhmD6tkXwEGaBO0kbFMmaFKRBL5oL8ieWjoddU7UP2nw7t6K75rqS5U5gOnCkpGRPWMicq1l8qf2xuD87CVGUvbgdEZbb+HO12FrHb3yPD7H/7y68KMxAiLxdsqb1lnADeg9t6Bn3i9o3yu1wPICMR5NJdQqpJQeZuCbIVe1p4Mi6yzC2fe75RPILAG+jLB/3yKY0kn/VNyb4k7b05N+i4M8WLQolIiUXW+92mCI52N3nm+6AoVvsgeeGTGSpgJy4aEnFHMVfVGFV1p3YpnHdYwUeVUsGtVGyZdKWNCUv3h6B/ggUSnjW8NRIBTqlI4ItA/JoI/mk2jTS9MFqgwBK53r5HJeL1/zAdVm80qPe0Vm+V7eBXN0/sTOS1wEz8GC5oGS6Y839mIIK0tMKoPqkc2W9Xci1MwnmRHGr+iwzOxIWZT5REU7EJpUL2GlLlSv3JGLQqDloxsiY8/QwJD1k0oBgESLjvryHbRb/cc8zzUR3VDkzzhQkXYmCW3quxRmpaEfMhqQemGJxAj/N0n/vKCD89AvPMuyJ+xNHaBddd1beGep6u8b8=
    name: database-envs
    runsOnList:
      - database
  - data:
      DB_NAME: AgC9YwEDw3ZjZSZwNA/inokwP/yVkEz19S24Yw2uFoU8wl7rnDYJWQWWg2bFJhOdFpSDqpT1f0RnYdw++tLHG5YV4fIC3lLjDFgiXBb1JRM1nVH2f3R4AdOg0wpIH3sgvlaEQINfeIwXOjRRlKtW+U1GLEGqWRFAodIgyrP9ctaPIxqRd/heZ/erN6HPHbsQCZBpZAA/jul4/JVXGyhpLAh4BRDo8vJPxVZFRNAHl6w+9Uxmcf56rtb0hi4QkOzfzbHThrk9IOD3PEKyPHkQ8LFaJJ3rFXIOQ727vkNk9B5L5ELCVt/d3XZqa/6xDgD7hT6rpndTq8EGIQrFTayZ/yj/duSJhZ0JHLdc9JJgXHFe9ZaHMXmFNXTigliXK3BnmhcVZYiPD17NM3tv+Y1Q1ntEmKNinHtZ3fL6dul5+7tA77KokHToBBZqTNoHVoOv9sSQVf3Xa4nSarLZKT3mCfaWJTw+0eWKNB/5KFxiFcr+EKSTwb6vajmNCY6Leg4vkZFB/nusZjSlm5HIhJvWGElC2L/TeT/XLSt+yuuogueh9fM4qTDq+ux24cUZVKBjlm5Fs77xWvnB6B1i7UQAEo0d0pbkyZo32njLuUp8Pfwb0fsuDF6n+fMpnJO7FREKV6IqZAUQ4wDMT8jjNw+n27K8Zp8SzqwT+Ey3lbwoGLWRxW9pOuwXxXxc/o8asWatuRIb0gjn8aVffw==
      DB_PASSWORD: AgCJHkEk+e3K5Rd3Xr94hkNnvc9rUpb545yLThfqNRJOReXr1BWcIukNC8DTCKrP2aJ5YakcgM7sw8Wb4XXuj4DG7GjL+KQFYMkyTZVTjyBmi8ENycoTI6hHEJNC2fI1fXqiL5/MvWPRvFoXaFd0UYHC3dRo1sQhEpS483+y+IgWecP0s+nIjOexFb4GXAlWn9LRJO86YntlIKNwNbNhwLebXGfYWS5LlCk9HEIv7yTp7Ri0IQ2zRDZ7th5rJIRXI6oCKx8zpyn06eK/RvyzLyvxBPRjBr62a9HdQlDQ8j8dDRyPp+6VF9HQCI0ubJDnmiegojuoToe8jy2JYr+UtL1YOHNkO8NsacGtQj042zgZj2My4s6fK5RCg5JeOqMk8/lyNJO0jGSiTVpwJHcuDUVDAV02aBEF9r2NEVp4F0RA0AVeS1BojoKhyri9HllP4hZetI3/z+fpiDYAJtfPGVAs4nleN8XDmFlekiY4Etu7m/mSaRBaaBX1MoT6PXsKgm5IJvsMkrPmCazYAxQDQGQaPCn85uzuBGyYkAaI/8J4xB22YXAM66L+37q2FJjlBcD5N0QTJWdI8Hmv9sp6Mt59F9xUwPigSe5axN7YsQC0Z7GvUC0bNxlun1GnTyhrpzfHVwZFt1xV3ATIUKVqKxIZ+xSxXH5ieEUVhI2FlKwxebcxEQP3FETQ81N70pS8wTttOghrfJYV2iB164HqmJ+BTdYMwWkLnolCHvK2Omwy/6VgfjnZP/9BAK4dtzHYBRDkWkA9Sio=
      DB_USER: AgDRoaq5VnlCGG3VS4tml+JgkDw3N21njBtAc3tLvBcz0PKzbA8fjB6b/PSw7CVUov0ykk7C0ebmQeIL+3JuxuxIh35OJ+tOla5N3cOwipr6z4ZtEz01RaXOyUTVGNqKSaWFfYAA7ZENVZUS0U9wsBKq3E5yYX3L09yDHewERxYLLzhokTADEGA5JpA9aSW1h3fq2xK8oM6S8gP35+MVQPmcu7NYZAByryH7X1qNBJtYFNkQezeblFAaJO7hR5wnbLEjL7pT6gatqYS69dMrsuB9h/v8n1INRRzLY4hB2uKQRi853rrzz8d7wTZ7ksiYaoLt7vppD625ZCCotdWnlRf1qQQFl9Ud2vayPd9Bj7EcOvmINyQVeGgZ4E2zFM/VnpHq+40YnEue5KAz8/VDqP5IfqiDOU/D6G5/PEhWSAhsyLRh0pQvftIxvTgiEIwVntEwfsp9wUGSHqCZi9Sdci0MQ+kGTPq3nrLRSBWeEFVIokhxFQNBFrpLLIinK4Xdb3fQe614evWDCUW87HVyWO+1n2AuJlf8kGeQ6KMoDdjfURG/krMjTDexxp6NkT0Q/qRgVSZYG8pr1KNsGImBjzh5q6ug1NfuOblntqU8OzA+SJGOFKZo8Wmwxs61/GKa+ksrBIfsTzOcDBi5RU4k7CfJlxgXW0FIODU4YQXIo+EKLYKJgKdYp5Zjq5enGboXhnzbpVUAni6doDA=
      JWT_SECRET: AgDgLiCzWlRoR4Q4aoPvFD+Ro5lBqEH+R8T8gm59SfTQLy0Ym5XLpuDO6o4s4jlXMBESCsCouD1DHqUObqJURnT+QsBLpcXY6ZdxTICoRGuxbeqwZYBuRBfyqTBQo3zAPsn6CEuwDG+dSsp5MGxCHXTGT7B+xL54qI3WwWCAYvt2AcqjjRjq62ywECrfW9O6+wbTFKs8wlk6NuY6/awlLu+5oO5Ymvs78QToF89viqbMh36/vw9zq+xsMjSTONqMhlwWHoWBkJKu4J7OQ9yBaMNHitX8dqwWn5wr0doQ/WNlNAljmjA3qBlZcEztz7+AROnZP6ibttv7alfYwnHB1xMbpjSb6+03mEZU+fzoeZlOKEyZWWiEI1g6xxx9KJcR/MmSS4M1X00x0Zafe4oEJsvGc/J/xo69c6Tej2Xw0MJqd+HiBG5LpGGU60+ckryDXUQ7kw6PUyuc+xD73wR26G+G1V77FXhGClLLqBz+Y+jvXXqYIFgFSlT2kHvghONazXD+MqdobR18g6wrS39nJd3ZRAPTbUYNDZEbMFXIBSTRT2/edTWR7Erz7PmDllyXaj3I7ut2AgZnenG8AwAdFt4Phet/l2f9gLc4OcGYT5w3oAqBtyrEdpOSlhtqTP3zjv9VTlyabOa8VimUWG49wBhpuXqh8uJdc0czcHTc+QkWSMvHZqjADhrksDEhkgDHsVMXcerJ+g8ibtidJDGOcJXdyrm6zC48pHBiGVKp/X/4Kp8dzwe5M226h5gjRU2i
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
services:
  - clusterIP: None
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 3000
statefulsets:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: ghcr.io/b-zago/links-organizer/postgres:latest
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
