env: prod
deployments:
  - component: server
    containerPort: 3000
    envSecretRefs:
      - web-server-envs
    envVars:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: DB_HOST
        value: links-organizer-database-service
      - name: DB_PORT
        value: "5432"
    image: ghcr.io/b-zago/links-organizer/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: nodejs
routes:
  - host: organizer.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      DB_NAME: AgBTUnYxEJ7kmWqB5Z1iGTm9T2KzI9mzaV47dGUEgb6lQ8nIoCTZbp9rGyJMGThAn0CbVtJlUsnBQAO/LKAkewpFo0RzJfk3EGnjWYeuqjnNu4oJW/D1d36KJ4xHJ0GwJZPEqaoyVysx03nSsDVSn+KoNqXLcSdUZBs42M/m23iaup1+qAz+WwtYVCu4JoqmYrKJ69g61wd9RZonLfUxi0zNOeB5+GTjjnS29gGMqK6akOzMjXTS3/fHSnc8KjDC0DRTA3khrk81ggb7oMgFAhDwB1QwcUXkAE6BrilztxqvNriqyy09A6CGt/CGpiF2T56L8kX8iddEPnPPEl8wZRpaKH4vlw+/i4n/kXkcLeVIz1R7kc0l/oS26AhIQBGsEyDMMDuJWSbVpoovz3rCTWT/x2/a1eaQM3//dWW/XlC7nPbVpLDJ7fdtBn7KmQ6lb3/MhKC++8f8CxTyUK8l0mvj+M2lUs28P7HjoJwqG2VGgXTXliLJZxniGeHXVduiCfHHZ++rX5FEXUVK2FgebGKG3E8n6dpF/1SOLjg11Yw9UcV3MkAwHqFuyBxsh8NKKnIVe0CKj5z8l8eYxb9krjhv8oKLeaGq9jLe3YQGSeU99gW5WCJQqR/3HybczGTXQUwmsC2yai/o6SfoiUzIGGJ6PckEPLlshUcLdcXe80hdovrHZYjzX00bw1fMao1cNRMAwY47Z8TEOQ==
      DB_PASSWORD: AgAON95+nF272Xlta/gu1S/SdGHznyx2gnlXRhsaR56kzlCZfKk669Nri/QGWhnQReJuhAENLRmQ5DWHz/h/UUyhlcltBH2HV9FJ1B9ZWk8HiFTqYeVEt0fHXw+KFEPKiRxEgafjpfZ6n51oCb7oXYOVXJm3JPO4CS9cIivBvuF2K0IFiCdJgZDbWJFtXC7HQ5fwYdfGgyoZA+LwAEVZVQH7NOmT+vL2NV840xMfXLi06OQO2FWNHezPlILcqbRMWns8aHTqFDPuklp4GwBg8II3lc8ED/i9CwWvvlGYorV+hJ5zeiyx1tCpXfOE1YGr30b1Y/Of5z8j0dDzKduTH5GGcjDKA/vwuuihSWZPKFkeg3+KeU2sBiib4wVOgwBocPgJZp3lgfzahY1l1pCak7AZjRph1XZSoI9FoqTOVhoDTGS5xa+c+BXV2lu4HstDxBojJE7AMoDvED/rl2qmC1qMHeyjxLbUpnmCiQUYP9IGouvR1CT99iPvUTL9vJvym6RDhoW5ASix0JNQWWpCPigxDQ8XsTe/UmGoj3R8nVl4aTTYPHG8Pon0wTYC1Dg73auLfBANoPRWPjXEDfRj76X2vyG0pJ3J7S2top+g8+FG60QbxN9Kos+XHx4WI4YuzofSKPruZCHy5ENxL8mFDMhaiavqFFtkW2hXNK8GtqvS3Rx9KFSJ8GZdVqOkHW9sAjwWba4VY9Llqu3blEGrbyP4fotUtZWH8OINb0JhimM9lcBIoLeRuOt1NdFkaRWdjMH3j7G6jFM=
      DB_USER: AgCfQNM9RG83sxoR8T22camiVU5vIDABfudXBSQdLNmBgjy4bBW6OAjCEYnlYpu5T508lgrkI9yO3UTKdeEgo4x1n2ZOsYUDpL+qilBTkC3U+Iay2I0wu0jK4wdcGLxFdDr5lWlQB4iFMH9CDtkjfaQtCmqqyXumaKmjBrp1wFIuCzTs8ze2GVEPuKRS0LDST/X8TgaowNTotDIrBlCPU9CsUUHl4C0SqLd5/NJ93IKdIEc9WTSXIwLoEvVnEGV6XOn8GF4JOGRp0haDfW2yaYv2N6pQ37xoKrL+Ymx4q5xviw+lf3QQb0XREWGz9o12LSrL1RqG0yjEfpwX6dge9UupvrqZt+NXkQQQkBrCEbB7fBvY6ZL3yGyhuhN8Io5Y03VKZ8f8WRiVh9chGe44BTcH8EP4abmTwkU3mS8Hegz5mWkIpum6niGm4LuEDsv+66ZePDfiFHMx+0EGuSWO38O7cFiL+PIpx76TpJw5UWqadvdAMJETwrmoEfH9x9qNdbOs5nTcCEVg0uxDwhRHkvgxoVhYzWDjfszczimlI+o66bDJOC6Jnt4hqo8dMH0zXczPzZNp2Asvm7jy7PaDwdPFAFhvMZb++VDtEQENm3IaMPSOO23T5AVBzJjsl68hyB0JlHG7hxFNzdX5LSumpWmlXC9ThwbAnWoXp7u/fQ5t1+DB44jRzSKkrVirPjFDJuamjZPCbb0qZnE=
      JWT_SECRET: AgA1HMuAK+oqsnBQuOc1DIZ2igfB9dzX1EI8N+GyGZlQFZGHJBIyQRwxgJgREtmP23S/S8vOSaQ6pprhu1tC6Yt2KfIFTeMajJ554ujdMpYC2ziRq7o+nWOCPGhVYXkNw2NJOBVGWDIz1RpzjRQ/vTeIZLeO3rWPhW37yyqGFWRo0nAdoV104dkkYlI8NtK0mV4rbxOqAzevrEsgobrSWhY+3OCs6hET5h4OwrH33e0Pb7AQDFsxnM4hnrGNpKV/cKiFM/NofGlSlYdoEqgxK4+GS0w/1+ujAH6Io2ERYgec15N7VUdZgJuqdwGHzBHuc6Y6+zqwhXwUl97A4qFGpzd77l4/5GCr/mroA4kWs2RkbH+iVgfq1mqIyScsw9/djUfWTQ+jVi9sitAtqwXbVTg9X70mx4dV1v47YzqfhBnKaYhNxoQw+04SezEOTVnEpRGd4EpXfyxl/6zzPTk9iEP59os0aBpvlHvTj8Q/xJs+gG91WsCrH4tzbkcSRVp7ba0bGd7xEOXCiFzXX5Sd3K59J/CgspBW3p4izVro7B69pvqW9c9+U0nEEbLnWj4ykVt0vPhNdeMkOkhAxcQpvPYpgGfg8jfZNxfYLBUaJgPJETXHik0CQ5Lp1dyxfJE/sKZc7KX1NwIjtKbtOtd2OHQzGPJPC6ZmaZ+f0ho3mADLtiWcFvePvC1gcKG2d8lBMnySI0JSf0U7OIt2ZMEISS/uxW3Ij4EKTth2/ARUoZTt2Sq7urOcyHDIqVo8j5ax
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
  - data:
      POSTGRES_DB: AgDc3EuOgRKoB4gcIeoZfcYdygxfvJSJhyD/hKP0SFh/XPRVz3z2x9cm1KRFY66mO/cX5+NmEbdh9dgzMmVv0ACYQiffGg0MaTOgWhD6+DRmlf9zKk52v3X/rYMNCxD7dgBLmhdiWn5YbYcm3pmBo2b46KvZtBKl/1IIY5eGVqD6qc84zkrAY14y+vaw88XeeWq9Pj1WiTrWYzAy+ReQA9xUOH5XASLFVyMEPzJNxnLGEIXdTFGmKvAzWUYkVVpbNkL/J6AD+9ziq5YBqOhd8G0Esg6QN6ZngIe9Hw/pk5YmvLTtYuwGeF40oMYk/BCDUEgLPrjPF+Vmsyzep7LR97ZzDqb4YgoLb9M46/6sA6ihaCCrwIvNcE9eiZJkYzW5AylewCxGcXvgRJ3NOhTZNsiZHWS6rZEzhPQKAHlI9IBu29sSZXTQmL20+qfo2i/hD77LafqH4nPRzMUUpVnTy8zlhmrtvwV4ICZtmrzyLA+Ihj0QWpv8nxIvtGdo+Odo6yFWV8RvEeD+KwyCmTxiYOMdmjVlZn+eM1+xdErUrxVv6IYdkb9B8SbR1z+XUZQ1B2e8RkfDrhWfscvhMJkt6Nt3khFTkWgXEn+nQVdMUsVVermdtgqiD86p/RnJbpcRxDyTR2qd0yp7LEaie+TYW0w/dCqvC7hVR+y8H6aC3cdMIbispYXaLt536AAkHOHSKqMopXhAqgHdHA==
      POSTGRES_PASSWORD: AgBfspmVeodMnSTaS28+mb6iwEaqAFI0cQVYIOJvNWY9pbmU7ptq/kC1RclYS6iAmgPUOVNeSZFIiKSRYhVVHZglgyjIho0y8d/i/OA6uN+RJGCZSVCsBuB5Z7NflvvK58UdfbRXE8MWCsGfdXUAShTFAdu/6r7HuQ2IE8E6HjLRBwd7LA+5rRrhdJw/A3DFJ2kZ5nslOJOv3dWoovKV/Vg3Cn3p0PK5d+SFztfQQ36QX+TMy8DMNQXXoVWIiKnBwcOiGq2OfNLfhwM0vHZd7v7nElUx06vf4NqxniC4YaPaydy+7/ngNzrPROJRPu9NcDwfXbvfvZNA3e6Lqvj5RTD9xMSPQtTjmFuvgH98KoOcWdeI0ITTcF1Pzhp6zvH2uATkk6zyq95L+BfXsYxO+/BKuTjo1SWwCcTPWWENaY4YOcbn6+3a/Ht2aPou5uVkpUX1HJwyRP115LYPFAGaHaM7X0sZR3Y+o/ZkkZbgOUBV2IpMqYfsP2ne5vMyS/h+N9xNZx63gJN1NrUB6dT2xaGU8iurTWft4CbjqbBRITrR/JOVHnfVh4d2YgOGrbQ4bTktKrf+YiM9p1s+n+/zCkt9mYpKNA4l3aQ+UQOi2pNtVQhG0RdFIWGnW5H5uMNWwLA31QOVmCWELR0nTEzDhBS8p/NiK+S6fuo6NtZvw4nC0mJDtLTfUecu2I3z44kZiI0r7Qe2Q8a7NU/lwn/82sgmaLAo0+WPSi/8bCNkpyOXlMnwOGrJyjD8jYTeePXQk8EMfmkWKIQ=
      POSTGRES_USER: AgCI+GYN49qSCGvqDIz8xg4sfW7y2bsC97bEVkwmg4rh3gO+VEv/sMK4w6hP0K+TOOckkP6kG/uNpYJcTvg/Z6wTgy1tDJYoRj75IrGDmiA+IViBS85szMemLJhehbz8rF6YbOUmZ/kIE+c6FlfaHZTJQe9/EAsbGXGYciOgFkVDbPgHC3+Ah3ngq5SJGnfOiJsPRyE4rJOvymY4HPMzv8vbagNQwo28pCRM+lXz9qJIHIuBOFCB5waQXBzGMRGKev5J5owGfRIkAvtndzubTHheYBB3izx2eaSbCFjrgtaAppxUy7ogwXaettWPJBlp9pM5tgzfJme65Rp5UpGKKNxy+Fee/6gDRrZGJBonZeODP049oZZTRCOlekE+ihQAydXaCx4OTZxWq+vepXzXqnhJOTshiE16V3szEf2aLtv597ZIxnseGS6kYHQc8/xwYS5jjORBklaEAMecPB50E5O+2Y9IZrW5CSrfcrhdyMjz8iXgYhrbE8JZpsbGGn783sT0UBMkrSkKNCCP+uHbmQhO0BNXD1hAGr1qDxmY+Z6ctMPZ+O/jYaq99GpPxyF+0Hr7c7cPWhM7omPsa784GVuTKzC2OgNvmB8cilQoqNSMH/uIWruSHWPzuBtplvqQSsENRnGMzOY0kBc4HaBV2p4AM7wz9FpOOvsL7c8zRbp/LN2F/XrcFgjbNLQF2MaXsPw8wZvohNl6Llk=
    name: database-envs
    runsOnList:
      - database
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 3000
  - clusterIP: None
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    imagePullSecret: ghcr-creds
    envSecretRefs:
      - database-envs
    image: ghcr.io/b-zago/links-organizer/postgres:stable
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
