env: staging
deployments:
  - component: server
    containerPort: 3000
    envSecretRefs:
      - web-server-envs
    envVars:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: DB_HOST
        value: links-organizer-database-service
      - name: DB_PORT
        value: "5432"
    image: ghcr.io/b-zago/links-organizer/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: nodejs
routes:
  - host: organizer-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      DB_NAME: AgCQGeJmoSu/4egp2TUylQd1KHS4nNICTcwpKUFSu2Lo8ILoGehdfApNAlpn2JRvQ802wv+xP13Vj2miKlM4O3SYv4/LBWTgYZEocIm81ao9XUJveN46CqiM3JwK9Tw72iAxurIepCnTE3tfz7xxWbZmy7aURgVpplo0Ka0Me/YhKMLkLO5z80otNwUhl0wyl2TiWeQ1rWfA7y8HTcuVY0P5l4LE0h8MLlWbq0ouiOtuBFQkC4xKnIdLL7CpDCYBRt0jWgnIitb9OPDK0Mt1Yjg8wT0vzCL6XYf1dhBEkCZXGXQsNtWi0NyhjFN5DtDu+RyHKR7lMVymVadxrpOLjqVLMjyIvB26dTlEZQO3uU/B+KfKwl8JTxLV29UHfHd0/YueSpSiuam/y1uZBUA0Zhe2Rl924ONPdlHNnIscILLwOVT2Orv/p2TRAUWwNJM2XgS5Av05hc2nyCEvJHRE0dCRdhzWA5q6BVC4sR6cv1/qaVm2VnghaUpGwjTgvevChMHLcFopb2UbLBXOEY5sG7ObZI663dH/E19Aasu/5BLgqt4NP+K/hJJ6P0W17iENpV0OgYDyToP2veNfrnoAuu3AVpvKMKEb93EZp+xgI1ful/wYhSuqwxvtvCfVgLk5xCkuLEbHRoqHYJBjpxiBa1OOZ8JuFB9BAye2JHUpEHmsQMXAYBiN+2yCYHoq2HehJx6rwIICh7cMTg==
      DB_PASSWORD: AgBFh3dALP5KmTylwpNuYl+5eS9aXT22KfQWbqC5n9Vlw77A69Iw3pBi5Nv+5vyQ/RD8+SzGvV1+ctoncKmwpCLusmjoWAioCvms5rIK+TmLhwE+GRLZgWbiV392we3rPdlQhhOQnm3YoYDohw0FoLLEi7u+RYER0dWZiNR26FeDfqC4j8MZskWDRHz3cryJ87zfBkqJTftGaN9caruNzFGVxk0lQkP435ZB5TzManujjIxnvzr35ARahCV3ex1tUQZihU716m4RfbMnOzH+IxC2/Z/BBOH0OKlOyKozP3wHrePmNZE+a452H1A5zH/LwdSKunVe91NDfHIGWa9Ctcmor80pz0U8vOSZZeQHjIU+1zzwpqNqeZSATUnwG5xO+IBbUnr4CCuGvP46kfG5uSyfUvmYyC04igsQGjZyDxakVUQYBDfNLiTBLnphGKHsUR/6vIhqa/pAWpPyrLj7ZF5sb5vfz6ubpyRR6jXd8jPJXPZMXSycZvaQxghgBxmF918wmUu6RgLJugY7YOYQ/BTG8Huk78FM0r/lYS/yu1uLGNiV4vqFulW/1t4xYQPpcR8ZSBEV+b7/iSTOdS31VpusZyvyDoWqCu6dOCOxDx2ZF+ca27k4J45pZ+igDr3HkQkJfztOvE6Lis6/rpXh7+YzZ3EM/8Ljhwd0DAK9pqn+/hqCwKxe7zU/CFj/HH/jzi+YXMBbIUqdc23+JWXz2cKSC7jqlLQIZvPsdGD3+f5SiHCEhypScbJTtYagLftiwZPRxeJWCwg=
      DB_USER: AgAjnzMLxaHsGW7SFSIjp2Dc6OhylTbGuc4Nzfyl24Q6yR5xue3DH5VkZ/lR48SFrCeQqlWVD6iaMu3w3uOVMJhVAi5uZtwoy4cmRWKGS58JOftNjn4QDpOr9vt8ZrSUwqNFSqUmJg9i3KMJV5sKQOZ0/VxTQiwcXL91g+Z0AMvccY2Q6xFWucTcBrOF8ofSm+8VRvK1iF0O42MchDukwbbn98PzK7070w9BFVWTyx7WtRINf47mgp8O/f4V4YEX2zbDLbS1aAHn9yHIria4UlPGWdimg+HWJRFZ+UVyv3S2xFnIU+kJjnTeEkW+bYNzFwo94SlcrSleNB9XHLm78WmSQ1O5ZofYtgM/EgHgOAEgGuyBbQIaCw4MT2hYR7HMjRKjmWxyGPJrWysQ3p/gzw4rDcni3h5lgE5wQuQYbNhoLxpnKESkIfGMJkvCrox/T2jUfiCLUuqBsZE60XvHPhZS1BSVt1Equ2vkiZssn5HPzn5AVcpFLkuSfpjpmYKKmw2Cvg+qfhtoao4DThnOyNE4WznsBJW/s1t70ls8fPyBcBf4C/j2j7nLHz4rPNyGtSCGxUys6rGe4RZn/KEhyhFkU2ngQGdQVMvx4AT70xCetYzrmFaLvVagDMQKvwxmKOgypS7DP8LL8D2Bu5AIFZADZ6yPFrzx37/pO59C1iIzagjRj1QHZkcW6h04LGN4zfdT9is8FcP6Wqs=
      JWT_SECRET: AgDMYsMDMPuLSml2sbyt5OePF8kFYg4kmZ5Xc3GI5dnZ9KI8csRYsTMm2bcSiX5QA6SMccyTUs06THrXtfz2AKANCeB3L2bNGzyS9ps7GMpFKjwFuBDcbWGeNi5uUdFC7cKAu8eBMS/z/qz4p2A3H8MPCmNu9BCMLLYQCQZ6CJZoeNtqa4nyFRSsB+PgQKAZIuuAUY8o0ksaPLsjwEizr8UZTgbJ5NvyoA86oOv2t60GTAw/0Q8qaQAD4ZRqLD3ZdOEipklz3B+jwiZdP6F7ByXsJssjC6ZZne3zINInHZ/B+CZwSpo+E67mSbimVGyLRJWnH6mE72u9Bu9iOaDGjaoa3P3zLATvUtZzhCDQ0/H0aBBgnVLctXZq3EznL/JAT2Zg79m+PiIbstdQ7iI0AVQJadQtQtFWzmQQvzPEHjnFYkRNuamFbmwsovtqFJvRrRNyXgVZf/IFs5pqDzEXWfFqf2b3q5CbyLtZzOfvMvlYYOhdq6aRv7LOaYwfqT14I0YE08tzyXmxP/9Kfv6GUPxcgFmctovNR0jV+X6w4e2LTavePfkQjEiu74hBo1THCqmOkYvlJbmuVAWVY3A/h4dY6as5AYka6mnty2fyEnwZq7ZygtjyQ3iTxRFvI39DSMqvi8HXbRq5LmnM+r5sZQWdDzo0Pa2F0SIbJ2ML3GM12BLcd/O/5a3847N4H49Jj51tWI+I3h/y65+XFJ/Efbli2fOPNi9EmULBuNt3OsK38+W0dY0sCeYlr93meUnx
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
  - data:
      POSTGRES_DB: AgChvlb7c6o9IIuG59DWz6CbIao4tDwdTYimQhLPcgYOPaqvflwg7IXcVsF6bK8OqfyFseXiFeXjQrIs2Q/S8uzrkFbWExotiS4KV/cjDWwCkWZrqUqhr9o8fZkv1qfgtL2T/0wjbeHHpzZvL4MMT6ZGtqAtNTzoWJpj58+YULBlEbQxv6djCh8HKTjgkHJidpk+hEiaVjG0d7D4+uGBLjjZeuubChuEGmxy0xWrAla3xi6p2NUkQD5hHm0sY0P/0fG3J/1ki5S7tthN4FP3C9evs66WT3HRMx5MHKh7QZd7pYJq6AgKG8cX/7Y41/dyAtrtdIPQU0T3bSkROF6NY8/jVe2CAUl8ODUYKmQ+wvM7/ONjbizoQscd8QnbPMbGhvKH17X/Blyequ5/fcq6s0w2WednZVVbaQJFfd+V/aGTGAPSoytRRHgUfiLDvNBSPO/CakygT9XqYJ6gbX79ZqPq8a6ruPhwY18f3YGl1rpbBOya0q5XNL2xDnRuCf+1lBw+khqZ6sC8MbLjQqmqm9wS70LdzExdTkIkx3272kIAomoEabAGMQG+a3yzuXVrVVQVrAsbqWdhwLSV1Fe4OZnMmCfADl4CUNadXnTDNToWDRaXuD0ZtJlsK1X57y1jopx8uZksSGUiQ6TfCzic+CZZcq8tdgxg5yMlGSunRsBp0PYnnlaiYTwCRkyi8eoF3RYOhkNxR4mfNg==
      POSTGRES_PASSWORD: AgB6bDPKuuoXwODa26oCI/C+XOio7LpNoHXFCUmTPvBgenFCbYdpoAR3/cg5dU8DSB8+QH7OrpvBAvnEx5thdBuMyZHzAt7jtOfE6QZbEijsTR8D5dt9oSsreObjjAfEeZkxXf1GrHoy6UR8qwCVesSY6JgePn27hGAXywUV3kop2MEaMPjNjAzb9YECIBSWYlyDEU++pI/JNh8NnD53PelEX+CEggSLh6PCrbOne93wtCI80Wc4puX/uPzHWGXlgphe0Y5IApL7pf49yjoLzTzSuMkP6VCodZC/lzdlFwAZTDsYixDLjZGc6lur4/icQTSVSVGJHsF/pjqDbNS0vJ7O4q0VnlcwIy+srvbPVdW6zGfpJImJHupmBOm0AAHNXgnlQVRRcqHYBGy7ZTP15ITcedIKEDFuvhor29ihxBN91gA/819bl1vdK3Rg0a1WilqMoCeIRSAqqDmAZFCbPqaOrM5Nx2sQqX3inq+EgBYU9Es43WyMengHnjuM0eW873KeIPifLD/XeefI8OyJ5zz9mjHGWel6Fn32/blanVhWgS5uaEfGBoaEeioEDfT7yy0SMea5pMOfQovz5+1nzPzdB4wiG/i8DGwsKhk7s6SJK/GKE4HAHfOeqVujC9Z4o1XFiK5cjlPLN20NxNOZBVX+DXFPzCjfv0l7mbnHk3voheFVedYvxYnoMPH9r837ct1a/YdgwTVKd2LxMSrJOPNmVbnqWVITPsFWwZCBCr+mumjsQPO6ML6eG2/RtGHuANDoOiAoLVQ=
      POSTGRES_USER: AgBRN0E0nEy6zaZia7jN2KZagBlCgcwc1gTVQ2FsBo3Lg9PJqFfqT8zeNhde4THjtQ7N4z1J6fI3C0O6PDO+R01Sy3S7llQsH6SS0srYizhfMQoZZFSECR7jQCzyWvCjTYbFtPHXNwcVuWCqjAs4b0UquydXfGxjZsd8ehNFktYDPWFadWzgXwhMoNFhraQJK8dm+kKGAgcXWl0/Dxxz6Ov9yi6scmLZf7+xa2MEwnv/HMLQm6cLMr2Btb5XKMZ34cccQppH02UbvTPs67OxlH1WpcY6/ei9uz9VXuDjaK1BA+ZklcuK1L7yQ7z0nsnu7DORypNMxfu0M7MJgGkeW7q8elkyM42LPCpBQhwhVsqLs7+HMdg47yLStmKLZWGzMKrHNdxeyeDk1ydZkM/z6YnExf7Oph05rOk3QW0LFMTyGqRCggmAgjT6V7pIhK0QO+X68FnXLa0XMzsbfiz32cwr2BZ87tuyXtDK6/QlvHJgZuu4HYWnz7hB+qYSDskrRjNpPAG7YRv7JzoeGR8k3Lzr0umkhudsbfO/CfiAptyy3oS6CrMy6xOsbHqZYXLpAyMZ/kSNbwD+SVtxIOOyrhTlO3hZ5riRyoKfXAcOTMpQyngDeBgWIFUmnnCXweKDAuvWeS8CeGH+Hwse+pfrKvIOV0+DkIULIv/WRIuf12FSHAUkvvFK2sO9QAws5/65geySbACh0kpvuvA=
    name: database-envs
    runsOnList:
      - database
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 3000
  - clusterIP: None
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    imagePullSecret: ghcr-creds
    envSecretRefs:
      - database-envs
    image: ghcr.io/b-zago/links-organizer/postgres:stable
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
