env: "staging"

routes:
  - name: webServerRoute
    runsOn: webServerService
    host: organizer-staging.zagoapps.com

services:
  - name: webServerService
    runsOn: webServer
    port: 80
    targetPort: 3000
  - name: databaseService
    runsOn: database
    port: 5432
    targetPort: 5432

secrets:
  - name: webServerEnvs
    runsOn: webServer
    runsOnList:
      - webServer
    data:
      DB_NAME: AgB40b88PP27SU1DmPM2cGKyWjqaMhdUE96ebRn4/DIly9V+YFX81uMSh5jlGH1RrpY215i7qIqO/WrTSp1mLdzMQdyU8N2qlVtSbdbHijtnBN5RQYx8ERsXKFov6VCHH1/EORLvvx9KGurKwTls9rixt03Az0aBP9tAmzG2u6M+gCqY720BUPwVy0M4fzT7TD/EUv1td42od/HxfjKPnLdtDwzz5sHz7dzeieVxH5SEx+i/cBoKAS+qcZwHduKInlMLfPlWgNFcUuvkv0CiHbiTaBJO+Cp3jgVHue8Y3kkAWD5Kk+pndO8gJBSvDNDjfWdxcJzsQIUIv+t8oVrgOEngPwVHQP5GXvJOiB5uT9sMB/pFUqJQO6/qkmSOHwq3aLSuAEwxYrxGGINYmLUXiu4xJNrEGAeove44T2seGLa2i2WX5RUp4ULMFAlgbYp9P7Wsaiqp4gTpdKMZ7C7FXohrUZfkd5DARIJ+nAWmpqNXxVJToAsmMTb+eK+V/pU8SWmwnXxlpfzv/0njGipQB6e7UFzm6eF6YgK7sRE6aceUodXv4pQYQ7m+U/CDV1CZbbcOs6Jr7Ln7pmSTceXcTccY3oavj8oK3Gxn+KkVOBzAYPkL2cqMe5M90rysXa26797K4U0iBn/5nZfQryMIC0qDy/6fovB66Q+tsFu7iqdTQeaX3IplLm2VGrG/jirSjldG6siBkNtubBs=
      DB_PASSWORD: AgBqpOwqW0Cfzer66JNJf3uGC1fuwy/Kd5uNe9NWjJNnLUSMotybP0TdNcSDW/A/1qn8qS1mLKgDpsJRRf+P9QAAGRBBL0Fhcv5UA/49cWg1Py8oaWg0zIDGoTYa6DxD2KySCJB7Asmv8GbS4vrqPwCdZRSkQYFyN0EY73ayCsmW8jQX0Kdwwk4W7/QZLgDfoQhqpL9Y1WGVGmkyjKg2NcvVzSz+T4KnBA8bCwm3wc44Abo2lTaMt2IRklA6Yk41h0na+PbfvM2pgwzF98Twf+l/XQpal7Yj9y3XvkVzCej8AGylP+P5zTCwNt+RNtF55MXpHAcB23dmQf/Z7qd8+mbZiwqNntw+ll6Fq1l3G7R3QR19KmMebaHULF1+1GIPilq2hZoM0o+OgqwibPNp4huHtlY9yQFrAYmARwaqF/aHyg6ra3Cx0Do9B51L1b1U2Z8Skc+CLbNFlRSa/DijVuYtiRhVvLmVSwHjTPP8M/YeA1lmJPmxa0Z/owA0SUukjpNDNitiwcXpgTYK3RZIm1gPpKxGyNxd4ZDhzpCljg9hLwESPCD8HRy9DLJeoI7kFBLE8HInzIkvyQnPTetzt+A18GydrZDc3vNOaNG54rdrfBimzPqDKICRDU8aS7tCBTvgVdqqd+MOlb4YmiOVBQuTZ9kUCfThH97eP/PLEvaFjZ5Jz2YahFvnVoeTI7P1sX+M/tms3hJxXWXcOXPy1A6iAcbF8g==
      DB_USER: AgBOKKcOKFbaisIThoM51R2z3bJersGt7FhaD1HbJL+9DmNRFdgR9hDVJBvKexR86oOjz79Mb5X0Q9+6YaXuu3C5E/yIdveBjTUg1b1cdYBrPF0RsXP+CCU7osabHt3L/naEoejZ2fJTYZsKgcJMMknA3iXjat+gUseb5jfXpsLXmCafieTo4dYHoKBe1n1bds2LGVYIWPYBF0vlEco8xes5Bv8bqv7XV+D6z4VyNZZwHHVLeMyGlGZPfRxm/IyO8S8W/m+CyCmWQHZyAzIPVgGsTi2i2dDARqkrxRs3b5iiK9F4fZ6DccQN+A47C6sKAgHL0j9K17sPzAYWm0ABGsVa2GnEmJNlVix1g1KDq8ht/sxQnjxQ5HToc8fT0mIaeADnyg/QzDddlmiYpM5YntT7ldL9YoyaoLDhpOcJGkWYrf2q00kEUcNhjKAviQT//5Q9vRw2OipZWTMMEXO+jFyOCwaYFalkNFwx6VAspNMaZd7/9IttONA6JJ9jg3/RErkzNGY/+7xLSiSkDJQ3vC0a2qBCHBWLi8GGY+99Lb1FUz/t3YrL89Lx3RVweNG876th/Ogo/VhqxioEtgNk2CE/QOeKd/rSoS8npYEPhsTjKo3E/WkYZrleYDnLrW2kyM1iqTrutN0E1FxphOfu8/SIHYLHGcp2tnvefCR1XbSBEXLX4Iee+j1pedn72aMhal9r/Ox7aXm5
      JWT_SECRET: AgB0cbFu2ic6n3qAnC7gbZKgnpjgCIEhPLXSw94wKs+uyura9fnblfxYTPMAuO1xTjjLy2mgKw2pB58EygFLymWRhoK3MwBaSTp0hilcKrRuodS2kWPn0mYe7NDkQ5tvHQDIyTmFUMNwy2dyrSTsPBqRtB+0t3bhYwESo+oihlUfNwteK14ShAeQhYNPL7pH460QX+TRxGapZqlY6VMEkJtklvruLaOuiL8qNkF3Q7NIXOKtR80O+XwOeh1yQL1sPa1zlUFd5+//N7rSQVus4fvVq8hn4TfBlaYokzi/Cbtg5Fjbzj/QOlN2+lu6K2K9C2Do95hBWJGFSCyfvWChPKOVvVtcPQVfLuQ0g83yWq+//A3UEw9cfYOco4/TRCs1fE3kNhG6ii1WsYTlS1RWlSON39pwtZgXkZkngfQn0P6Yt/y4AJ13BK9BYQGW+cXOS+cOBRzGsxVaacuitUv7LK2SBwg77QX1ueULjM1mCLGH411x8beWvWLVzPRj+JYTWhVyk04d95Df5ym8qUZtG6atVI0LdDjq+LqFMoK79vFlQEiUYSM+gFULWsFK83Lm7iJUvWDql8KSr341BdpiW72OsfnEP2jvLfPkbNabqZsmN+aU/ImG3FMyGrFYV8oGAC2jyyfiZef/lbjviHhr5iJmleT28tUXKBNDBFrnUOgcDqexacgqsD4GRCkmBz4Lc4pQOO+VNne5SH80IIcvV7FABUonOiZn0N9zebjboTFTrJMNA8qj2mm0X+k7yA==
  - name: databaseEnvs
    runsOnList:
      - database
    runsOn: database
    data:
      POSTGRES_DB: AgAsHt2+8XtTgEJ/aZzOjL1FbluFn0nAAN4udD/f4lzujOkWIxRBIdG3EDrINjSCGx8woo+U39/PdzhwYRZzbLj36F/S6oixpC8oo1/MXqmvW0WKQZHPplg4qgt8h+7xXnVIfUKyfhVRBSQaUYnYebthwk49DTMsrJMrGjCt01pY/sZ2gxB9YXYFKGGlLWLMoP08eofJ9SXsJzmlGyAPFGDN+2omxGjj25pW3TqBMsYrxV5bWK3+qXvEMLRu8IrkRa0HHDgZx4+WfaY2GonU8MF6erqBfiCJCS9jPSKK3xZhVD9FHe6Zqes4k9e9opt0gD9bYZCdzG5TN+cK8PzD1kIZ+Pkk15NpPEjzHKng5AWxrIUtbCPziaa5y5pN1NZRYGkH19yyVMMTg/WJt3MwMvfNE+v8ZzLIkxPWscAeZaULOg2boXvsGSOduP3oEdeHI9PmF9EoTL6WShyryuyNShbynURoyhft7M27ekPI4pKJVJxO0aAb4SHIuMXUr9pnws17V+l20xKcE1ziweB4PXT9YKG7fgkVuXRHnrPqFBe3d3nsoqF4N57Lxix5bX5Bkc8ibTiMzXFE7NFb0EIATAK/ECIat7HFZFFD5BZYZ85zAR4Ea/9T/8GUHueJlcnj/0Lv8531pL3Z98n42XoTLofcaSVgM1Sfj6BuzgDTYgN2gAMH0pvy/m+K9NSKXtQ6IfqPzCIjtygnDBE=
      POSTGRES_PASSWORD: AgB21K74w444YsdI5v6pTqb2TbvU8dBpSkiQk5ebMpQCtc80pgDp0wA8nJhBdd1PFclLsTNJqHJk3L9wBVFQNJDBdXBtZVwzDuUOP962XK8OOtY4w7oRFwBaaNYe9PwJpz0YISesZod6qNtF+gDGGzNwJNBV9FxHolXdVMv85IkEtbPU8aHDH/sKvJ+QcWwvi2vNgcpc5McY2ZX581HZUtJK63LkkGkQxlFhJFxjUXZPQ1KEohbqulZS+etVYZOA+pz08dGZPFOS+txXv4xGf2o7+Yg0zwIJ9EI/itQVQ7EbJh4zBv4llXAmmpESJONoC1nuy60unsm/qmIk2QbVq7JCVEUX5qTnmdQ89BIjihvyUbifNlUfX78X0Fnj0C6PBEbwymEYCQFT2F+0Ox2kwU/PFWIo+mvhIofNyPPLIKjDwltKEfuTf6sPpxWU8eosdX85MR7eSvWDqellO64MJXcONfBeX+lx59q7o8s0DqOqJaS9iR+t/3k8v/gXOha0YbTeGPak3/AuqbwU3RqRARfsse6wNpUibDQLRqw82I5NpDIDtRn7nD45CYrjFQ09E7Kz0773f4irXE0hbDq54a+SkEXwRm0MiFPAn2wfPWeFVqrJk3QA91gtqt8UQsPb877PSwm64i1qab9xPAVR9PNYMAEnGI+2R8fhJWXYciEwnYo2efhlhqjERaRFA8a6dcCSo6Pj44zYMvJzOCPZktF3NOAeWA==
      POSTGRES_USER: AgA85bEmxX5kyzvwtx/kNZbOfRVfHmXm/CLNOg+7mfhjwsoOjKwT0DujMCYtdsPYaXgHPGc07Ax8SYDsxRKQpkP7gv+arQa55DytbbLcB5dPjLm4UL7inlWsowUD5lz61Sf70I22bA1UPiAR1Db1pjebnKoJIySJEfY0BVhGKJFEaE63pQZPyeGMO43RNsiHUX6VBukaq2TrTc8Oz3r7pwy73iUI0y4AstTBgFhYf0Nd1rVSxVqV8gMaRL62czj3fMshvqoV/UCmB5fmpXUFx1eCrdnvWoDBHlOB/LcCICygP7Vz9ao+Tp+o577Q7oiCezOv5ocnATZD7j6lArDHG78hdngqxNU5sVmy/W2J96x1bfTIRAnwY53L5pAtQEsdAoDlJ6xur5ZF0GWPJey8FOnFcn0l7jJAalXMapS+uJ1EY9JdOm3SSiqdLkHo8dJNBcpDpUX9pCZ3gWXJPVIQTjmR2U2l/juCROExqpp+WfaWlXgeamzMM/rOQL5yWfHuP3KKemf9Ya9peakSKveCPQf4dc5nWkxEpe9aTS1+7kjKxkK3Tulpr+SefFK056aohjaWdaZn9zApJnd3sT29IiZUCxk9RRw5/xkTmTjiNnzWBkViDhE5WQqc3EqJujYI0hGhJ/9rO1KIrEwS7NRID4n78YYHwwmk42C2VPwfndhiEZ1dN4Mxx+W+HqsEl/MThOf1j5XFPUAB

deployments:
  - name: webServer
    image: ghcr.io/b-zago/links-organizer/server:latest
    imagePullSecret: ghcr-creds
    runsOn: nodejs
    component: server
    containerPort: 3000
    envSecretRefs:
      - webServerEnvs
    envVars:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: DB_HOST
        value: "organizer-databaseService"
      - name: DB_PORT
        value: "5432"

statefulSets:
  - name: database
    runsOn: postgres
    image: ghcr.io/b-zago/links-organizer/postgres:latest
    containerPort: 5432
    imagePullSecret: ghcr-creds
    component: database
    mounPath: /var/lib/postgresql
    storage: 1Gi
    envSecretRefs:
      - databaseEnvs
