env: "staging"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: organizer-staging.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 3000
  - name: database-service
    runsOn: database
    port: 5432
    targetPort: 5432

secrets:
  - name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
    data:
      DB_NAME: AgBhG1e/fYwSJhfB+D89C1JcAsKyKZsLbicCcO0m/O0PTIH9dRP2IRqccQBwQw6XS6OrFGz2mT61q7IvVwbdDW/Qc8qHQg1tbwKaUBc0VtF971h9hJxAWvzcjImGy7LDDGvaPDulD5iaYj87bsB7uh0Vh5XWlg0dmZNl8LTr3P1XC/SL4YTHiIyiFOr6ZICZq68UoEp4DjZvNoWlpmZbZUgyfnsNB0SS1WvcYquh/baJD5VopcCu7yarycLrisHjMQFWc5w7OXiCuc1ib+tW0OFNg3tFuO8l7FAG7rcLMV9xLMfDYOfi1NGijdL8K+n88TONvvPH9s7WbqtgFXaY2S3QIb69jF+T3rpJSZ6d+VWES9PkyrG995inyHgyqzKst+bOfSwMJGdYA1cy1wJC3BNN8Lt6dT1xEL5UOSF4rO77BKckx4njvUEILTthOhvvkcva/q1j9AeUcHeo8u6/OpEJaNDfBULjliwSciOqwj7bNaYZ1R6uzOXUm5JGOkc03nJfkgFyy4krji+/li6IEVs7Z3q36YIHEieFnlsN3qhS9QbUSW20rX39zfVh2OmE6fZKnoWjqCAEaGoHC+HnCzARXtoAvhqC8Zl4O/u0aHZhUzdGt8hiPUdPbYttu0wijMY23cSQURXmxD+I/piGLJUS61VRSWI8+AnwQD37xLUsK18JBEBjNNdeInmyT32Zj80aJLA7ewYW8bQ=
      DB_PASSWORD: AgAuE+WA78vV/YZhKpTvTqlrgJud804znM01hvStk6LtLKG+jwjpXESfx/PyLXhv85YGPYzqc5wFtsPWQXZb15SIce9SSPz8/W220LWg9qWVCsjdHFH4QjewHHlgKPJJGU3Y0TIInjPl7v2KVG5FiHV2xy3ybLDTrXoKO+dktGCXFFOkK6Mw/eOt9rfGyWYXDP/DmXsdKjckziQ9RRdNQMGdGZqV/YGyLJz1gNmQywR+OFabigdNSSezKka19vwMYh2A+FqLJVqhyMh3mm4XyGc/Q79Ogtd3/D1I0nyF4VinAzpjE0zkmgiUumlxCmBno8kiLJKXOeWOn1AyalwwkfmvoklJwG+BoDh+lfLieVJRrbOw8XqzdqDGaedPmBniDL+hWcWsMr/4IJ9nbJxk0RCMU78LULsayjtpDgqZjmBPxOLDGgk3/W4onWL0N0Bcl5jbK0fMvtRFM8iuKeiYZqXlPaeY3adA1uKd+bb3OuHygFFdosmmb0vQsRoRtUBSQJSrKerDKX+pdIxhlu7AR/Kugn39k4qXrOp+SIg+4Hm1Jl+mR4t1P+yb/QiEu96ouSxynOgbGrUtoBXhzQaBlP9Y8oXJ5RHcTPPmaAohmBgX3HBjfWcxWaCC7nkRw+JmQwkGM6R+wczjpVRK7h9tLt5RAkUAsKPggu99ZYDTa8sK1uyd4zFsogd+fh/qZqK3egFSgfOyfm/KPfmeVbeo1Ptkn3/JlQ==
      DB_USER: AgABIkZp+IMcWO8+IxSJcDgvyw3vqyNfYwJ7g8MNOB+UNknKKoInvY1W4qQ6mLj9GFWMTKHeSv7MBKrUCeuakPvnuVlLTC31jlw9KLtW0/OeKK8AHHOK4MM+rU4SWcQmwI8jHGxvSVR7lau7j7olBMgFD/QGVQmfB3x3I+JNR8MeOjBVOiLRkhmNmbB1zNu5fKD2uOg0sy308UDyrCdrFdEEeICgtLX2KXIZ/dNBFQj00cKiHB4s1MC41+HeLq3IfqI9Y4hCKN5VOalk9hX7UK4Ah2wiQumy1j4iTuAFxuUBWXMNjva63tYxK7s+4rZZjPZigzePd2UKlr2lT5FwuWkmlt8/5xVotgT7E8AmTjERljmBY4oTCjzCRfEkEl5hOLFzBjU2uG+EeJsl7b7NhgFU6AyfqKEpINQgeOmBz441MDt1EHSWhWLOX7dNgYj5CNb8KMxv4G6S+fkYNDRbidakzqXKc/GSLCFBNXM0GPnhwH9EMNSRmxtuaPNiKqUgi4vVxJjr8s7zi+gE3HOwbVcs7Rui3LqjoF6EKZwPuf0X8fczOIGAekEBkXRuMY0OqMa60cMjNJQZvCgdo6IKYdeTGd5WjHc+FnBwS2JIQ+o4gf+AyQhJkISvUiYzyS9JSmcxAjgiJl/0MGRmrkqhjpr15Hk4VLCpBLW5bgnov/jzW08omHcC2EA1qdy76CktPa53TxHO7d/l
      JWT_SECRET: AgBVjX9EqpJSgGNqv/5soA8/4gyQIl69wig6izqKoKPMrAFPgvKdh1bPkB04LDNnQzoqK1b2qq+eA3Qsq4rOCrmFJIeqqN7XmPVaZyIMM5seU/4mWbSqxc/Qwz+KgLxXvTz6hL6HJ9zYTq3YQoT/IsZu6gN0up0Ox6dXcW2hxo/OoTjNzsXwduU25nyBuc5TCj3Nj8C1Jcxrb5i704wbr3xyCGTf3PTsVU5rwKcG9lRq+5lJLCZ0roa5W1vwK0RCgeogwFSfWh8W7NouDVxj3rNmOfyJI90H7hb2MRlNfVOldDX07TUrzrTSr/lclJBhCnLA6dvboluZ5UOXxw95bh/xeud1uv+3O9nL2r/Mqtr75VfJoWno/fDeBCXb/2CqqVnteABVGtOZFrchIH1v3ISo2R8DfTf28vWEzYEAaWRmbX39V1NSmmyoFALDgHgcDELQ/QoVXVettW6mLLnOBEAILT+95h3K6IxHnoSznqcoUTumuJC3KVvszvEkxyx5xRnUbP77a/AGrlIFO2OlGZvofDqSUyT7E1o2Y/5vrsZv7mi8MvFufrJ12Wn3Xm3K9aj/bHeep0MzvoLvoGmP3ak0FdclPNT/RV1w5gob/8OwaQb9yBAznesZM/B0I9SeTy0rbDezN8dBGJiMT1Rjy2JPHRtepSV4uIsK6lLDfDfJOmbRg6NbTgEZeinvCj+k5X9Ydpkh3LOPSSRg21bAnwbAo4XqdL/w1ssxsP2nRc7TbC1tkC5z2w9djUEZtA==
  - name: database-envs
    runsOnList:
      - database
    runsOn: database
    data:
      POSTGRES_DB: AgCVPZUCWmhPDiZKtA8aXYXZWh57C4znt6DW60mLWvx5ibD/imVwhHu47EFoeFZaR5y8K464OZmCvXVEEvtfYVA1FqIWkJzxuQ0RQGFKfX7IjJuLdRGlKZYi/MMa6UR6GIeRU6HTmVFuT6UrcYo8AymFGVesSQLYl5EkogkQFLr8qBuxU9SCm9lZvaf7aDhEjjl5hHFx9ct/CsnVpbumD8sU10jHfhlrGeUSpRB1oY3PicLj/tAF83lLgHmjIR8dnmXhfy2rjG4zFu1gWb0f3IlwLXmOW7Ah7mMdIgKMaKafjsXCdYTtn/eJit4taf8t/1+gX3mbfZlwcPNr41nGQjvgm/kTy2AlcF8arJcR8oSo3OdkcUShn5c17y1dnj38OZ4A95mOuTKRc0ztnbSI5qQx589JiwB3vNxhmH4y8UMU5Gk8gqSIHPQ/lBMY9c5zd7I+iZhxW4R0PvkghoDnflbpHER6qeIJ1CpA03ZVrbN3NrmgPzLvap82UCkrOO7P+pNA0bNIpRSkkOKX76PC+1Lb0Ra4x6KcKwVbbfVNHa8FmFmPq3Yb6e84ohw+X62NWXzpI5bJqtStQT8T+XVg4eYLvxXcWOz3Tfx61e79S2/yX8degZWNgKHA/PdnYXsyVZhra7UauFvoQLuRDE5xetT547QZek+PgIERcQgA+QtuKj8Ph1NQ394ZD2ydTr9STh490b1JGnINvLw=
      POSTGRES_PASSWORD: AgBszhCyrWxddS08LAu279Eb0hQlc27jtO9NUyjnt9JacXVxAcd60vFwMDanRAUOgohYzZ3mz4nDN1li0F9eiCwD/IXTA+tlglhOT4EWJ2PqPK4/qqhghDelJqHtwBDKSBxgGpmF6+ejX/aZ2iRBjFWJOGWzrTjVZFqvNrA2flhEDEMrfIL7/n9emHxXooJh8hs9NoEqz3lAUBqOohU2B2djv2aVS8yT8BnQ4zS9cyrv9aV8XHYnsDhcens/5INeEWtm3jTyqzsdcpp5FAsYx52bx1z/Txmuozwr9Ke6TjLxNxs2lANyauKU9uwUwJysoiZk/aCb1GQgA+GlzQsufv87EGx3d7Jg1eNwplIzUcb6WOqMVcN3/yr0I0MgsKFhqFjwZQhvlCgzXv1UGVEXZxCk2zw56sz+nnffSSpXOOwtIbvFws11frOBWzcVFDyp1kzG6mHPsSK01z1VNgfW4e1UKVobDvflKdbdAWoCjE4GHClsOvksHT2cGSNxHN042FbOlAW4LkhytUb1HBR9t3yL8sh2oysM8yZ2yH+06B0pRQLa9fRtQuS5V1Vfkc0lR7Dgnhs+MBsf4FZRVyKh+bIXe91e4VOCl9J/nTmPi7tTdxCyqPAwHm/Cl6NjqcoPtyv6Qe4b+0PCkg+Ec1duNAJYALVx0XLfQE6lLGVICnqX3bgDjr5FlDcOfBz0u+TkA2z6mvIfKWlMW2ng8HQxKckuvBtNNw==
      POSTGRES_USER: AgCUOoLS/sUXO2FHDyZdZeZxnD3b7auKWdqpHMvSLBEY1oJJeB/BCTa7OGiWSvlSMSqVsdKYOSJRsZz4VLjP42xZ4jll7EfCbybDttNNH8titdOUmyHNgzmjRcVgKn1seTqFsCGberavsZCvOZf+BQQgpnTgxldEKL8B11fVRvHOuwtL5m4xqaqkXPEwf4CRin/jcXb1cWm5VAs+0EVYPZk4t6tAj8+9kXq9EFUj0QYPen30uZ1OCmy0ZCJdJuQEx55C80QxZ+QM2Fp/ltyjBTPgvF/nayAyvBZrwnsSzQrAioZIepLbCfilVZh8qmPKdSovWN+4SKR2fVz2RNuLX8A9+ADNTRd7lwQCEy59VLfyAyI1POQDjO5VI5hh92pFqTlF7h4jl/KUFLI6NlR7HxX41MoTEtiET9AzjJ8mrLFzXNcv5F87yMbcMK2v4xS1I1LtOqfeboTyQ5KPo4BE9AMKP5aT1j4Eo54xI8DhkuQavQDTwsWInGphVJMQMBseU58disMoGS+Ze8BWM6EYBtUiho2RC5atirhtrRQxUIiJcpmqg5kImGRz3hEzSjtRqYZCQZLkTcP2vk95mcGNxGV5EsSchGygKz1sCwsIWlCvlbW++OHWZsSQHXrJ56x9itXvV182XLc3qcY2l/qDBTkERo0XMnyipFj0nJO4tBnnZ8GpweV05v2L94H5m3FUDbuX0ocMAwXF

deployments:
  - name: web-server
    image: ghcr.io/b-zago/links-organizer/server:latest
    imagePullSecret: ghcr-creds
    runsOn: nodejs
    component: server
    containerPort: 3000
    envSecretRefs:
      - web-server-envs
    envVars:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: DB_HOST
        value: "organizer-database-service"
      - name: DB_PORT
        value: "5432"

statefulSets:
  - name: database
    runsOn: postgres
    image: ghcr.io/b-zago/links-organizer/postgres:latest
    containerPort: 5432
    imagePullSecret: ghcr-creds
    component: database
    mounPath: /var/lib/postgresql
    storage: 1Gi
    envSecretRefs:
      - database-envs
