apiVersion: v1
kind: Service
metadata:
  name: ships-server
spec:
  selector:
    app: ships-server
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ships-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ships-server
  template:
    metadata:
      labels:
        app: ships-server
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: ships-server
          image: {{ .Values.images.server }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: "ships-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: PROD
              value: "1"
