apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgB2TAuX6Vsprv3q4dMKwFFpmjou2bft6cGN7OXyEjYV/V7YFMTCR8OXUGNV0XuBMAlEUZWPxT83Fx3chtsoC3AasYNc38o5NuQAuwVOSSZQJYjxTI+vircpSvI6RrVF5cs/2jGBTrWw1YUev8erS3s326Af/dk9VWXpXUhTrly/omBCQmshEmPWqctRVADpZcSHNBfa7FiKBmW2yGRmFotqYuEIRkuVBHagvUG2HxVLXhNexu4wHfPROlDse1QvxyOk70q+BXCPV1VxEJzGTjnquG1Hu/1+62rEQmOudcCFbQUHlHEFFkpq41qQZVNdhOzIwBmQurWdVZpbnKv0BcmE3Kzi6g5RqIvislZVIuLDSn7moUWNXd35BFaABaWOe0SEKSHJNbDfczuictEKpxWQ0IWeGGRTXtsuZGNk/qbbFFhv8b201LXwNrUvCvz+25KmdrBnmEd7iLBAk0+oR3NlwrA/cCG4+tLLs3+WJIVwzfzdOX1ZLJxnijp9j+ZLq5oypvOKasRFo/TNsvftsCApOjKh99zAViGmiIVFmdEUvReMOKzpMl2cZyWikRh/t+zoYL4F2vebLSYH48qcnpwUVEXdr70ReZ/Y7ruY7eOwhtWy44M9xX8JEUirOp7kRS6SxU+WaNx4ItxrJ0I3kYQLKXrj/P2tEgRvVRVHSVoOYRdLjbjRsuNLj9jl8/CbiqU8/BtRmoFI7tVhzxKg9huwq5Dlbix3pu4yNjbzkkyHF4+Y7eCPZT2hsq/6nqTUZ8plpuWJEg==
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: cert-manager
