apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-db
spec:
  selector:
    app: {{ .Values.name }}-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-db
    spec:
      containers:
        - name: {{ .Values.name }}-db
          image: {{ .Values.images.db }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets
                  key: DB_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secrets
                  key: DB_NAME
