env: staging
deployment:
  - component: server
    containerPort: 8000
    env: 
      - name: ENV1
        value: envir_value_1
      - name: ENV2
        value: "2"
    envSecretRefs:
      - web-server-envs
    image: ghcr.io/b-zago/simple-test-api/webserver:1.0.7
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: python
route:
  - host: simple-test-api-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data: 
      SECRET1: AgAw7n1b5ANlPf8tA+9fR+oEfCJdpzqKj7E7b1f47qC7EIb7A2nnDD1humfQvFIpwCnASEPshnHD/mF5hKYgg0SRYIBaD/t8Z0frmNRH/J55WjiahzEqg56edyowYlvTRW7dS0b/w0hg5ZmcYjskxZD49820VIwJG3rpWKtR8IRlDw7jRc/vyHNpF3Ulp4n2RqLSBXKzpbzW6vo/WBmEm67ku6bGPbzlv52SWOUkIqUIq/lQOj3+v+Uq2X+r6Ukksjt2my7wbqU4l4qWs8d4HAoyjjWJc7KMxcYvXNjcU/jMajTi1tWRl1uSz3IMb4ZPYxCQsnC3d1hkaFa5FpQzClIg1M5y5XPelClV1MATRe9+NmGkMr1foHMNqOZE/PAScoRPfgbHJ2XJvF1DY/5vkot8319HhBGFP2GMRDegG6RXvCx5HRhk1YBJPpIjTCEMkELTaC9ZEfg3S6ratNbCVwa1wyY3uMcOAId/ZDrtvn/8MGnjsu0MCKJm1dJNimkBk9puhZOVNqwT3BxttKmHjTEbmHnomwg0rWUWqq7iQwvpmEgWRkwNUAXibz/qbgrMT8Bi2tJpKfqNRsaeMecD0QrAGPFnnZiBqXqVHfBbCoIkB/5SUtMKnQDHMN6ce3HbG+NI5MDbUV5neLrhk3HNDuwyzk1b8HAVGBNjNJM3Uyoj1L9KdaJPLvuzzdu+q1yL/1xYYSA9seWaSuzB1Q==
      SECRET2: AgBmSdNF4ezC8hm3yWRTNGPp/qYygGWKIN5eNdirgUkSeVRCNYDPdY78zhZWqH0TJkF6PCfsHhGpDqglJ41M3lTO1p7tIl/ZrH+6rrfpFslYbK9REsroVuwNUuK2dkc8PDKvXak2u5h5KmbmKQDibkl1KcrjMsGWUpgHjwSlqihJLbeIApS1WMXwKJ/YYmW0LPR3aBBl6DwQhp3wkuoeD61zK9LFvDGkKAiBJ//fC0kPzme1ygAST4BSrH6VqQeymSuNHEYeLCE6kzxjQL4xNaoTbSaEU/uSt6t5BiEdsZvnbonIgiRVzIZtxXy6Iss6GWjmNYaFKZILgrPtGfGquLmCqQGC47vIpNOUsO6uJvlNddyaI4NQCfxRUTC5NPq4iVGoINtLEdjKrd9UOWTnmM7U0u4qlUXuilUOo0sMsuJwyVUjLVmNd1QQtABMFJd+GLaB173biFii00AbiQScwPjRV3FJfNL9Gw/J7rTkS11cMF6OF8Z0qSY0nNp5ZBo07WmUDoHfqX5DSal8bvJlWwF/NYJ1g7kI+XKRAQErMzNw3zUohFNEbnwG+Wk/lMR9db/FNmKDeZnsE7/zYCECEHg+H2Vwrfa4CLRL4ZJMM1WP5kFPSxk0rhs538X3KF2OfdLk6VzjN0E4dBROY0yr23lCexESe6XIGZ9hKSiPAtASomPtvExgZ47Gai/ehyIfAa6yqkc8MoS0OL/tuehosj4=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
service:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
