env: staging
deployment:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - web-server-envs
    envVars: 
      - name: ENV1
        value: envir_value_1
      - name: ENV2
        value: "2"
    image: ghcr.io/b-zago/simple-test-api/webserver:1.0.8
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: python
route:
  - host: simple-test-api-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data: 
      SECRET1: AgAApPBv/SXhaZOmzyYVgMTIGsykPyST1XtPR3ewAR2dMyB5zpB3vb/v/O6JddmuQGaw2eZPv+rbbN5uFoCim0a7VpNhTT4EUdh0CdsZykb0fyD4mfblO6T2PtTeRvnI02EU9SzONgmXRNILqqV+qxY6ZgfMwUuolVQHk9BjG0CJ0vhdztdjOiD1AbFLcoL9CupHvmagSURV49+B3+SyrtPKHvcSbxbY31yJxB0x+xkNz9PvfLtVF02GAZsykztiVCRiZgUkq551ORvWZeBhVsJF+QgmpaRwHswXZquFkbTPgy0fq4k4nQjraFFWkjRdTq3U+qq2NNcwY57o5rw7znRAz/++vU5bF8anesP7Zbrqoscqo7SdOSRn7lt792fGVHuWaSHKFjVNQsxOWAMtksOoMbKprOliba3BrrMQcdd12hBHm+3tZG4ouPLTSy6dchczuUbF5ADZyhP10KVxPLYn2nB6B30JvnmSXBtrH5r1t6AKgrv0HUVFNj/+Ve9bwf7H4DSmbMw2RG9IKU2DHCctJQX+qg6bKSOQ1uoUZnobli76R7AGUHiLv09YkC+GoGki2AtFNowMBK4F872EcUEDMW4EdxzVA2CstXdC+GlyoTr/nHvzVG3f3m+3odrm7hKebyQRLtO65Yzm3qggFZh9S43l24NmEJKIMieyTCV0GXdtlkAY9oJjjwcNDn0iHP2kR08I/xk4QAtkWQ==
      SECRET2: AgC+z7T+oxTgkA/BreUOwAlGzixNhXoBjRKdr7YPqcMAqclEO7Wjm5g34oj53OIGNC7X94W33yrR32D4WG7enJwSBxpQ44wZxulcpYzf5hWQdWDt6iMtm184CU1Gd9Eqr/xFG6THcjwI4Yq4QDyfsxNTTCjJ8hTcKC+Yj9c8ailZp6T0VZIxkxs++NlMvIANZLdZRlo3pXYLEke7OPPX2RN6Rot3iLy36JwMbmETqeS+ecKxRMekElnLEi64LSputkHVvKq8Gmz/CDNzjad9kSQzH0bVnmUcmE8YasuAxXBzdhd7x8KMFv9C5FK/O0f6PIkl3qEhlrFvnyh5S1Xg2a4XIzcgxacqXDM2Oc7M6x5Z4O2B+CFJley9nY7zQW35Hgde6ZjMcdwKpxiiJsBM0Ji7LURlUYyR+O/4qzCVKuHzcT/L2ikiFVT4ZVDBWO6WbX/bftMnxnNk9q1yE6NmjqPQ/ysIilIUxp5WhF9bCfzqZnpYsy4U4ZfVU2h1e2aFNVRmOU6k4gVl8MkjHmIDK8fLkf/C/gH/Wuulgaof1VSJVhUZGuAa7i4YIBgGuI5tUQZlWNe9AU1sOIf7M2mbTPtg8nhRCueunbmCIH3TaPW6b0UrZpWRQf24HCdecOeexN9OG6EbpnftIvuxzktbACXPnunq7MbRReX5obc9Q2RDBIgLp97N6oqcenfOHJwrdDRPcSJ7LrkI1eUA7R0noR4=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
service:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
