env:
deployment:
  - component:
    containerPort:
    env:
      - name:
        value:
      - name:
        value:
    envSecretRefs:
      - web-server-envs
    image:
    imagePullSecrets:
    name:
    runsOn:
route:
  - host:
    name:
    runsOn:
secret:
  - data:
      SECRET1:
      SECRET2:
    name:
    runsOn:
    runsOnList:
      - web-server
service:
  - name:
    port:
    runsOn:
    targetPort:
