services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - PERSISTENCE=1
    volumes:
      - ./data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
