{{- include "lib.secret" . -}}
{{- include "lib.configMap" . -}}
{{- include "lib.atlasSchema" . -}}
{{- include "lib.database" . -}}
{{- include "lib.service" . -}}
{{- include "lib.deployment" . -}}
{{- include "lib.route" . -}}
