apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/b-zago/k3d-infra
    targetRevision: HEAD
    path: cluster/cloud/
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: localstack
      jsonPointers:
        - /metadata/annotations/nginx.ingress.kubernetes.io~1whitelist-source-range
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
