apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/b-zago/k3s-cluster
    targetRevision: HEAD
    path: cluster/workloads/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: staging-app
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/b-zago/k3s-cluster
#     targetRevision: HEAD
#     path: cluster/workloads/staging
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
