apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: prod
                - env: stage
          - git:
              repoURL: https://github.com/b-zago/k3s-cluster
              revision: HEAD
              directories:
                - path: cluster/workloads/portfolio
                - path: cluster/workloads/nyanify
    - matrix:
        generators:
          - list:
              elements:
                - env: prod
          - git:
              repoURL: https://github.com/b-zago/k3s-cluster
              revision: HEAD
              directories:
                - path: cluster/workloads/*
                - path: cluster/workloads/portfolio
                  exclude: true
                - path: cluster/workloads/nyanify
                  exclude: true
  template:
    metadata:
      name: "{{.path.basename}}-{{.env}}"
      namespace: argocd
      labels:
        appset: workloads
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/k3s-cluster
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          values: |
            namespace: {{.path.basename}}-{{.env}}
          valueFiles:
            - values-{{.env}}.yml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}-{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
