env: "prod"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: ships-staging.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 3000
  - name: redis-service
    runsOn: redis
    port: 6379
    targetPort: 6379

deployments:
  - name: web-server
    image: ghcr.io/b-zago/ships/server:latest
    imagePullSecret: ghcr-creds
    runsOn: nodejs
    component: server
    containerPort: 3000
    envVars:
      - name: PORT
        value: "3000"
      - name: REDIS_HOST
        value: ships-redis-service
      - name: REDIS_PORT
        value: "6379"
      - name: PROD
        value: "1"
  - name: redis
    image: redis:8-alpine
    runsOn: redis
    component: cache
    containerPort: 6379
