env: "prod"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: scorevault.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 8000
  - name: redis-service
    runsOn: redis
    port: 6379
    targetPort: 6379
  - name: database-service
    runsOn: database
    port: 5432
    targetPort: 5432

secrets:
  - name: database-envs
    runsOnList:
      - web-server
      - database
    data:
      POSTGRES_DB: AgAid54hUxZmfg4EQ44f/N7Df+mm9mvxp+A81deZR0vjwp44wqtp5FqqySzGt5lnNp+NyrjtCDezubhgv0L/j2bfVVWlXZqgr/m7CDVgpp8iIvfcsdLuRyzHb44ni9PeuFgF9kciK94dYThNVI+a7ybdDug04l5TTeayQF0ANFmh98ZMLit2c45Z+TRVEWdg99p6lZejw6mGmc1AUobFdbELAK6HnJyMIcsXHK8nA/0gjOlrwu4z7aU0fPklAsSvJxw2RMTOpLm2/dPiOC/Uu0r7yBQZW0jWqN5+JLjc9m+PiErI+3Lo4RIpZaiEqcE+8kZ1MgOEcLLQ8WbLpb3JFixsQJzkHxI95rEx7UtxocwXJoMhil6kvyXjZkX5Lce4E44OWY4tMGD23ntzpfqW7GRtlpDNRtmMF4qL3t3xoqBYHZmzArQ4TzDXVZnjcZIAojKGMl6bYyE8WXgO/dzUnub8Ahec8/Oc18qfYChw7FqJDAAsa4Uz+6iGqMXG9JRfuB9erTQ3VTm8YCt5utfwOvCG0ULOB8HPGC3YYqFp7qxDDekn8V5qJBDvWnZVRgesVL0GPz6fEG2orz6catLIaYb/HjjWZZt1Wj6o7RY62HPjkWZjYKn0zkWeqmTkjDEeIHoLNX4IQ3+Yhr3e+VGSKHn8BA0WxagnqktWMRy90/0zaT4PP4muHkhWab2zTmtGtIb30HLykXJUHzKp
      POSTGRES_PASSWORD: AgAzYs/wGMN2MzuF/HPahOQEPH3khH9BjrCXMs3wZoI2ib4+X5uC2W9gnbheoHAknji7JUBjI9eZTUVB/0iZy0axOMpFsplcyQRSdJc1PqVJJUDDuiS7YnT+jSubnGnq6omZUMTSGWD4taEH8b/Z7QJMSoGmE2t+xRA768N5HPBjvb/Ktrpn3iYYk7QM03OvpJ5gmJnDAycA4v1/gsrItyRmwrmZ2tJTE9GQ02xbvtVkKjY8vWj5Xz8Ef25xPrw6QVKPuQg6sblvSxB00UeAXYlLu+T+A1XIXWtRbmDwl1G2j6m2n+ZaJGDrcHFt1La7nDHighSPml0ZGlrrxitcQAwEtEBNVZfxLuaa/cQNze69jHGssidz8IdhSiuZO9YoZpWhSaQpe0u/nn99ZG6Jl1gEYhK3SRUn43YyShBW2mkxIvG8r1qgTKcUgdYe09Q5ToLIU/rdsNvVDfdZbIlVKZYOkDj4iuBZRFb9Qmk6ITXHJlKawt+W8alHSBALQa4jh/giPiFnltfpG8+KcRONxl6LTM5BRPNpQNmIpd5/3Ru3j9Bk6Sx+meNy4GZ6FaAp63iIwcktecLXG6G9oQpXw+7+70M7T3xinWQd9ZhXQhhOhKhOr266LrAqm69kGzaC32lPSxdV04HrMRWlhwyc3mq7SPDMF6Ohc5lXUapLM1pBmtZkrdeg1RuOP23UzREE2hvftOsKVZwEUI9VQQ==
      POSTGRES_USER: AgAMavFfyLPNcgLyndEJJNfEkDHard2hZrKtwDFiiVGDSStW6d8OzBFjQFHULvkcJd3RrNZBPdsqTzzGKG/hZe6bwsNbKd1BH2DaFBhn1HQ7Jt5fUgaO6JCrNr+9h0vAPC9+mxh+oHT0q1ZjtciQqpaAvAyiYP17vFt3ZexGwxk7QBmdRpjl4VxqXirm0iX7xZ8q0wn7FDuK/uTypB8fygetFANRs4lbdckTiosGWg1PJ5v2bATnJa5jZdSvX/PY7v1TWz1MiMZHCnTZ9epGW46aHV0S6lsV3S4l2TWcwRPU8vZ7Zy9LEC5LsJ9Q7s9bbgQbsX4hVUhVlH7EUuWUV0WK5htODxyPYJUjLl/hrukA1qEuZiTPfcz9xRjtoEEQd+q67yZYZkD507b44zPrKHkidIM6YE9jPu6iSq8DuPzOd/dBfbwAlD3EhjuRtAiv1SOwEKgko0/yGxzqDDAm2dGGLDWBekvtqcUb+NI+vPQO2lDTaWBP4BqneFjclWq987dOLS7dGJrE92GCB3LlBSe7JAXtFrEddzEpZfnlIF426MiA7GKrP/CAKPZ18QICHPxabdm6Arv+2F+0oaqBc5NNVNW8JP5swShMfNZrSKp4ehUUhRppFmikENxfoSgobTp5HdUFCWCEuHRNE/dBt0zcgbLcSfkd1/z6JPadJtGSMYjqxSqJEZ016IG8oBddCRQSbeP+Terg

deployments:
  - name: web-server
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    runsOn: python
    component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: scorevault-database-service
      - name: REDIS
        value: scorevault-redis-service
  - name: redis
    image: redis:8-alpine
    runsOn: redis
    component: cache
    containerPort: 6379
  - name: database
    image: postgres:18-alpine
    runsOn: postgres
    component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
