env: "prod"

routes:
  - name: webServerRoute
    runsOn: webServerService
    host: scorevault.zagoapps.com

services:
  - name: webServerService
    runsOn: webServer
    port: 80
    targetPort: 8000
  - name: redisService
    runsOn: redis
    port: 6379
    targetPort: 6379
  - name: databaseService
    runsOn: database
    port: 5432
    targetPort: 5432

secrets:
  - name: databaseEnvs
    runsOnList:
      - webServer
      - database
    data:
      POSTGRES_DB: AgATDTa9lpQAx5I3R4v/blKdJLfK7sZy/EaTQtnc6cdOP9fuMtwfggM5Es0AJuvRyj+eUZhzoezPs874miIEykg9bH1vsxNOh0ltn+XMnVKvWfqco6BVd5QU50S+gJ8ZOxove3ZuWsSBAwlc/NAicLCkgdaQnhmq2Qph8fihG50jD6hFY3NzfNtY3gEScbqFFi1WN/S+GPZ064BWMtWhPiu9z765dpUg1LOe8EsmrUHwDkd7b9gZFaUbMYEC3gNJwc78VSLgzplUpBvpfo3zvVY8rhtWI9maoEfxpvJ7tGE7bHTwhzuszNuiH2+SoKj2ZG5t7cPbNBcC7vSug+8EwxIOE+0mowuYV8DfZ+/oqJtRQag1L/KZEYlCU4miLYrrk5yktgp1LZXtWcyOCeLALwTEUC6pxnL5hZOIEtWQsjbYpgcqcIVn91cpX0R+Vj1veKlZ7PaIxmjZ7xWtvFkaJBRXV9RWOKmdTnrEWTbP/dK1EhSsnxhGiK+UbW23DPbgvX6fkJugPzbp2+F9wxup0gKcSNah0babKV4PRul0KFyjcT2QDY82yA4oRubjdKlN8T+bJ8/snAqkbbZi4dT0a3v/XUTAHE8tBfdtUmBDgnHkaCUfe2WEpBRZQ62YVNwVQeo1atRTknVeE2cy4HJIskUiG5+uaGRJNUS1SdL2kw1X/ZBb82xxJilGDw81Asep/bvf7o2Ad04XyVS/
      POSTGRES_PASSWORD: AgBGGkbejpwh+WK1VbPhvYRw6U+Cf4CYm2k7ToEMpXrUfh7glXEjRQ/pDBCwfPdbhZ+EjF0lEBNHYN4oj6IKBisPJ9gBGWJYuURaW4HDSlRSX0uvCVh6nBhfON+OV5Syvg+KdrfFOkoKBduggq1q5WQT7ysb8Zl0keQsveSjhXCiRq2cnzk/h0ebhhBEMOrK37ss0FxS+XxSXNuEko9lPiKtVYJmJwxZ6aPypxtLs0/dxIWGJzu/Tvc6L+QdwMS/tFivJvyV5WGQ7dHWSe/LAmfPVZSpAKuOb3T1OAeClSn/90jgf4boPB89ZAw+oFvaev+BTINQKDbu/+iyRGZ4cwPAGdFNAMwOqxmjD4TbYFQ7EE7Y880D/BURy9YrnYAhR4YX4VQNU/gqMrP3B9RGTHjyXSJz1E/QOlSF5TRHbUEUukgPfYnUD8LgahVGc5KDTHVL3+s8520Di5M5tJyuBRUjrGys/rAD/LtC4dqudO+8B7UnewIdOgXG8tYCsmgcmnGXHitkjWdo9K8LnBTp0qj8arVxYYE2zKdhaewBB7hPmIJJhr5io8akA+v8QPlmKcthdHne0+qnI0L6MTFG7toOBGnuk3BhBIpQN2t7HGBnMXO/Y2GmbDfyt+LADKyANsSc+AX76/gKDTqEEGpVViyM4rxF/3KgK7W2+hk5hlmVo/Uy9WMzNFUoyq8eRr/RhJ1AQLqIHkzrbePPYA==
      POSTGRES_USER: AgByNW9DJqpqs+NBq+UsA6T3ynrqAv6UbMGztiJs0LV5I+EjKc0prsEj6pK8zI7n8al6jiw5CE2QE79GyYLnBhbtLMV4mu8cBM6YQZYqj9wo4DytjHkSgRip0cl+WTDMzz6Y6i4bAiFOC5SihD0I2gqbEkOiCfU6RkrGH43Yo4YnG+YZDC5ofOsGDdsSJWUVU5iXMCgxhknmdMAUXEQPRSmhwjHgFS7uVcw2CYAejfkGqn3ffbSDA4Ei+v+R86V0nl6VJDzh++mVTK+7N370G//ZWAjzlw1v7bSP6GJE0na+AyfHo/tONT79gyw6xAq5MhoNMNC6krB6E/x4MPQ0enUxDLz8yqs+ynsd/zfXkpIYE6Dkg+gUUvwtuZ7oikrWRRc177URBA0yY7daR/jo6Q6vw5xpe1j/pKVM2gB1OpW4Ryuy7aAtrV9s7Rp4JvL7qAzHFrvBIe+somecYL6DmlrKOZgA6w52zlxqSdna/fX0rSaND/YJlvGkfqYbguJ+65dyXnfTcvZb8S2DIpTWcnddS6FIAOm33TTlZOdHkpaZrtOLbkd78J9GU5cOpd/cbmCBooRNf+oWNP061l9GbbaZExda1YHBYhvepGxcxZPG0CTqlccqCHvsu2g4C587DuA41J4Q0gwzJLRAhLMvdUiWjPjGV9mOJkO68oS8YVJ+Ru/0eVqdjiHQCTOjyh5Rpra4dbC+mTFi

deployments:
  - name: webServer
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    runsOn: python
    component: server
    containerPort: 8000
    envSecretRefs:
      - databaseEnvs
    envVars:
      - name: DB_HOST
        value: scorevault-databaseService
      - name: REDIS
        value: scorevault-redisService
  - name: redis
    image: redis:8-alpine
    runsOn: redis
    component: cache
    containerPort: 6379
  - name: database
    image: postgres:18-alpine
    runsOn: postgres
    component: database
    containerPort: 5432
    envSecretRefs:
      - databaseEnvs
