env: "staging"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: scorevault-stage.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 8000
  - name: redisService
    runsOn: redis
    port: 6379
    targetPort: 6379
  - name: database-service
    runsOn: database
    port: 5432
    targetPort: 5432

secrets:
  - name: database-envs
    runsOnList:
      - web-server
      - database
    data:
      POSTGRES_DB: AgA4kzOzaCZGkxuuotlJVoMnrMKdul3mxwVUf2X6uYTd/7eA5fh7msFLngBKrgSS2b2rexICdw6Yb2XzoLsfiGVks8ogCN9G9gfURs+/20WDnKgtRkZKDo4q2LidgtwgJi4VvXcZSnW2/MRE471/+kWS1hFyb+IAtRSwuQuQuH/EkG77n6jkU2uiR7AWMxA+kK9olFC9B/sCLnar8dXjAGjb6uO/Gm+SxA5M2QpY+uF5Ss8VbN2gqFqytBMvuHSl5mM9O0HC7c3cXStPhJ++bCDjJGLNlCtmGPE9L0gl1sommugDlteD3uVlFEy3YKv0CtlXSxwWC8rn80BQOiSvpzovDxfVmXTRTODcTdhGM+U4fwXLnxQN/FOYpIOhOdwLFm8KgVJKkFCkYFws9OieedaW7RqnvJ1LfAh49C0EvuJgeIYgc9n3nYkUpQVA8AHeNzPHE/xzNXazNVO0wcnv4bJjXDPOAfWmW2lpggQGmMbg5KlcfalZPJ5kZxPKVPg4A7fv2mC9roF2Fc8IsCJicfIGJhvINQZK3T8v0FUVv7vccXqOVwHfgkKuvUFQwGxYCi3fsKL6GIgE+pPyQZNZFY7yG+xlvvgfaKBraV1HzAy5gq8+7DCL/28FzanXFyruEKLtL/ZawMqAW/IzJqTmyNJNrCZwYmKu5J8pdwVQCvHHhmkfoV3AQjJz3YEKpSf6VxdJ37CIfO7LXaFk
      POSTGRES_PASSWORD: AgBVfIO6Zxs2ndzH6DYTVxeACWXoYQrmR1gN4rGzElheuSqH0//N9FgBN/YS99ZVnxQrdSIdwgWoG3zB+xiPrMAUVxqqeKVr+aefDoXO9gcEBBgQpeIUTg+Ue/3954N3F2DTDBVS6WlO0uCMTfriod7QyN3K7Ka9QtCXCAvqB1NCQ1+pCFyvtqmOXrLvVqlNA3qgceUrm1xmty1gopHZdTe5b4LCOdTmF1I6lsk0SxAlRwuKy1CVGcFS2BJ0Mu8y/4gNYKQH9tEjOAviuOiKn+4c6vNBWeaLYQU+RhjWtxAHhzolFb4RkGYPEsGip5RTJfHEJG1WxKosl6ILqycymcXkfA48StIbhadlyaMoidPyOShwpKj7z8qidXEt7oXPHsiRE0cEP3m5Qz7iuI1dJei0RXSawQ0orkIT4i0zj4Ml9nqjRhTUVeT2ws2ftwOzGngE7LIOLs2WcVGXVO9cRdPacr2T1HDQfuzVTit09xbrZSah04QE88M9KvdAGzF+vU5koD7CetyO4EPAKsdXHGNI3L7eGepy1W+yDQTSjKPI7kN9UcnHcg/CDAWHAyiPVFg9MPv/0/l1Npn0e7aXCxP9lnioc/AX9C5cg/1+zjOdmIwzCT3aaErvfAcvWLq0NXwPT59W6AzHpsRgg7aUuIrDKw4va1x/VEFCqU/GLYiFjPf03amqlG7ReQmuneP9XIT0q/eMP2LFXujYHw==
      POSTGRES_USER: AgA8A2ag5VSQOXKW+LRbn3L+bP0w8aeIVimE5KnYa2eTbMhXvmtBKIm2pOZDRTZRnsBFUYu+DXKF2PokK+E9bvZR9Qw+AfVlymSeoNCMUE+Gl1jjJeYKT+Pyuzp/jy/MtXjW6vsKkgTW4zDwKizs2ERB1Swm0/J95bARZ43oSDaNk+dBnKGdE3Mu5HX+kuTFL4w19zG3yDnEgy9hxW05JiuDupXKHUol1ITLVzzuhqXFAO/SeBkjCxiS+sGlPWcNuDAm/0I7780zidIUaDrxTKy940axGFlnqjJT3gBjGyaWhl2S/yCLQr8lnS0jvMFdlJuKzROs83tKTuifTrAhUjDu/Di2opFBbFfJlGI8T2WznYzHBOrIezBsyWefbQe7gE7HPPDyldc6r/QHtbhrDgtFcXL3VYrvr5g8NES9pmp7W3h2HRufnnQht770PBScIQ9rTOPx74tpkiFXJSAIJ79cL6ot5yBp5GBKbO9/oObZ/IravkJlheF8q8f/JVGV/7y9PyDO/uweHJ7X7uLMyXI20oCdgiwBqpY2GZLicL0z1iFfNaNjpyUvN+FNJ+Q5D8UgiDleU1PwgeNssXYKIGoCiKLYZKCYuATN8ojFzR8Fl1i0KeoyT7QwOukP9pIf4ErfGr1/ZJ5TvVDCLlT9qrVKN1LYlHJ88QCcGcgX3j8nyWU6mrSDaaENt/HpQ3klMJZ/XBWmkFp9

deployments:
  - name: web-server
    image: ghcr.io/b-zago/scorevault/web-server:latest
    imagePullSecret: ghcr-creds
    runsOn: python
    component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: scorevault-database-service
      - name: REDIS
        value: scorevault-redisService
  - name: redis
    image: redis:8-alpine
    runsOn: redis
    component: cache
    containerPort: 6379
  - name: database
    image: postgres:18-alpine
    runsOn: postgres
    component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
