env: staging
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    image: ghcr.io/b-zago/scorevault/webserver:bad4cac
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
routes:
  - host: scorevault-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgC53ObJ1ogjJ1RZpGKnv5ntLFfYJZ9oU/0Uu4eZMhlELOUS1Qj8uOMY5LO0mk6bbOz5uwExOpVMEbrUr0Xk053k3MNrTTcaFXUiId9n+WREFfBVS7VhMh4WptAQ03PycRDqKi+XPmaF5Mv5AafTqm+PeC8l2LhcKieUJ5w2rTATxDs1gKWIjX8UV9afEFDC0kSrq7UTeowWHuNcWjQLoIQGMTXwMzi7k80T3NYpIIUaWz7Vk8fzuQWdofrKB66pYIC6WCPtZewhi+HnwL7r3xS8/ZvMxTsp4HfLJDCFweyDYhi8x0F6//1U7U+tbhjb+GkBBh7EG8EsqaM4vtELpTVLZ0xAD4iSlts5Jz2OC9Oj6oRF0rMYGebgE88Bri7oknH7EHgiQJYo2VsdwVx+EN+/HO4mnlZrn68OCdmTEYvTfx99awa+AQgAYuKfB3mn78lK9BUqEdtJvBZA1wMgGpMqJjCvMJNZ9KU1II2UZBJaR4GDtMqb5Pb4S9uCB9vLK+L/oYEcYKCa/touwd25CXlS5IXCzYXi6LIpR8XIKazCAtNcdu1dyxJJeEgNnydfWn5s/eB+Htkn/pChwxAZEMs+s9itEsN80/1PV/hkxe7YRjU7mm+JnnOSvCMBZse8UcpAl++UTHhSy09f1KbpKR8/PmnDlDWEibMoY4ZCqVrCsNBRdRY7zgF6I8aCa754hS1Oazb2LX4pLw==
      POSTGRES_PASSWORD: AgDZzCEFaSOoqeGb/Vc0uC2fqq+QrqKeUW4MFQ+pVvJNxZvpKM2EQtk++MKm5AXfZ+QdABGxd95qL1xoN7WpH+Mp28WFEgEIea98qre9GgOCxcUg3IBJ9McUSCYii43wW/M4zXI22zwiwzvb208oAzRy1Hrdcgm7HpZmvJZaVQRktUAFdarykjWQwI8Wb8QEpzr/8soXhMyviz5VLi72Qj80alqDolYwY0MhjiwXWxt7pW8RyVrJowJyXqdrnTkDZJlklvDT6Eho+9rwxH7I+ACgMufXC6lMgXEQTXg5ooQO2nIVONn1kx5K3dtlMy7wGIDgvn7ENA7SqVYgnb3zu3qiN0Ork/wNJnIN3NrWKgKixAcLyIyNF10vo8Xd44RmOnFr1iVma5duJoiYh0miYD1R2NR2bb8mlA1w2EzmE28AByrOLT5fhirDe8LPF2ZdKKNF2cxVcr4nCaJ/RJ2f1HCri0B078eUkqfvEogYrq0t4dFy1B+sn5Boz+s9yll4qRWeTB+aYi8wLZ8jAzS7+qbiXZipsNHj9h7mLWo+qhkuvOupQXAmq0kHELPg90XGu0QUORC48+BQ8+pqUpG3hArN3tOiw2qpVJEx1fqNy+3pawqKN7LrXlv83Dlnd9VaGHFOCMc0bEN2IGfJjqgUEfBe3PHENVctdas1RrV7tUmreh0zvQgtUDDeXMkxzzdgmveeGwb28/Xu8g==
      POSTGRES_USER: AgCx6mvMJpR9kFjAzI+jS2Fd8TKbwluGfo0drEG4QUisWCZHAVN+abP8fvi85t61sV8HbNTzDAmP5IlTrTBEBLNKX3zOV4n1dp89N9LYXnosiCWRT876YjcXdEpWy4p6EtFMzD87KAuYohJ71O4SYXt7E1LBWSYKiIpHodipAMlckvNXSTQW+wEYKWhF1KqrxDrXhVlnaD7dAFExdJvKTic1UfNJ2SYQW5TT4HGojQRFfOZKx4VaOEJmhxJt2PlsMidGmvqr++HbR+i4ZQbHS/q6fWzgRTuQmUEbAAYNsBXRuCO3Qbky8AcMvHSHrUqZbU2VHivRmbr/58WMw2E+Pfy6wI5U53i6JTnLEZrIGEOgMVboUGaJFYbsBsJxRsKOAL8sAeisB7KWkg0kT03fywU8mq0EMWqBfS96vMjhldqmFEkmBI5HuRrjZdLteSRJzo5So/KT7sVMpbuArZxCAvDQXnf5njexlkmqivYrVsdQq0QS/f3s67M1XlHonFggpg/AV3Fz7Ts7MhPGltViAyQ8VdBp00FFncXoQphdI32E3XJC3l6TYNSdI+uJaOEs53SglXs7n60pwk06WznANwSIMJrhdkxTwA/Plrsp/AxZVwUD6M49eGLO17KFRpxTkJBqS+ftQO/wHsLdCnB0VYCrDrGoNBbd546Z5DmdLmNlrjbUCeXhuVqwwx8CKCvt5VMOOkLiws6kQA==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
