env: prod
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: database-service
      - name: REDIS
        value: redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
routes:
  - host: scorevault.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgC8XGUpPC4qhrgmzVPirfDYw7BjVrFlxzxIKIzHglij4NpTTnFbWCZh/pNFKgA51WT09J7gTZUcT4awD7Bv3HLwZvGLpHp49+AGrR7kF+XhSBp6R5K4LGw78rKdT+C4q3a1YwVNKnEKCUr8cUFfqKoSQhAT0Dr6OZZ9WLRjZmh94cspcrd5F2MnnTkL3T+9WaKa8qOtXGNSoPH1o+vZC2HUSrvpiAcH7ugs512ElZjwn/TcRTFsFmXwEJX6ln1pbg41vZKN1/t+Os/E1BxAHrhpj1uGUZH/bHW/yPxT8E2l+O/vbPsglkOXi+/KUkVpHf+HPkV07oWGwM9B5KfxG8AxheW1MdPxUFRwDDC/xU7tEJyxHW4Rj8td4y0qhI/ck23kMnzrJAYhzXcDF7NpKnfOP/VB2Z5KQkohXunmpgBZaUV8oXGmmA+6c9azHjTaAV9SnnAcCFjwZ/11lhIOQjz7I42HLHDdzU1PZG8B2IYERcmHxpgdPXyEzr3jveLd3uX9xtaUDuGZuPBUrJrnm3s5ElRYlVn1amx3dMRg5l7e/gPuGSgED1cYOgb88x3oeSlecHyK/IlOkxkkkJYcZCAgiLahtd3moplSTsLeb9mjePO66wDJk2YpFS2NkwIFaW2u7agvB/dT18N9rhDkDyhsEk4TcDa7WM2YruIT2P8GVygsBfQelq2tE3R8EGOwiwx+MQg2QuLm9A==
      POSTGRES_PASSWORD: AgBMokrnPlVX9/b6BWmNgHUxtj1j+6eR/BqCO5EKYbQs+nu7tlqUHIfMj3FlJRewkEBOwex2SPzb052VPj7jy04WYvaublEn5oqynk2CLg4Eb4VLEh2ieGRDnvzSkbely8bxmTmZJcrt4AAwQInxftsOfBh1c838Nuu9UceAt4cOLgkPzF6Nizppy7eTpYCGUdKed40P6Gp0JIIfdrwq5AqYHs+ZL87aiJZJucjuFHtMctE5oXue6hPBT6Ar//Do30gINpHS1AmkHYpawcF7ZCby61G1jlLP/NQitpebMnVXDNBt7E0di3aeTrmN8bFQ+IITVLPyUUQrvaiI0UliualI+f0cRQLbirxrwdIURavED1Zu6SZAQhVvB0V15WPhgHJNwcho9QbylxCiCS3HFYFmzCnfTRclwNER+meOemnjqA7H7yphsLmodruHT3NONvwrGvCGd6iQt0uADmew4SZVWGdoBK/vG4i8ZXQ1nB/U/9UP9G0jWWkmWtdccqObnsKI6tMhAzif4Zyti3tAIvP18ruhqeYNxW4EQ5K5gSuasU8OomwY6m9TLCDT7XF1BfA3Rh+UFOCB2VILSs6I2N/G2PkOvjtSih8G2mwz409iGPxbNUldpSPag64k/CsyIc92y7DjNLBk9O3J+Rzph3FTJNtvBaxMEvAfvyNBPV/wLll/ImF10Q3SJfptNHj3QA/jbIDvijz40A==
      POSTGRES_USER: AgCSCcFuTGWLAa4Ovcu6n33eo5S7yx+FshOzi9MakqjVlbP7uOoQdsWAQITcwy7WFXCBKhgC5NgVgI33pJdVDCoh25ZQQtyeK24/7naVNDUeVjozoU7AtVdoMiPTkDHYHUl7q2bpjaXYt9tinyPSe7uXtGgdR0Exa+IHNc6GGuE+3Jv49spP9v9cWZg23ojdB1vpVFtmbofO77VJ13ZAL2tSfZMZfFpgON7wNtu79ODRnUIaJhydzrFdLLodUvZTlGyxAh62QAwBuVofX5FA1pBfcLC3wBfp7d36nkIWZpaO2gaT95iaSKGtCopKS1ePSQgt8h2iq6LA3MZyvgyha05xKON+uAigUZk0lViVhrCZwHkSCqNkKrbPBY91kNoD6mAFo6Dj5SYPeJKEBmgYOAJ4m3zcK3ARVkFr40Mc6hakoZsYnliNtZzEXSpo3HrgRRXy57VubcMFnEiDMT9XD4p2gL95UJbDOOuAgU2LQQZwTaECr/rtrxrtaFTdbuQzjQ8EjjQ92JJuTvXKqaIVb5p1thR3tGv3YcKvE0j2X0fcPknk9k7gO0P+wX2sqDrSLG2XHKYEBBFKu8HcjxP4hhRfR/x+27sKhk432upM2PP3a6a1F5flkWabfAk3zn3qkTP8lz31492lvNlB9S3SmzoiovSJexGnWnsLiL8Qcss4dPoGPkEc/9porPAychjWdRXAubIEWUYwsg==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
