namespace: argocd
# additional resources like ingress rules, cluster and repository secrets.
resources:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.3.7

# changes to config maps
patches:
  - path: argocd-cm.yaml
  - path: argocd-params.yaml
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
