env: prod
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: rikatest1-database-service
      - name: REDIS
        value: rikatest1-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
routes:
  - host: rikatest1.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgDgYZkesGwVPXwiGCaovj8SJOkSK+Wsix1FXFj5ojAec6OzNgytZSex5Sw96chlQtp9Yph5qpOI5aI8QNDjogzSsfuX5g/9yXMKw7ti29AAF+d5BYjpWq3dzGkri7eGSxAzti8HBceRSfR2hzHMzbQ9yhPaELiYjJsDMSDdduLbHgvkFq5yb4BkNM+Z2jTn3mzKAKWbwbxf81xCJvGsg97zEWUeotzttOXq8KzJzWnJS2ALQlw7UwtfuolkalUF8RPhEhrkXaHfceUvBzKcqp+nm+AnuilNXeGen64V9vCHZSV8zCtffptW8qnXZyvTHDl7nW+/d/j3vF3NG4BxDbqjIk0aGZDcUoWlrdRDsJt0/v8W80pJ1ubhykVUOvBNvEhlZUWOWFzO35vnTVRzlNMkZD7smJ6ygzIU0ku5F4qxkicjZX0nU/1CuOAzYbf1VS2fjfXg2IdYNEJbWjGyl1x1xnarEzcBB3+AxotEHpfUM9jEgy0U0Iit33BsQLGWQ/COjeGUwJtvW4l0ObAAM3j07Rk7huZfLCWTqOEaxak2TNtvpX2YexTARjhKv5MPPu4eLmg7+W6QI9NZtg8FDCjVLPWfmW3k59EIfM9yHsHXVPG+iL1ILWWbcRvlpSccdKwoMLPP4sGfaNjtqaNF1kD6fCM3kd9PA5evvrduve4fHCDqOnG0cTORdVS/8v8PNub8E2ltzDNftcUB4whMs2Yr
      POSTGRES_PASSWORD: AgCnZcizT55v64p88rLTFtscINGS017WB7pRY/oy6PzdqyFNXRDnY+t2KWin84SBGxK82kw2pUvcH0qMRqOdCZ2UBPlgyHQKEBbzTTAVEfNRlZxAy8dBXQHlpgR0+4ywDetz7MIbJiFqIsiTL+kA+ohYLr14MeFS8Exh7ln0iroB/ygB2PzKRef+vwD+IbPVVXJTv3z3JH1iym/m6iftM2Kku5HS2yZ79uBknqpCHn2Qu5eVrVjNcR2x9o7iHT5WKugWthVU8cvVyOv5ptPEifQjFtxlZuIfPo6aGhYYxNBxbOyZB3M6PEYSGrg4bcQaHJ45dLPHHHvqn/CpY4/+cWuuVPEltipirLCKgq29pgGwh9CU9Y01SD6SrpzgXMLAUztFCoukDqeFVFP8IBVUdqxk7b/8F2D86M5BziZLrKKEX8oCZb6ZrVddzM8GbdmYO6t3C6JLwcx8FWOpM9oLO+bxG6kYpM5yc0/o2HuF19XqwcFNCWzft5Wx4Q8c908Kl6wRIX4Zqaf1nzGYmG11PnheyMnn3tIsyIClrGa+lkFi5rypj68FEO9mu63wdYtDV+HQDDao2ym5VeJwJJZCc93u6KtV5RSPHqzGl8GE8it0tSKvFD0ibOPotJaZnzzNQ90I7DNmWpqHt9HxsVzp/EVY+0IrBMSpgEnzlM632fCqgNNLjVRqTobN+6+y5Txh3IL5XxaOWdJ3iBFeENlnU+QG
      POSTGRES_USER: AgAofHj3HAmhKISaLNXe+G80T/OF0YhZM+0Vtrj3Vxyty+zDgG9dqRXSQCi5QrZ488GKwMg3Dn8+hEnNN+Yp3qCj4e/dgidhu20iZvzL9zcq+oSYjy/JaRvsELGpNCFuc2VzVTSzNWtACDL3pT/ZNbV/FSPE8ydn0g9k3w7Ob6GESk3D+IyaA42zb+3Nlb2M37aNCMoU28fW5kbwTMsZfaR12WdmyoJIgyuwGmq2ZPRbm9d5pVvrbwhYXMuKhX3KkguFPqBB5NC+d98JIiFe2i6NVjdu3pGlO+Xp1VWm825HJz2q4VwRsegGIAw0WDhZErVUZO9tQcM8yN2MKuHwlKvoVgZdYp4PmwiDqN6H3x93NKoPXCX4A7CIaYx3RR4O0Y3TmktdMbppoWe7YCDb4EyB1xCBYHkCzgEIj9rMEprc3ZwnC5qw9DSoQGbsk7ICi4AcquJGCiyRe7yd5vNVxos0DCmIZpTd492wRufFd3GhbY6wdA3qdkTDcY51PhhyrD4lHDAu+8aj/DFwrvOcRu/H5bkPJgNJjpE8l0dRshcXcows1oT/fjKdcwM9Kr18X1iPD/18ObQdE84MQvikSt6Xa2fIsivn7oxqrCLqAREAvqFY9vXO3ETSFu3TO1DNVF8xmJLnwTaNL6HpBMRMuAwuvAI4IdSGcYpd1GOssOHJqg0AJeb/kXrIC9c6DG8mye2f6NojSDz/BEy9Jnxu63+B
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
