env: staging
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: rikatest1-database-service
      - name: REDIS
        value: rikatest1-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
routes:
  - host: rikatest1-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgBRqgd8gC6PaCjBxw7qdQ3HQifJeXErermmN+PAaOCDlwcEd9bf2d5Yl002FXdpKzvwGrzEae0Amy9mNZKa96w02ggjCTNlr3gi86+wU4cA6Usw03RkR8MnGg2xWA/Vq2LQahuGm/9l4jGZDdG1dO3Nx1dJKTBEevfgYqrRx16VFB0F1yNGTi3s3kjzeDuvFqIYcAglg5TFzDLKkBXbpJjOwLF8U44jD0wWtzS6qJj/7ADnTzsjzpQ3g2X9qOIGxX8IjVuEocjK/x108XB5TqXn5l3AtFIPvoYlMq1A0T6KwayQAqtdAjgS2KONBgLQo1RLida3OTwgjUv6DrRmbbt50qcyurnZepGvJtOsju4Hly7k+Wf3GDi7MOAuX2+xtsXZxkYP9+RPqbzApc2NT5XyjVf0w+ucRkF/F8tLUWmIYywet1mvouhSzuvUtxmcryUL6XiosycUfIPuWoK18DvLVOsstu8FXQn5aYr0MHiyBfjsxdVA944lElz/xZnljPH5aqqJQVBayt/gNjrmDIJNf3t+lKgt2KsPqHOgMtexP3xGeYBbeNQdS1AjV1mlqfitiZ7eMrNOzJIQygy4NjdwQQyXGHal3vlKpZ3JrqAZPuujVtNhnRMLom80MLW6T5KiAbZ+1XYUmzWx541X20OgDMNDFacHX1gCDTRTFWyKPW1ACY0Ma/hshNXqrWcEqff035kqrEPwndy8vGrjpeio
      POSTGRES_PASSWORD: AgCwd7x5gITVeekVEEIQK8bZl6jE2NqyOmHxZxlqgFDFOQN1JP3chAmEY9rMlGhNRC/hbfd2LU5GblW+H9xeUyF88+0MJfRqK7bOXkOQpV1NU9XpwJ/Jo+Xpz9JEbJiUVVAflPOfUf97wyPNUyd/VFNrdLF2qQ/dpYLc9hn25bIptjbyy8ZNtR4snVSnLFHqV/ilzau65/3FH2dVskrLU2enwgWylqZxzwu5GRtWTEFdIvkAVKBpOHt2m+UfzkSULDatm+Bx4t1PS0XsgqnDkwDlxcMY93anoz+jEKuH1iO7oQ5VvFlkFdK7WN2eOVJUy402XjqPhn05xgmDic9L33N8xWBKvmP6F1SgZzvr8Ub8Ufy1dM+lXGVss15o3esgoAqbUtJe62VaTVf2HNosqVfMbUzHwyVg/cZm9myMV4Tq+96lqp+OOCiB6/uZst/eYmIKzb5eKiSvAusa8L5+mMffsRFr79XBFn6NhdjRlgJp+DCvpdUKTxtdnLV7WbdulTjZgd6ZVJp4vx12700A/fH3Y+FNMkILkKmvsoE2+hcM1LvYghuKsPt0IcWYUuMzdL7FFXjb4XyZrWzbW1qS0rcuVgWJpOJePhtNxv8dG6iZPtzmxD66QD6/nkSKPfekz3NhHNXTfHDDO8D0pHz5RnYeztZM9/Sdl9MOcTW5GRTkPFlPCjDu3B6S5/wilzCY5T4u7uCrmJuqzYMHq9RWxRwW
      POSTGRES_USER: AgCC9vGGNQAUd5TH7dRikAo4TUUGQ8pY2xpjefWbRihQFz8O0Eb0hJE1gI8g1g0cwLiOKdJe+/3wX8q4onbx4jRFWYgeagjiS4ZZHw8RwSXdqvKOVv/YS+CyfjWAv4b9sfsSAONYjL1fKmbaI3q30NfYg1QBGbqDlWo+trVHyXpkHcpv5vL5o1+Mtl4NJW4gf9u16LC+FdVBDEqch+GJfGaM08uHikf2PQzhWdQjJnPPPdIoa9U7OTdBEYLtO7EJtEvtYHUSLCTNoNWOMRvevweYxn5l/KxlhOlVZy/zFtcDrcRsYgw17RYJsEjDBQr2HP4So9dwa9Fwb7dAlCiaBgawhaDFNPq2lj8pS3G8kPEB+1wp/4WiMkd1X4suU8q8W5eEEdGRoRQt+ixd1+0w2Ps1x/k7Yp0zbt+5OhYgPZA/TRiT9K/zXYMuoCQEV9cJ3SuKIJaTb9/suhh+VDMM5ZEcI/zrf9PAdDF7a1y0o0Y+D90m/+Z3Y05K0q5pbzvyQHuVTYrwCwGwajFjFNMAFGkEylQreJ9m+qef0Tz2EYJygpBVI81srMqq0sPnLQivUERS5LcwQWAeI2SUCn4QI2LSiGjQWL2Mqv5EyMLp+OpS2qEdlbhXCbiKEUFUOyNZrEByJZptOyxkr3xVUHoi3WlBonPMNMo+L5+MbL+Oo+uUrNUs3lZ79iSiJYUgK1fWYibIWs1gzYGRlwrra3EySSGI
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
