apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nyanify-secrets
spec:
  encryptedData:
{{ toYaml .Values.sealedSecrets.encryptedData | indent 4 }}
  template:
    metadata:
      name: nyanify-secrets
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
spec:
  encryptedData:
{{ toYaml .Values.sealedSecrets.encryptedToken | indent 4 }}
  template:
    metadata:
      name: ghcr-creds
    type: kubernetes.io/dockerconfigjson