apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.env }}-service-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: nyanify-server.{{ .Values.name }}-{{ .Values.env }}
---
apiVersion: v1
kind: Service
metadata:
  name: nyanify-server
spec:
  selector:
    app: nyanify-server
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyanify-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyanify-server
  template:
    metadata:
      labels:
        app: nyanify-server
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: nyanify-server
          image: {{ .Values.images.server }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: nyanify-secrets
