apiVersion: v1
kind: Service
metadata:
  name: portfolio-server
spec:
  selector:
    app: portfolio-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-server
  template:
    metadata:
      labels:
        app: portfolio-server
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: portfolio-server
          image: {{ .Values.images.server }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
