apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 84.5.0
    chart: kube-prometheus-stack
    helm:
      values: |
        namespaceOverride: monitoring

        prometheus:
          prometheusSpec:
            persistentVolumeClaimRetentionPolicy:
              whenDeleted: Retain
              whenScaled: Retain
            retention: 7d
            retentionSize: 20GiB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi

        alertmanager:
          alertmanagerSpec:
            persistentVolumeClaimRetentionPolicy:
              whenDeleted: Retain
              whenScaled: Retain
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi

        grafana:
          admin:
            existingSecret: grafana-secrets
            userKey: admin-user
            passwordKey: admin-password
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - grafana.zagoapps.com
            tls:
              - hosts:
                  - grafana.zagoapps.com
                secretName: grafana-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: traefik
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.zagoapps.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
