env: prod
deployments:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: rikatest-database-service
      - name: REDIS
        value: rikatest-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: rikatest.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgDD7J+/6cEP/TVbWjcvwrA4AxafBn3myeooRQBBbrBbwyJcX8ySqdVDZHuVCngtU1uLcef8Dv8zLt1eVZ+0nsQuTPeDWoAe0z5glgm5imrJIZUNCpWYkfoFkT8xDN17BNqOENA0HmbvDHQPs8nlGUFgqN2bIxXVGGBV+XW4CBQu2D6zItQh5BCgg8n58pspqAJZp+JW+LVLiuczSK8ByM8HW51nC2Jp0x89ldQsCc2O5L3pKzG57MLot2BSz/L0gBnRnaf45E/zCnt+bUUK+n+r/tpPRxEH/uDQSSgGz/b3N/E7syRuhPNiZFKM63fqdsSum99HGvMP7wzvea+SDLhXFnqyEVeXONb4Jary3hDDsh7lxhXQmr2kgzhtY0HUxyElmkIeJz0pSNmcG4/3s0D4932FwrKfXfKck3RNfBspDncqTMjl/YCfcx+dxPYceI9afx/XVcG1pJmG7ClNqgAW+If3+WTPEWQfcmYrlBvaesEknHY+4PjHA97ZRJ9aIRw0/G1JqozsVL4cWhhU7COt1iIp2FKzlQMNA83ojIN6tVVONNpJoO84zBEScz4lDVncPqrna0mSz5xQ9SmBS46FmFjErqJ91WjHzxDTgVi4IDoYUBIohBdw807TyWH4E8OLaenFhZlEzfg8wr2K9ZyRsOiuIsFd8z/V6EqJDnITqw7czKOW5/STdJRV+wMdD/ttRU66BZJAsfsaYrclod/e
      POSTGRES_PASSWORD: AgBxK4YeP7uTIsSLX4Sob5mQ9p9oteN08LKagNP9jPRSnhQ2lF+Sm0e+VlEvVoKyGYtuQptuJgmynl6wArt+Dy2m23nVYP6PzSQ19MkaeSNlv6OaTCjg5fvmW74cq2S7W3vyY4vuQP15Krmf8GSXEc7pHWn5PGKSryTPn7thMxG7lxQW5xe+01nRu7JdMB53dulwfSNz+hihLlfDJuPCO6QWUhxhhRC7CUmnz5fzkuETtF8xuC4ilyg2ixmx9x8lQAXHHJ+0rGGaVxkgG2JxQPM38C02sV3C/aIlJczIA4ETw2XthzEx0vFsHTJTvm9l/5oRafUtRulQ3fU4yMGXmhG8HzXTIiNuRpwEFPDdvXOoyIdaXHik5xBoFcKLo3cReiOd3mqA3/3RHIfJGwSY0T1oBJlNjHqPhJ6o+bdUG17Es+5lPdpKJ8rlcuM26s8zA4LIzYOXxZoalY7tyoyRcJqdJvEVL3QPcrmURJlAYXqReNOYwgK7tNVAOizW+jB/eCV+mVH04kLXeypus8TjmPBHvTSO5TEPTeZpBS8eQahvJ2oh7f9Ke49nWvTRlmhBctK0DVdH8fDSL3S6gT1TngDE/qk4/egtkTqY4uOFqP15mzeEnoDPmWDaoTHRwt+/avPgEvyCdtf8AipRXqjJuo6ZT2BfqXfEiKZCYYdykyALbjLdtQN+E/hIgYRcdI80Y2zo3kd7CDXlc81lq7nYfCqw
      POSTGRES_USER: AgCU76sRWZi6TqsebCc1tKRzYXght5+Hr2iH+65ms4aQPKbulQMm2Yba9y3vSpBCjJ1nCiZvqn1Fk3nzT0COIOFJ2nnmhBAeMcmujF3KtR9uQRGYzLJePRx+xdv7tcB5rdWBzRBsZnbqn7WH9ZVvdGQQAYL7lN3dL/+yozEA6TlDac7FtxZjada+OJwhGvRdNJejkpZoFP4Rr5Y/mtRO5+2cPksd5cVnoM2vIgVYwUY34PUEUdxYgtCI+eFgbupBS+hq15dEriTZ30kM48DQLqjKhn8Ll9ottICYCLM9oil7fXyB+3w9SI00K8oEZ+fn+cY+f7ZdDIVl2xo8Mp1ACQV6pkK0rn0AtgyxIDYq5gWgWF3lVH4jCfPwjE88Nx+wbhuXaCGtZzhzKs/2gJWluater8+bs4xnLISZNczKU53oAqw2D9c+4kfwnKQJX3L5wdOpihJiFNuWEbWteo2S4j9p4IYReK72D0tmzaHDtOnuZKWA9ohM0AllmNKoUkrBfhawu3dt0qcIbihGEVxi1OxJZ4cZPfcMYGsLvGZswfDBmu2qJiJX8HhXpwbStezusgGnRidGoPwQv7oX4d1aCZPjgas5vPKTyifIfPEhZ00BzeleVAq7YYzziCpaTBGiOpFt4bowIRaOUMPjlou6cnNxR7Q4SrcLDxJojv2GyJUvzRBXkxzM8R6U8hbza/t1LTZIBZJKeYtPaGxHtnKw9Ty9
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
