env: staging
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: rikatest-database-service
      - name: REDIS
        value: rikatest-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
routes:
  - host: rikatest-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgCXDHn83sBtaZ/ks4eTHO1dQfep/ARzkeorzIHBH1pIaNMFs6dAxeAqAldDZbzH0CD7WIgbELNNIrdwpv3i3dxKJ+FdTMy/rH7SgVZx/gAd7Ew/mdF2eSRK+0b08PQb2kv05HxqkIOTxheqjqUf80WaRStww+SATmjliHeRcGTeHvoO96MhLKmnG2sF1/5oXvZuchw4sebVzcsU79kXMfwUWSpQ6gv6dHbOFQGeyQ4G+2sS0EpihgAoy1tncdmnXBBcLdBwdXNjJdoodQz33qicYmVgwG56CzEQxHsRRNBpovEB3PVkiiOtqhe1FD4NozOKt2VbAOxDHIGpwVFOjCE2PmAR5EO1kDzgn1+LNGj5j6432yJO7VlLfEwsGGy8fNOdf1SPDA5GXZTk3ZOZSrxXjNxewgFOU5kWQV9Z8V/lPfj8lO9PgQMiFkt8ywddPMhi9gcB6Xafb1TuXF4R3Hixojg3XsEQ/vlyyGvtizynhJA0WRciBJeFXvEk7414VUXpa5JRc61yHiBZ00qVfyocxxlt6l2Elbl0KrCcd2UMmsSKzKH2dZeJ1EWrbwEq0eMfz2Fj47EQgJnPJp7i8HByZFuUg+MHvCmLE4/azd0yRmZc4eQP/78McrPzXsPCR511OOfIFNff0Vjx4dgK+4/O6uR6pND3E42fwWL2U5V+Bs7NffyDn86IjgfAndiX/EN3rnv57NzEZTLUzp2vGGUu
      POSTGRES_PASSWORD: AgBJU9Zqe/NQouaCFaUUM922ibM/5eIONoLMMOTs1+DuoT2Oe3clnK5SRxNc11WxGQDbUAFayUTiRRbxAT/Kps4olnrt/VtfoPfh7IR0aF4SZSWU40jF67KaSFRkfkwZh3n7qf3tgaVuMjTIYw4yRckiqNhkiK8QxjwuLNZyRBGDzlf3rtQZKpAxjlsH7D/r+u8Mf36nzRpQy2YXORU6stQn35P8iKfLljaQxrkH5yQik38iReNBbCmuuGLuht8hf4GggMtK/okW+LjsoytmrKwvjewpE0xzzWeFMQR8t+sEBHhuEprpgq0OkpBoBXyjMy4dJReIT7yKecD4XiWaBlhBOB0OFcYDs4xU2NqfGPZSKRnY/KvMlWj2QiI/Suho4qzn/YWfLPqWEz8eP/0UTVwR46VAyEodLysIotx9JS1myGk++i6VyF6D53x1s4RRbMnHC6KU6WfQyYj2a2vANSX16Tl4J7ACXkqauOi79lw62Xiy/amzKN9N+xIwC+NCIBHHGd91pI8LJTwOa7HtG30AXuNlaetdO4GwLkd2yEuLFhsCyekXjwDzPt5+wCAnxaJO6ZOdM6p6r9Aed5nSe6DZipGyPKlE0acehXqMgQYPm+rfcOxGw3ty5PiHYQnPuwoZtmdb67OyKvPAbl+1M0tnGZ2YLkuWtfFTaSpDDv4P07xrQAnNsaBOe+GtQm1n/Pd8O100hcIbBwxVTqpytGaG
      POSTGRES_USER: AgDpVa74Kf75+77pKVnNrHOcLJZscCv63lQ0lbNPltLhECi7YWY1H159FWnO4uP1XZTFwoSTnegJnXe3VxaHtMjJvDBRAT/CX95VUwZVgo45ydYckA0sBSttKwexlwayq4xK8ussD0uU0SrnBSjjAArkR89Iuaec5x6a7cAzvyxf+xJTjKfHlfSIwkDHUjPdNjTkgbmAgBzfbsxLMroo5PpNQkEgJ3Y7NGi/y2h1gYqCS9iQxIUJhXeGJANsd5FUhIybCwE8Wfde/PiCeBZHC/rooIVB/GbgMADmz4XgOcA3Ip9K7zb7QJskM+5qWBRKfXOUTr5Ugy8tBr6UjPB91NmBBONGVOskpb7F0R6zA3PapAskhkJpWKmV0iEG0yDMJvS0Gx19M5HKU1zQyAMkeumLeLnYWSdCKPSEiYiPXyMMgTpau3MXPUhj1qRcDAG64EB2oTp8MI6GQ+QjFKgy+f2b4HxFrVrTF6rv0THNB7mbQrlG+ULeCw7p5k0XWNRihh70yfBaZvJkT+xWiTBDtphMIhcyaXrnEM0NjSnmPGZOGCb6CBNhtPvVg67YYzEx1O65yKlcOg9SPuwg6gYvnM8pZCB3IBKDWRNavoHksBpGqAJJ3qFGLqy5Kye0897mjxIPE7IcRJl213a0NHn+P9QSWLxBWDxIsadUfd6xcOLAfOgu43TPjd3Tk4sBrIy0G4Ezl90ywdKqQ44NgjFXLUdn
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
