env: "staging"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: nyanify-staging.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 8000

secrets:
  - name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
    data:
      HMAC_KEY: AgBEnm9RveBGBDvcrDTb3W0rBfVMdyoK35ibVP7LhlTvop5PNlR3uhWMUQXd4hHUqZ7rQvCVXyPvo2wdanZXpQyt3oiFAlgkS2SUCXH57HkrFNA9CaImWbX0wod7kJk1md3uGaNCOxnYolKsd00EBdFwurA5uBDVnZjDkSHC1fSe+l8aLP48HP6ka0p3jLMcmgaNzuwZaO4/5ypgYTxdPmaBuDZcwLrzXAIoG4yZLQ1RJpNMEjVVu4F4FNDNSlemG+N4ln4tONh0Kjf7XFYySpKdS/cMwZy7t4TwVIQ0c2fyVRB8tMeWbR3GtcD2XBIGGIw+vm0SyLqdmpziU0DImoXuqOSUOOhia2nsqC6OUEnV+EUYvLazx9N3JR8z7HNLXymwPyNQzPZfUhA0krTWOlPK8OurvcBe2uFBbOG4o9mKjjmPoECwoQFqm0Qo3U1M12Ensu014IYaT1XjGbhoTm+eN+KbO5IrciAx0lSAkR3uMxkRvuOYzbXwpICx5zTspwSS43cziptTuwDaERLrc+YICV9MVjziire3gZOv+gUvC+wsbd0a+NUBVYJ8FrXW8geeHiNQF5HWw1wuU0YjAU5H7PEiN15G2jDkuKvP2WgrqeKj/ySY0b9ywXsC3DC3u1dIKZPQqPl8nhH98oLcluYW3vpuC9AabGidh3SzqATOolj9k0FuoFd3o0fqEjgv3KrMG/P2bmMvluDsMsS1FDn+BCO4u+q2bavv+2r8q4ws+b9qdXcWJrr6KNLH2WTKj7wOD3hh37S9A/sw8Cr6ToYd
      TOKEN: AgCiCaJ88PLeuLqa8xSyPsYhnh6veXDeQGia/jMdNprX5/BD4LAxpqLKeS9kTzYfDYknT7JF6ezIQT1XUAP6rrMa2MFcn2XDiuxD2rYDY1i5JWLBByk9RUtX+dpNwJ5LpK6cRxh75b8svE7lgSfxcjXCj5qh5EIluJrbHDXKFxPU0oZycIrlzaoQo/51gy2cLtE7sqTDEzFjwQJYA8Tk50qzYJNfFe51I0wsX4eDhnW6iQs5ZTh92fIcNaa4bYoVcC5Me0U4jRipIP1YVHcr1WfPUyyCusGcIjSKOLcNTaVwFtFDVgM+Zlcr+r6s4O4JZZIrUyL+42U9GG2sRUmJXqoI2AOfPb6GfRSL/d1/s7xCWnzyvakSV0wnnHxQcqJqJ502EQpWkxlWUY05iws84MEUJIrU6I9+jOSoln0vUz3Q1xfe42OHelF2cGl4xEJJX6fT/Lz2fEhMVYkHgPKpLwXmBn75g61LNkG7vaG0seOeI0dhP9/3Dl7AwKB8yefqNr4q4VH2PxY0yLFNorumfXXv0LgahoUv0pZcEK6U0SOLzgra7c7IWAldWc8/hzLXxxsrHL7Ae6/zcyvc2Y6FuFTERjEO77NqU3krbj0mlyzA/Au9UumF8109XE3Xl43NzRc3/+uSCKTi0WNLrHlsrTA3MR8fWu/n5DjYaHTwkeWFirXgbIztdTs1owW0R7wGfrGaWpOE8yPgzAJqytUgXS9ML5eEa7rGGd3e0Jtnm+A/1Z7tL3Q4mzAwAJfIrFXUr+J3ht8HZtMeDE/2+u+5kIK7uJi2p4FxntU=

deployments:
  - name: web-server
    image: ghcr.io/b-zago/nyanify/server:latest
    imagePullSecret: ghcr-creds
    runsOn: python
    component: server
    containerPort: 8000
    envSecretRefs:
      - web-server-envs
