env: "prod"

routes:
  - name: web-server-route
    runsOn: web-server-service
    host: nyanify.zagoapps.com

services:
  - name: web-server-service
    runsOn: web-server
    port: 80
    targetPort: 8000

secrets:
  - name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
    data:
      HMAC_KEY: AgCJX+lQFLqJpe6oQh7C7VrjaY0PUKClo8Pcl2afNYcenD1c4eugkX0wiZfLas0VygIXeWlF1R8RB2bLTK4qL8MLuu3PwLUlUwgpMK+8aKg2xdQ+1+/3U0PjAg/O/DUO4G6ItukUCH7S8Q+4IpuCdTRtY55yhqnNwcMsfTV3HDvqRMleD6Z4ocY6TI/gjpxIASycCwe0JMegxj0eNFsBuHnHrx5w3enF3GZxnMajx3hbOcq0lo4RNwzT/eOd5xapNjlQEmEDgSpDl3KPaqSVmi9Oz1rfA/pU+uzl3qxMKI3Fh5O6LyhzwoH1kwBR0utO5bZMJ35Tmd/8vij8mwKmfohN3xx3SQDNTLtSZrUXbzwXyU3wXQ/9fsSWFxSICNIMbLs0vIYD4LtLfMUxp3MZ2qa1T4hcQgwr2qDlfOyoaFaOyxriKVFAEV+adkBHGVYXKccbf4gJZ+y+2kXDms2aEjZWGQH8nra3Z92w9r7L/MHu98g5zGhui/wycKI26PGtZviB6Rb/RWp5uk6SyYau/M3Tlz1TZ+gxsSHT/Lz2Tmr3B0Rp3OMoBX60Pp25JIq6mj9+WYr7T63qWM7CohtAEfMoVQ/fIpCb+wlCfFwFsnjV9xhlI9SeVKT/bxBjcykfwm8o3HHCAY4vjnGo2lweM1saxt6z5OhBjcSYSjHJgQHZcV1ZWzR7vojlITyiK0iESfFAZvR1LADSdNI4LyfMeEfMzikGq2woOlrrkyWMDUuVGbJCPZtb0bU6NAUAO9tK4mm5yqILeBLGNB6ZUGeEBAwW
      TOKEN: AgBHv5IP/zejw6tJObNA71T0LcdCsTjfkv5iAAd3ZBRbNgwT1M3HUQl21DTF0MMzhYwtt1UptFsNkIvxqQKi2Lia4Kv//zy1AKn3WxQmSbqGsLo3AL2fY8H0mOPe5ssKj2/ljq+a7AovsnpmZzgUueA73LzELATvS7wKn9+PklItJFv6O5+WErd5Q8Gi/SY/gNQK0KdteDUk4FKKHKZy/FWNBDwuX2YrIgDKrS3UHBiWIhKJsIrLktV/VPgxN8VcVRCaI6uFw6T35bgQQr1GXdBp32OWg/i9oz1sA5sYlbZoDHZGRAhjtOSKYW9H7qMQk3/mh0x4ODAhxS7oSuLWnyp8K+/hapZk702yNiPHye9R/GaX+ZXgxMJqJKbh5MljLH31BthvG2p/SI2N0U2XARpgguck/E2hux/USdhmYxPw5vo55KgWEhHyspRzSd6hkTz/l+qL1ppmOT4HMLfyUBOyCZEG6maNtS54LdvfU3S+UGYuHCtYuWHEg8L5MCzKg6XwutLUCZAI/1GTgVN+sF49Az/TcKm7bhNjREcjspmEFbi4ElZ5bvYXQUxiGJH4mbXwsxMadX/D/NaxAX1fqIoEcBNzTd1iuscxZvlOrvqd/DEsdjBueEVpRFYugKMBYCIhWVsFueDbovitq281TKwbzjOWirYYP1wFB+vm9BwqQ8fS8u3iPsNYYLWeczlC4o2mg6VSxwYuHwa80HhjLNCtcV6Pnom7YndcYeYwoZCG9aAkrnY1F8CcC95GSnwHZpfhFHE2YwVbbPaP1ohegsxyxJliH226nWQ=

deployments:
  - name: web-server
    image: ghcr.io/b-zago/nyanify/server:latest
    imagePullSecret: ghcr-creds
    runsOn: python
    component: server
    containerPort: 8000
    envSecretRefs:
      - web-server-envs
