apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: v39.0.9
    helm:
      values: |
        api:
          dashboard: false
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          listeners:
            - name: websecure
              hostname: "*.zagoapps.com"
              port: 8443
              protocol: HTTPS
              certificateRefs:
                - name: zagoapps-com-tls
            - name: websecure-apex
              hostname: "zagoapps.com"
              port: 8443
              protocol: HTTPS
              certificateRefs:
                - name: zagoapps-com-apex-tls
        metrics:
          prometheus:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
