apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-staging
  namespace: argocd
  labels:
    part-of: staging-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/b-zago/k3s-cluster
              revision: HEAD
              files:
                - path: cluster/workloads/staging/paths.yaml
          - list:
              elementsYaml: "{{ .key.staging | toJson }}"
  template:
    metadata:
      name: "{{.appName}}"
      namespace: argocd
      labels:
        appset: workloads-staging
        part-of: staging-app
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/k3s-cluster
        targetRevision: HEAD
        path: "{{.chartPath}}"
        helm:
          valueFiles:
            - values.yaml
            - values-staging.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
