{{- $volumes := list 
  (dict "name" "pv-claim" "path" "instance" "type" "wp-local"    "size" "20Gi")
  (dict "name" "db-pv-claim" "path" "db" "type" "wp-db-local" "size" "2Gi")
-}}

{{- range $volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    type: {{ .type }}-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}