apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sftp-config
data:
  sftp.json: |
    {
    "Global": {
      "Chroot": {
        "Directory": "%h",
        "StartPath": "wordpress"
      },
      "Directories": ["wordpress"]
    },
    "Users": [
      {
        "Username": "{{ .Values.sftpUser }}",
        "Password": "{{ .Values.sftpPassword }}",
        "UID": 33,
        "GID": 33
      }
    ]
    }
