apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sftp-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-sftp
  ports:
    - port: 22
      targetPort: 22
      nodePort: {{ .Values.sftpPort }}  # 30022, 30023, 30024...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sftp-deployment
  labels:
    app: {{ .Release.Name }}-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sftp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sftp
    spec:
      volumes:
        - name: {{ .Release.Name }}-sftp-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pv-claim
        - name: {{ .Release.Name }}-sftp-config
          configMap:
            name: {{ .Release.Name }}-sftp-config
      containers:
        - name: {{ .Release.Name }}-sftp
          image: emberstack/sftp:build-5.1.72
          ports:
            - containerPort: 22
          volumeMounts:
            - name: {{ .Release.Name }}-sftp-storage
              mountPath: /home/{{ .Values.sftpUser }}/wordpress
            - name: {{ .Release.Name }}-sftp-config
              mountPath: /app/config/sftp.json
              subPath: sftp.json
