apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cli
  labels:
    app: {{ .Release.Name }}-cli
spec:
  template:
    spec:
      volumes:
        - name: {{ .Release.Name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pv-claim
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv {{ .Release.Name }}-db-service 3306; do echo waiting for db; sleep 2; done;"]
      containers:
        - name: {{ .Release.Name }}-cli
          image: wordpress:cli-php8.4
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-db-service
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: {{ .Values.dbUser }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.dbPassword }}
          volumeMounts:
            - mountPath: "/var/www/html"
              name: {{ .Release.Name }}-pv-storage
          command: ["/bin/sh", "-c"]
          args:
            - |
              wp core install --url={{ .Values.url }} --title={{ .Values.title }} --admin_user={{ .Values.wpUser }} --admin_password={{ .Values.wpPassword }} --admin_email={{ .Values.wpMail }}
              wp plugin install all-in-one-wp-migration --activate

              if ! grep -q "upload_max_filesize" /var/www/html/.htaccess; then
                printf "\nphp_value upload_max_filesize 2G\nphp_value post_max_size 2G\nphp_value memory_limit 2G\nphp_value max_execution_time 300\nphp_value max_input_time 300\n" >> /var/www/html/.htaccess
              fi

              if ! grep -q "upload_max_filesize" /var/www/html/wp-config.php; then
                printf "\n@ini_set( 'upload_max_filesize' , '2G' );\n@ini_set( 'post_max_size', '2G');\n@ini_set( 'memory_limit', '2G' );\n@ini_set( 'max_execution_time', '0' );\n@ini_set( 'max_input_time', '0' );\n" >> /var/www/html/wp-config.php
              fi
      restartPolicy: OnFailure
  backoffLimit: 5