apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-instance
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-instance
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-instance
    spec:
      volumes:
        - name: {{ .Release.Name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pv-claim
      containers:
        - name: {{ .Release.Name }}-instance
          image: wordpress:php8.4-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-db-service
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: {{ .Values.dbUser }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.dbPassword }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: {{ .Release.Name }}-pv-storage