apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/b-zago/k3d-infra
        revision: HEAD
        directories:
          - path: apps/workloads/*/
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/k3d-infra
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
