apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: prod
                - env: stage
          - git:
              repoURL: https://github.com/b-zago/k3d-infra
              revision: HEAD
              directories:
                - path: apps/workloads/*
  template:
    metadata:
      name: "{{.path.basename}}-{{.env}}"
      namespace: argocd
      labels:
        appset: workloads
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/k3d-infra
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - values-{{.env}}.yml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}-{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
