{{- if not .Values.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-pv-volume
  labels:
    type: {{ .Release.Namespace }}-local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
{{- end }}