apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
  namespace: prod
spec:
  managed:
    roles:
      - name: rikami
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: rikami-pg-role
  instances: 1
  storage:
    size: 10Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
  namespace: staging
spec:
  managed:
    roles:
      - name: rikami
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: rikami-pg-role
  instances: 1
  storage:
    size: 10Gi
