apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgBIEndFw27yK2FJDO4PbG47vAzEurEM1+LE5mgtLXTDYXiOgFvMdLTJ8y1twbG7xodvFmySZtOrT6OqR9mgGyY1dHhGVbG0/2lJtF4XmoVFPILCtpd8voFFXdvfH8SBV/PROtzRcZD1Iq/nxqpdeHDWu6KGC7ZSfPlDiIbpj5HtzIgNqVI4uJz/S7a3MqWy57jP84jR0qitw5XjmAux3kiG8qi3Gl0iTm64JBYLGmcRMJtj3SBwp2Y+MVrFxOHdhB8DJlYjh9Zwfq/ZNyefxtR/q14R8jDjOD/SUteK9ZW5+54MrIKn2BBN7N/PUK39bhwaNFktsho36hKLXsKU4dASZGSE+hjb29eUw1iS9q47XKDrcHb7O2087cG+ectoWdP6FJQ4Ao4VeIhZkn8l8gS/JmRTTty3xye9zAR1shcypUjra8X9f6tP20EbtY0MAtK4O1Gpagod8f27R08soyuG4/kwg/On4R7gM0MfxxUC+LTSy3u8v562/hvjgDIkOn2RoLihjPZDxedkkxIoQePCvxGatiLNnigvSP58zs7Vft9+NN8YO/U/QpXBpo9BowCGGdXHQZ+4ixiPo3suuTlEXy01H/4BZAgqUjE4t0mtQ+seSOgvJ9m3KEtZNR8GZpXQ1dXc/LVyPddIz9fIvm/mSisS7vPK8SZ1h2d9xi0C13JqnKKgxbTcJ2BOuWQoUc4NXsoaHvO0g+ig8v1CHd4fz2EBdc+dTE85LWYnPZZIetxTcLr8dmrF6Z+0uwz2zSwMGft8WATjO+AdMGfy6xil+mfL28yEDvC3LbNz+iEzIirzrnT4Y57PnoDO9VysYGjgWXnc5zLM4tWQtRD8XGuUgVpV7fhWDGRsAm7rzz0t9vOQcOfZW2FDdTipX6P2XKhgBFeOQjGznKz0Zs8r6rbe1TAjgucBqqomlB4=
  template:
    metadata:
      name: ghcr-creds
      namespace: prod
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBEm7gYmBWkXMzxOxXqwSwdkwO6lOGlHfx3fH7fDuiYs5cO+rtKiEfG6q3hkKDkcDnXeWJA8SMyGhMv0q+gkzUFyfy2eScSWXEOQUVQGqbBMVSHdaL6ZnRr9OzPh4RWbA4HztNqNjUGXGbU0vE3gZNca/pqZ5vuWq12meJXiyIh0w7sAAE+xt04yj6o1Hx0THowmp77scMmMNTW2qBBHQMJtLdijRvyR6tWlXuu0f0FSMUijVs22xHr50WNvojzqDXDRewEdyyBgfchEF8M1i7QEae+IHEi09UZVL7a9Cmb86e9DJUd/cQjytE9/O9yMyCObhI8yVE8yvwgHvt15onKUNp5hZewx8rXXywcWPkOotNUyl6JM6ompEZ2rWUbdvW1jIohMbxQTqlSaN0vZcTCM55wLAiVLIgcPw8vb89fGd0UIFt2KPl3sDlVFcbnIZxOc5b550oBcANw30W9lZG4vWqjH5V7vPxblrG9fPfVk3fGv1/akP2A8N8SNyQsuA8o8fEgF96UTmhDaPMJovX8U2IWQSIzF5kQTxcuWdsd1Mm0ehGPpQepnc3kha6Srg03LTzhBMzMiHpUFbUBNz/+YR4Ic15h6DJBqxw6Z21VQ4XBBFtzQzZL9X6npyvyS6clYyyu+DdwwghbXJSgclt+hAE8m/ed9Jx1XNBYgeVxqTNb6DqtsK7hINzYkKiFlAYSWtDOKENtzVCz7HhpvbYQMYTjM/aFjgOdnGl8ct6PL54DMUIM+gu7Iq80hIbWCduK+ZCCJS+YRy8mjbtmPhQ4qGgIR1IAfSde/ZMs6eAFXf9vhU+5saOjGsJtuyxKj/BaSQDp/NKtheDzGUWvPUzkDUJ/aQs4YZvE8HwLhHZwx8l6ccKjdlg6JF6j0ApcSKvG6uP84PS3MjTxfS+c2N91gh0lsnwDgrKFMY8=
  template:
    metadata:
      name: ghcr-creds
      namespace: staging
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rikami-pg-role
  namespace: prod
spec:
  encryptedData:
    username: AgBxu+Z2yc4LxcbMf7Fh/zYzd6gc0QfM/ZcD3JzgIt9Wgb+8WjVxujuDpnQb28SeloEvpYptEPxPlAht3ZR7OWflnJ3Ue2tICDmR5nytvLkCFVQcBgJMgcVw4m9jnMRw7m/HIgK3vRqnOVHCR2PFqmbcweGxlCC8XBb7XO+rcKaf35O9YkZvUOTmgc6hTlgov4FZ1X3Xv0Dahs6qQAeeYu6XxGBKTYabdUp3sFF0eTI5tjeLaqzfCotStnWKcmEiRe0nXjPqj80s0nbC91X9SK/fz6rZxWrmpTqud8fyjx8HoBqSJ7ov80/BudbFl4d0xTRxyO76ThNgUQvrI5HfTru7MIjnhdu79YVpTwJ7F+tt0LVgODwVl6+Ehm6parqL3HyFgcsvP1y2Wo/J96GEwLrlw3COwXbj1g2QTfqq0orDqs5DJAbVOiphxiaXGCVQCoprmMuUOJ398pAa2itRXSxuxJGRo+VYODby5nzeM5VoHIt0lIKczlK86MUaFAyN9K388e1cyR3DyPU7xE61gXp00gBcbwHPHLRjYzLmwH8ty2lt4C+zchof9cJOn4Hzf3H+kDLaBoTphUbRR8mZ/1KbeppiAF8GSQuDttHy0L2it+W9R8Vb4UQSVRlMRTvZ8zAAwOkdzIyEAeeDZWG4oz7a7k9DdNoNkiQW5HcFZ8ZACtJFDeFtp2DYGJCIg+lAZR2KSbLElWs=
    password: AgBn+6XkkCUHCKfx2q2YtSeROFikn9k9GMNR/m3MjgchMhUwur/uXj7jM/IWqiitqDnNGvXx7UqF0Et4kyq3qhcdWTkManNW5uuVmwWBLMcSUD5ljMnPBO16wFrzQ0Xmfv2i28gReeVbhj0jE6wOeBzWAx/EfAeaTj6WX1lVGT1JtSfa02lvh1Lt4lksrnfOISPGUILMEGqwVTpGPcJ6CtMhimY3Q4cmKqVx/pjTeHnfiXQNO6pE0QFk1YpBn6Fqoze2S+0IhN9NBf1X41oRnbNk2coNZejhkIlqtAP+KuS3oJZgASSB3awl9R9xJW4s+3vcfL3TNlh//QsqHCr+eIZmejQrdkMsC0Jf38anV6i3DgV0/rz0ypKEfd/3pNdiR8VFWZmRKN3GAy0gyTeYc+/HrDbz2nn5kweO6kiGogMqa1BQ5WwasllJq+/DH5S3BPRAQUr9zyd2z2IgVwWEpUd+XQkdxbNqvXPypL2tKENPgQVKY4Zb6YWR4z4PWvSRu15MnVF37UYpUzVPwvyu2p6VnelLv9I/ESbqoHjosXIzJvHOVLZ/81l9ZvZd1Qcl/POGre//ga/U6PONZTzKQqxwgt6Ql0DtKsyMJxK9V3Wu8jgQ6YWrqIngscO5XIuyAacVpZeKPZ3q+PPOEoX1qCnqRKzW0wlOPsWbH8ACDNaIJSubwqassQBk8MjPa92RNG8BWpSXq0X5PncDMnNM4+7UiLAOQMRzsNHXFCcWVOxSI3wfLCjEJwQV9027Dg==
  template:
    metadata:
      name: ghcr-creds
      namespace: prod
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rikami-pg-role
  namespace: staging
spec:
  encryptedData:
    username: AgAa16LSfysVKqZAcro6n9Iqw0xtopSL1VQ0qY+BFTxXS/nu2hxerG/cZlhg8Bzs1/KFXE5HcS2Sitj0kYOp4wuW3MaaEsscLRPHUPhodK7Y33ctuPrE+5LtPv3k1ZNa8nOWmy7EzX17rRYRxFjTO6R1KFZF22LHpeEejY5ttYjkNX+X5CKJXeGfzpY2XVy2DUswbHAp4qH4G/dsDb9RhcVL/6vFs1abkMvWNiwGcpf5a3RO+ckk5OZ8xr+Z3P3dG3xhyje9a+sWactXtYyRwhJIBowdONvXT4gUbpLB/gPQ7hlXG8dociGoOS5dms8DH7yOhRGJcsHV6MW2ApFlWrRq2xAq9l78Fzx//A1xKTcIYRL8FXT7P8yimFm5qpjfRdt2tyk6EmSOxCxMu+SbeT6MLxk63WbWZCxXyT93inVs8jyrA/tfcybS85nwScC7V82wK1Ls15KYMwnX/P73iGtO9pRg67ycPFdpgtuOFJfDfiUaFgC9pSrPp9C3gVV1pQSs+m6UW4E5HYD/peGN0pwJvN49QIUR8uayb9WtRW2z6KLdj8uK/D40vmshvKSQPWywUcXlC8y1/QtsRt5FJkwDQ6KZNYJXMcDpGd3/iYyJ1xokzmcvO4kkPpqIlj3jCBpNXiTKBeeChWQYh63i/qgMGznElLEF5o6TpMpferLdW0LbWKefgPJv4JYVyJ4gcN1SsFM2JRE=
    password: AgB+G+LvMIrnCLr2K07vaLwK4ig92Z++bPHpO+E4Lvup5Xr/+Efa55JVsPXbWYtaXcuDFlQCksX/drasbEZ2lV00lcr4aKOVEZQL0VQtMWi/NZO6sSWkWmyFLJU23wMYIFRwmL6O9F3sIxCyf04BVmTkXzL4cFZ7GHAsjf66y/nsL1zH/Z/Zp7vOmz9CfCWNMfELDAoaxcOVVXVv9xVBs4fpP8K6sK/tGhd1l6KrQ3Xsvx+VZ1mv61952fLvEV+GKRJInTgPmSEUZwPocQXEW0N6yHacygj4gurRN68UVo6oZCjcmzMwD3vB07qZwABnpMjbf57mwUggc/JXL1XuhcY7v7jm9rj2c+Ibj3muwGfsV5ZcczfNSJ1aQM19vqQ4QvaUOCpioLbg+BKFw2W2TGBEbQrkszY00od8gHlJdnJrpLszchSrRD5Dx7ET+pQHRe+N3hpwZ3thc4xMGlsGN7if/ZV46gVCoMucOIF47inCfl+6j5j+EJgoCoZvNMYpe37RbupmwaMsmU/MLE4BFHh+yGHNVoVqj5x+2x8ckmJL1x6JP1LEHPvPTIGHVMSza1sNS/n/Bdh0/tk9HM/cBoR1O8L+9lGZvrTlNv4dbRalRcO9DBJjOChDSTo/0S9i5XvrCQgue1ChlPZ0lyF/p9VKVe07jYpe//UFxeauz105zhJ5Fvn2JqlcaiCTfNHkWrbj6q095aPBOHupwuTrBmh8Bocs1aKtI/mH8VkL7yM4WugckuKZNOfX2EwvqQ==
  template:
    metadata:
      name: ghcr-creds
      namespace: staging
