apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-wp-manager-{{ .Values.env }}
  namespace: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wp-provisioner-argocd-binding-{{ .Values.env }}
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: wp-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-wp-manager-{{ .Values.env }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wp-provisioner-namespace-manager-{{ .Values.env }}
subjects:
  - kind: ServiceAccount
    name: wp-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wp-provisioner-ingress-list-{{ .Values.env }}
subjects:
  - kind: ServiceAccount
    name: wp-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-list
