apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
  labels:
    part-of: workloads-root
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/b-zago/k3s-cluster
        revision: HEAD
        files:
          - path: charts/*/values-*.yaml
  template:
    metadata:
      name: "{{.path.basename}}-{{.env}}"
      namespace: argocd
      labels:
        appset: workloads
        part-of: workloads-root
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/k3s-cluster
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - "{{.path.filename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
