env: staging
atlasSchema:
  - name: database-schema
    runsOn: database-database
    schemaCMKey: schema.sql
    schemaCMName: database-config
    secretKey: url
    secretName: database-credentials
configMap:
  - name: database-config
    runsOn: database-schema
    schemas:
      schema.sql: |
        CREATE TABLE roles (
            role_id     SERIAL PRIMARY KEY,
            role_name   VARCHAR(50) NOT NULL,
            sleep       BOOLEAN NOT NULL,
            awake       BOOLEAN NOT NULL,
            regen       BOOLEAN NOT NULL,
            update      BOOLEAN NOT NULL,
            kill        BOOLEAN NOT NULL,
            summon      BOOLEAN NOT NULL,
            users       BOOLEAN NOT NULL
        );
        
        CREATE TABLE users (
            user_id     SERIAL PRIMARY KEY,
            role_id     INT NOT NULL REFERENCES roles(role_id),
            user_name   VARCHAR(50) NOT NULL UNIQUE,
            pass        VARCHAR(255) NOT NULL,
            hmac_token  VARCHAR(64) NOT NULL
        );
        
        INSERT INTO roles (role_name, sleep, awake, regen, update, kill, summon, users)
        VALUES
            ('admin', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
            ('moderator', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
            ('maintainer',TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE);
database:
  - cluster: database-cluster
    databaseReclaimPolicy: retain
    name: database-database
deployment:
  - component: server
    containerPort: 8080
    envSecretRefs:
      - rikami-api-web-server-envs
    image: ghcr.io/b-zago/rikami-api/webserver:latest
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: golang
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
route:
  - host: rikami-api-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data: 
      ADMIN_HMAC: AgB9RJ+pgoX9MWtsAsTOBLVZ60mrdUvfq1SX0/m/y6v/t+XTxFnKX9wsUtM6M9gebqNbV1OOAjCtJh4TYsra80qVmkxRKKvEzEev96hbboWEkmGIA6Tgi0FQhXpTPU/vIdToBeZv10dCp/fKUGIcwHTh2heshrdy2w7bQgCqiWr4m8J8jfEyPvPlq984njIBwUux6apqByIG0EFnl6Qcht7Yd874VIFNbkbEgtQkTmMZ0QovsjV2f0DjRkE4NNaAf3KpuRoGCTfAJeTp0HgIyWfkYQZ4jjGyhlFNFppJS9W8XuGPyt4qYxHbKYOT7n7E96Y5a+Oroe0vaw18fj9Ibu5+mXLH0vGO6LQnq8FKvp01l4gXukuHrkCfTQbGcFusYJINDJd5R87CRUnSfT6b0Yz8cRemHdSddcT+oQEQ6ebj2QPq7K28+r8aV5z/heV3eneRl+ZOAbPjoSVJhAyjgXsMxIYYgNYdxKlt4PABvwiNv3UHTcJPECGDHYfuMBea2nwfI8uUKOvTM2n7htiOdkhWXGbzhKxjkU+Ffut/uP4tt7r5odoayZA7GkForXFyIgSlkykxC43VlDHTJCog0YqdptkA5QvAJJIsluXr4slmKSGt706SskKddpGFJbbQJ6+uqCv67NMDnFuDyi3PpDFWfuVxIAmovxVUP9FbQh3B62qa6TSycNhZI+vM3IxvCgTR5iuJn22DCjo6BYCGbo7wLXnj7MlxZkDMWacqBneTGujSxhLNS1vfcoQmpg==
      ADMIN_PASSWORD: AgAa1k95pNkcs7704H0bPRulchzJ2HRLBBNhszZS+XJxqupIzFA5fi1kPHAmkIsD3e9gNyZLNhrd5eBRBDT0FV6P8cxHpcTKwDQ0Vtl78H09JQYKUHwoE8u6hIGr4pwkvNUAbXZmKmX6h1MQet2fORZ6yh9B0sXFEl8mBN2DFRF5JfJjKtaAqqv4GGZW2NP9d8TzXdLB2XJwWFxNudc5ivfsfT51AD9QkVnTXUqa5xGeS6e50A59CXkmqDJO291LX/qpCuSo5LoAc6TA8rLiCgWS53XaJzBHG3qa+TiKiw3gj5czxxIiuOOfo6zuMy6+0qob30CnH8ZufBESthXKuyDyr7vLkJBdUqVFAKOeYo46Fgo+/TR3B/TnjmrkUOehOEm9zMakG445SGQq3XRGjpRn6UN3J4qH4XJJTl7Lpa8latpgo+AjpqEGiTU8Qu3+GBCIa3cxAut17OqNKcDIi1vjgSjXz4UF1FuwSlLwwbwZ2lLIuVgX3wuQuktOFpbFtH221rAV59YdA8UdZd8z1RXFrpcfwAsTsTF0okcXLCqmQpx+beOczu5XqEXnoAuf2NQTjS9XTERIO9AmMHUzCo6fQ7WZhh5SsKGpYxPdC3B7yB400DNxGZ4I5SC7+SuJ+0N+iiSg+r5fJPIXkVqh4v/GzLR+Oys+A3X7XlrcZw1EUXtfUrHJqefiuyZlc93hbQ251xoDERD5
      ADMIN_USER: AgAIpTNUKQ3KNfHqOUOCbazjR9x3hYZdYiJZTAQaRzZNzcKr9ZWpX1oobtZAvuuvsve6B9tIqGaBu7NXIAbrE6OHL5N0rshbRcxEt43cJgO8I00oWABcXA3cDGCnna9oo7olKgWfqNmMkIazt8E4WIL5DQMH7G1tuF56/3f5XrfddkkMeln9rwkZmkiTrlpHwFdNAGuuUvJf2ElQU6/kD9G5qvA4L8v+eKJ/wmrQwebUcK6blRmoNAc80dnBaO/jRTv7ijkF3cL9rzOPrrVBE5FfSTEGy4Uvt1KPsmNmvJcre7pd3FxP5MIwAz1Y/t6nNoCaBYVcYJ7JOHQZwOYvxkkVa+MvaKz6T7cFCK/r6lU+/XL8PJ7njCKU7s4YczZgYzmSNctCpJ91vZ39QykksVoyoIZvZMCka/+Xpsrpa3dOhPbcMO4Jy4zU3DNTsjo53NzMsQths9VeIhXob7cxYBOlEjPYlkwY5IguuyZvX+4O++e95UpJcZFdHbKx/TN63oWLc527/+5K1XX/XhGIqEx5Rzx5h/h3819hC54Z6mq5CXHbOPoHBWa8BtSdDiDmwSazpPAujFUqligGhkWZEq3GtJz/r2C4MUx1OKgo5Gcb6xnhENHX7G5SlGPhKTc5IPbrWN86HCcST/Do6+g7ROpgEd6PKJ8pRCerFR4rOsKEbJHOq6EEEnYJZ32D9GozWPiB496n
      POSTGRES_DB: AgAPKmyvBIFltV0iFaqw8lpRZCKto++mheeRBgrUI5vcNuuUXFv9jV/I1hpnV6ogCOiLsc2fhACLNsvPdIK+F1Ehqq1GSfyguGP5GoQGcmXLSpfwwFv+TH667rhuGkDl/8hVfQGPv5P8L204cmUZzbJoIVHK1ULG//o+ODa8XTrxqK0+/sdfVF0EzVjxvtWzr3GGzRVlLlKX0A6a058kWbpDY116Eng7SuHYyEPP1Ej+OCWwqFLJ8aDdUWsVvwhBSeErtKRT+kPJ/+y0H9AbtC7CaqoC9qQ0xMiGwDBfdjq6Z9yjN8xzpergzbNvz7QSKfUIHimVukPWYUzGNgduIX1rCwSv2SfgKfAIJhzig4TZ6SbZFj3fs48Rc9855ocwJfwmchqlmtcmdvH4u1z+hcFB7s17LZqFRMjPgiNEYI/Vw2d+ixpdEg7/Q3/htkFhWViuZA/cg3bOKsKAOoa3HjNiDjjYraGlDjAjKILHvzO7+IrvuD8WKNajdLIbVfJXsktIRItACSUTOLPyp7C3Y/V+61x7xcMREtVO84f1J0vFNbbgOrkFFVWkicFvK4lXIyQgfB3rL7nj7cg8TViO8zHolzEZzOftkh/wK/kt+GHJnTXsYJZq8tMAQhVAHdYF5uZbjFV1ekLCQ9CLG+DwpA6e7+qll9oDGxuGAuIDouYo3X6p5G/TFJQqF99VAiX54BB4h5d2X4H/HG4Ga6S8BZwdMgAs
      POSTGRES_HOST: AgBOAPIOun20Bf7kwBUUabX5diiDXQN2RNoumAcoS9fawaemir9yF9V84O30DuFSO9Wh6DKcIHc5AZUkUmk17G2ytV8bFDiRNJ4i6LjlA1tEnYeMWCXocvqV+s6szbWd/KyFrKhrnH6/I5A2ClxbjSMINPOF+2Qe1ibJKDZK5E9F+PwobrBQviBQPAcvWDTQC059qthlP1LN3xySriztSS3Y6kzg8hkBQyZe8koeHzmlW7qL6oR37NuhZyzvTpGq0uoLz5evTYqHJVw+lvnx9kmafwYXNBIvOjNBeM2r/ISnYJsCMCEVVO48l9oKWgzCM116ebEfS6ndrB69kMl5UtlJdu33uQwXcMH0yCfXT17tkCji3e8b/CEkRNPxMOfcvnAZ9C8+YxVBciMeQo2CY0jeFRwzLaYxGfOMD+Lpl7qM6TmbNOiqMjM7D8/tFKtAwBWTydyZP2K9YafxhhGuDBbCn7SXcl00nLOmhjVlwL4/Ah2dQ0GWrdNL4u2EWqIp/WSga2dNzAIZ5zXgxWuclf17plKogjaz7xH2/tPKK0GvnBeXDgM1sqoGGVEBCA6IFc+hEJJ4xJYLXte918FaFs9fEFIQziDjdW7352pVz1470kylE/FWys+kkvPHRd0kHTFnTWoWB2dovLwdORaw/Ir5T4iK/1yB4tbhMkqbZEom7+LvUx9fhcZJ1c9DXxDBJfZNh+v5dcCc5s2PRL35vKwL1tCT
      POSTGRES_PASSWORD: AgCyNp6ya9cbtp7swvPHsbl7o3quH7D6CyWgOsZQX7pSxc6eBx8pv+wR16ahlkFOY8hpaM4LWUQSBo5yoRC5qSaO+DWCI+q4jLUBsgO7aSJHv2pOw3xmyJSuJF+v/S7rmQdoKV+OQcVGAbTbVlqaLj8lyjtt3XwtqdAQ/HmC9HQHsrkr5CNflqaUegwlHvY10fqc7ILqzHXmoEZYKNM2af7/dHxEjE8DVCdcpaTrzFGADTUExx2vfaulw/PtlPNKmIAHtXu16VVlr6mmH/u+sOal5jL3fh5QgaEPU4z/QHFjcIvYXxg/hV7WpoN7LiDhEIupSOCarqYdrJru2FcfTPds0p6DaMo8RVfbnSW5h8AHv1QV3C3sznPe+HBtRTCF2dNN78/B7Zv4ygDhYto+pDCVu92kO92e275LiKe89rwNKSW7ZlPeXAVdjXfj1upS4FqidohDiem3zd895LMQ3prsetcEvtoClgYxP/twfIer3zYU68PU/Di7B5mih2VBGH750U4pA6UXncRzoPe1B8l3/MSa5gkxXJw5azm/X8tvrJOGC+iVof9qJ4UGGpEllHHSTR9+jaI8bYaAbAD8LIPX59nwio1hxjlupYxHc76xg664vqRnDRjXmEvLOzBjqQXNxfYVE+wUqDvsBbvCFCp2zXUNLMeM1jZDSrDvr0xTmTJdwivQgYlBOaDi5NDLiocMvKO/wFOiim2PUjks+rpezTzIJppH5edbNwJ3ENQe0uCCb4bOd1nWcff/Mg==
      POSTGRES_USER: AgBEnr4zpEwzT+hXz/2N/dhSCVWz31fsjVgbK2kqKew2byFSE+RLYA9TaYqd19PfGAeMHii1D5zhGDc9qJfrYxCPH/fhSAsgPwCDlBEh2RSTjg/M3UClRtQ+GcgyxLXr1SMaZiummpXHlX/axoeWVVlMzX8FrZ5ku28M9A2F9bGavjKaj9oLH048vIOqPlwO5KRA+ztVPVsMfOP7mesKKaxeelblVVjXVjI7pWoA0bHUoGRP7S2uJOvwjoCxZcQyx2yne4QJUKVIecKm2IjwQsU1g9sSMumpQ+6zoL8uFTWjHHIwsVrs2YRf5IZQ+9OiA3X54tJhZhOgCyf4M9OUpSlaiO/ENB8qqiyVsuR8orw0NcM7c9EXPzy4ETixMQCdG16y7Xmol860tQfxrTpyHV1HITDkuCwyTqJnF5xcZ6FbivdsZJxPOQ2VJFBAjRt5sTx7Kdk/63EUJkh6il+WL1tkG//y/9MqpYq6pN6g09fUAMqpf0KpZ4FQA/bsYVPfl4ZVyITF8ZgVN7dYLrUy9lY+cgIF8CgDDZjzN7gFR644JqTWz4bdjGB7M8rMieWePTcNH6/vsYv3jA29yI6ZjIfXZ7T5uoKy5mS5/zsV731PIbrD+nB5k7jnmAiLypdw+5HxfzCVuzVlhVtInpTYrKz1Fls0c0sKGloWgNHVFdCSaiuCT9Xhbvpp2zj0XdlCCikk2lKNAl4=
      REDIS_HOST: AgBTu7q9CbENuqs4rdhhBMl6/jB4XECGzCTVAyK7YkGd5tr2UByB41CmXJaWKzWRbvu2LL/4EIEMoOBy9bmWq7XrmXe89KJ/G/I2vvQjtOkjs53vEWKlKh4r76517aQPMKxbjLZaX6WUWYh+OUQlQkT0luNnmuwA1xaH29TSjAOgYhjOwcvggvpDg0BYnQsChDlJq11a6RYxcq9EDpelAz9INo1JvM7DA3bXopK8SXI2I5ehMesc4Q62Xmja/WpO/vhtKDCyVZDiGlVXxXtojgkjF7D3n4lgRU5NmZP/molG4e7Mhhaz+ZS3lrtdQSA/Lp8n1JSqO+B7ACnZi1ySsmjsSTHQLa82wdbUkHPtNxD9ZrMxGlC5wR3ZwebK7sUvRbHVLoi78kJzR8qYy9wAG9Fw1p7t/NynzN9Gz4PrlIXp2aWSaurEvAOT52HZMlMmyG6s9HdJJ6EF3XtxQVMmFyPhR8FZ/vZjDbVbFI6kTRLjU6d/3i4ZhrIqWcz2FUwuPhkzMAVdd49OElM+RHI92WC2BgPaw9/fQdFjwFee7+1nzBBMTuT07oZijxLRFa/HiWs8Yluh3AYU/h5EwMmxHIiwj8rGHWWcVlmYUCUhgVV1mZEBaoKoCLHChUYWmJ37oi6xi4GWjNZxUmM7Og0z/Eh/aRYBRpmir/KYkYkwqdT3PP4t37QiiBVp0FflFlwMP7gvktCvdu4cW9+MAZyX5BZQ/gm4djnuOFE=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
  - data:
      url: AgC/q13e9+nfUHHDz3DiJeyQZm74bD2aWCsW8qfSCXzYOiEmRv7SF0HENfhxFJqoSCuH6ScoOnxLfSR51hCWHGdKkLriSiAamJau3wTgHBn/rpgzKivKyZusdYa/ucdRCzqOsUw1HyyAO7WNMcwMjn8VnuiRBDBiTc0oPy5OlVzunZfm6zVWurz9GiLApvGnf9sisaJGYnoJ577tSyHkZPgH2QztMpMmNfi4yhQ3MLlab3cSP/RmhSduLBsDvZ+IxenMl861REaMXx7a3XCaOXvP+Tw/FozCYeyp6iSbbNg9JuliKJDwe+qoKXCAnq1DpwaUxOjh69H1XsPUAOkii3i33h+MV3MTGx77zHM2OncMVU7K8tXiUbxXg5yQB4TBBclbzeRfRKLOmMZj5jDAaOK+e9jTKBilqzReZIZumsMFAbogHQnAH36xoy6D1diy4iJ/OR39+GX+o02GTBcZFLi4xEuU3n7DpqwyFa0MW7AYeTKuD6S/D6hjyKX/5T4AZNj/XkcsV1bFekY8XOrNVSdbsTECIz4cdkiu5McUUoXUEUdRiconc2y7zES+Oew4Dt8rYdPkOUKAQiaMDpca1pFDy2Id9u44hKbNN2lUIvwoMw4alnkXZKjcUURBYJzVlZF2ZX15CZmIcY50UQa4PAXpfHeG6LvlA8VKSE9n96V3S/aIGtPyH7RWfqAds2LDH3cSTmMpdP8l/7Hd56gxwMCwo1j+aMLOvm0szN9+HDGOG5qjSVLWU+lw0Ka38kUNMQp9m8k1yUmisjyf3X1/lUuUQeLcs96+dR7hvG1WQDxIlQpFFTMPihJD/AR7oU092iNral5hez+T5CXAIJOOanHzS6EmtWISCjg2LXUl9Jj2
    name: database-credentials
    runsOn: database-schema
    runsOnList:
      - database-schema
service:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8080
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
