env: staging
atlasSchema:
  - name: database-schema
    runsOn: database-database
    schemaCMKey: schema.sql
    schemaCMName: database-config
    secretKey: url
    secretName: database-credentials
configMap:
  - name: database-config
    runsOn: database-schema
    schemas:
      schema.sql: |
        CREATE TABLE roles (
            role_id     SERIAL PRIMARY KEY,
            role_name   VARCHAR(50) NOT NULL,
            sleep       BOOLEAN NOT NULL,
            awake       BOOLEAN NOT NULL,
            regen       BOOLEAN NOT NULL,
            update      BOOLEAN NOT NULL,
            kill        BOOLEAN NOT NULL,
            summon      BOOLEAN NOT NULL,
            users       BOOLEAN NOT NULL
        );
        
        CREATE TABLE users (
            user_id     SERIAL PRIMARY KEY,
            role_id     INT NOT NULL REFERENCES roles(role_id),
            user_name   VARCHAR(50) NOT NULL UNIQUE,
            pass        VARCHAR(255) NOT NULL,
            hmac_token  VARCHAR(64) NOT NULL
        );
        
        INSERT INTO roles (role_name, sleep, awake, regen, update, kill, summon, users)
        VALUES
            ('admin', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
            ('moderator', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
            ('maintainer',TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE);
database:
  - cluster: database-cluster
    databaseReclaimPolicy: retain
    name: database-database
deployment:
  - component: server
    containerPort: 8080
    envSecretRefs:
      - rikami-api-web-server-envs
    image: ghcr.io/b-zago/rikami-api/webserver:cc19af9
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: golang
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
route:
  - host: rikami-api-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data:
      url: AgBIFKQxNJ46XSnhZzF3P/3bYuynZBoxx6WiZSd9ha4mQX8G2exxK5WdvDLeTgt/guEMJ0EWOw0EeqDA4HZrJtAs7QSVwXlCIIgo15RgP+Jr/FZcvLfs7+qxMLYp6yk7QNLcYKgrOFLyvyzIbkWUCUU7nili1h5wFs9cCmGxWX5MZv6+bIl2rKYM2uTgE7z1JQtrzlgJNvR1Bzk1lPvUSNI28aVV3DO3e/69NNE9W0RBWafD3a/75h03ipBQN7GbNkpZHUemlrNh5xTB11Ygx2hynSwseD7VBbm3+oG+xC0F3/xyLovsSFMgu+jbt9utbvQl2NvKUhew8nvDLQCFZihfGUUps0LcQrbzuwClG5D6VLaDSkweBotodyH8fV0aRHZOpQwGptmClMSK5/PYcWvmGCQhikEdglV5c0regzoOOJ3DEwXaoKzZHsQ0s5FcCiJgyoPUiQOZAXd0mStPEMmQNaiphdAZ6yEmyzQiYLpJaZIX9E8Lac3y01lI2m94SDbX8atS/kjWezoJ3JFPGB36ynuzEhZQmMPl6yYkrYplcwwk/WoL03Hnipagb6dFgYHjX4y2cTH4NZD4NtXpzy8VmPg+2g4F55M/xsE6Tm28Cl4+D3MRJxgsfzvMmoZsjkZmFzfxEA0/Vf7RYjMQtWhFTXrv0AfIVpNyd2f3J+DWivsrD1EVIHaF4BmYhU7oQxqZ7A9FPHDtBjDKS8ylAx8C8tho6lbZYU5+0/ZqSOdKyhmlgSQPihA11m9Iotq6ALZb+PPPe3f/2Xh1MI4McTMV+7trP9Sy/KBKtKI6eYniFCXCsVTvr2QsAUGI4TjxaoP/AGMGGRE20HUEiGSD0eTrr27S3jU9FAg8cC90JKSWGTsh3PvYgmdcWWc8tnHBJ86EqT0lP9Hzfw==
    name: database-credentials
    runsOn: database-schema
    runsOnList:
      - database-schema
  - data: 
      ADMIN_HMAC: AgA/MbUvZBUeQrkrqc/bVDhGa2j3Nma/u//9NjfdMkJH4PZpL7WyhtRMkuz2HqL+IVIUSXJx/Mu2GWhJ+YqzZeL7TAljgdCS4HKm1Cor3e2owkLsBb5nIPCVSuMjAW4FrP1dktDFPI/FM/hghC9wARjw+MX0MjaJlAu6lGtXXy5F6jp5yuxV2+lp7xV7mHB9hrG8lYj+p1rHkDBhPct235wtYlzWNgSjjqwRUIsil3uNSjr2IJ4Jmw58Us5DRDClvCYJWk6kQm62WURESw4tf/yOgk0vYEFH/hiWk5dRiLAgPDgUoRv2mJT0/4EGFcjI2/iKIqCVWGwSm7uaZSua7sMkAOxSVhNlJmRZ5eme9wPFrQsG8a4GENspIxO31H0WhLX9HdUpFJj6qZtOSS0t+6SuyLonPCZBhoYe3ENL6vDD0xDDFrhqLeAblmJ3WbPaVvyb4JuXLZAo2bjIVXfMHsDuz2VqXa08ALc5JUpjZK48Oc/Tl6IkGxd67987FS3B2akN2b1IbkUKtaaloOnOer1oswObIKgCiHIrrXPPavKk7P5QOtKH1tlNRAGC74cgMGbhFDIhNc6cZEuJ4tXd4yV0pq2lHJ2YJhoPS+T0+9qtdLy6A3+C5K0LGWvtJh0XpnA6iyoPjlC5NLsxJWcJskU7ySAI6bcjWk1o2kdukM22vRZJ0yVQPTb4wYok4SLU+nMn7tSJf28P7jbhqQtH6nQYq/ocox5dtR+XrTRmXDeJweDd2BsEzBzxCSTQTg==
      ADMIN_PASSWORD: AgDJunxbQB3CBXB4aaiKPhbK4SUAf2oVHAxUejCRYzwpONXOuRkseTm1uC2xTho/EKEXgM8MtU8fEXkN23LTz2OERU5qHnSFdX+8PbURs6SOf/YMPKmpT6T4BgHpWq9DumV1ouFu3smnzi899BqN19xVESKFZV/vc51CaLm8gtA2czrDffhDkCN/TXjR0/14QjsRiclNEf38evHOLzalPuIpQ/NqGECxMOSnuDvR8AcCtgO76ZatCm4h6MBYQSRmBVwYbDLN4pdHl9PRjVmEppj1KnTz1khyu38H+usl8IYFdGQK0biCUrbFHY2cfI4hJe0BA/MecwdZt9RceNoijCcNQOcoxcETY9jXgZoSgPSe7hQNTq2Oc55yy2PdixELlcPmnxFuiHMZj4OsHnpsfs7EAba3r/y9Dem8dz90Z0DwQrfQYkpV5Ujcl2dTxLBFDHBnD/lIK/hK3lyBL+st1M/KFLhdQ1XUZ9G6F/vAFN1FS2januiH2JV/OyNkjZcN4nzhdViJiURr6xQ751xpTku+28aYGvLE6q09ZMCRcziQOkNLetLR2fFsjVVYYX/dh2LbfK2HTw3yrMFFTz301H3qenXZN+IzVLbZKva3sRCbM1g0KPHRn0/XfjntntZpQcqOKygdiXhVoQBku9GAgAeBxeC8VYhMXkp81/O/iQVdngNy1qqYzT/trqso+DrK+bux8aZAJTcP
      ADMIN_USER: AgC3HlguzK8RKtdyYSr4FmQJA7iUcjVvMSnhYQ2VzhDqmPnpd3j8+nLLStwKVbRfa/CbXJnQvwlaGWFKoxTjqqaBHexT2Zb9dDz6nU+oy34Az9wC+6R4onUkEd8vbakvfXUvjMbeoZKw+TS4wbpkLm91c3BCoTUn/7YkvASxx0fa8RiRGK2X4NF9ridR+rdn865Irw2Urs3mNjHUF4UJfijaiAwR5ZNY+WRqsmMohZhmXMAxHe0HRH6JrVi6dK+oYnotMVA1uKkXC+y5HQivgKLa0jolbKojiK93Pb0/eTTt/xrFx8zBM6sEcyXYbabjxQKJiKDjmzNhFmWJS1FKF8VXAOVUcGGSMpEeFMigohQb49r/sxUpcdIRLDzKVZ/Eu9F+WkW9Ht/BqN/YVI7IfDddha/KCjjVHy37AMql25H3nbJqjzmqKbiQ1K0AxBxyq0nsi99kXXl5MQQrRVhTqb13pOipVubvT8j0BX+4ayK6X518pDSZZChB51V+Y1YMGqWuf9r3o/xGoWyQ1nhXNqcDqFP2GWd7OLzmM7XhzjtP5tOUMRlDrXul+ARju51I0861CmQpqV8VnEn7P/IJrBHXTTchWXhoed6nrLthYy5nYyY2IjQY8Lnye1tfwz0arMRW7Bbd01TqozelVZg8T+Glr6Dufgl/1G7JXFvAvJQscQnAGFgrQA6MVCqhaYxMDtqfAqLh
      POSTGRES_DB: AgBRaoVTbM9kA3FhMLxE+O/AVarFj7S9cFWHVRSt7CPtV77LsG9MZjPN9HLelMG9IOZbZNFSm4FXPXFwy5hP6yGFdBPg3vwR+nrRfWaUU5SCJ/xxQ8/624PANWCYREfjymDz5BY4m9Fh7nL7d5rXjjE1lsgPbCAJnlvPHCI7bxGvpgjuZhhMJA90m2cxsTFbeP5XDN47z1qkhhdaok5roULPVXYgLTr65Tu9ak1k2SlonQM7QVADNum5LUNJWt3nm6CJtROvn/bKCthoIlAPIUtC8z3lBxdJ4/4zx8o7uGPkah6wOmqy+S5iq7W49r+zoGLeX3VAEq2kTmArBVnWZEVka2T0166DxjTd3IaPdoIE9BVk2gBx95Zm/0bklza9ryvvqwJ3Z+INMAeDdNyK3bxY5jCXirqLPu+IYrbNG7AqSX1nKfo1tia0JglIHmZB4b0e1Lz27Aewt9K0yKPVOF4NhTfWAA4ktCmHWC2dgzFHuaM5nWUS7qe35BLWOfKH0A2wYwB2NtOClSTdJ8aVFQ6zaEtr09jVfVGMNwqq/+u5BbL2pCFRmQeRqTb07x+Y1Zq4uE3aYysXfPA2w0nw4xdSOthJylk2u+IL/cxZejPpU423P6C6ny9VUxk0idTzJQGwBFqCkJI37YIkHP+xq3lopSSICa3Rg9RU3zZ2IaOsPXHiA1Ikl2PXc9O5Q00vHhQJEUkdam/b8hr1
      POSTGRES_HOST: AgCCUwCGxYxODI292lPOgYIokcsfolyjcBDsLtYbdhtGsR0Svm1pXpIzCwOJ+8clzLcVgNtxzKVnkvd3cPQybU8UukL05mtCSo+QIQvheDAWwQmymBScaF3tGilppkpdmKwmjxzEm0y3QWlZRbXOeYzDI+JSmnfY3grjyUPdzKHQIea60eet0xPQFcHIxuGAvy/FGiZewGQ5Eppt8oKotFZl1rQFSZAR7VlJ6AfTCBszvBkCI2L+PjedmizutbxnicqmtXcvY4dYRSODWwzMce0jOsuhQ0j02uxUWyVu10yO+U/CPrtkXESQBmHIq950I6jBLq0gQhY78D7Gqw0gx+an3rPdGoKXuFigBP0DamZQFioE8QkPVmMM7Jbbi1vVXQCWBUc5urBwhEPklsRyb0YhIcdMuEoclUrIkWV9Z8jKE0jkKUfQX7h0qaG0EM/8NcPbjLtENgtW9e2uwMCpRFjROZ79+B3e3J23Eitngj5qa3t9N2pVyQO2TXOEnG68+ghSkyhq4KTJF+LhnpuukaHBgX2cFpV+/1MSHJi0IFbRS2M43a2KVZ5H/iBPEHQleWKhmDwLfD8IwEVT0bHdtH8MawTALKm/F2wjsF/l2apcO7u/Aq7Nkaef56Ni0RIi2mr8oaJszqb6YWdpNj4HRhYKYVgwhPBLAh/vLr1IWYy2yN+SwdNiYA988juT1RNnsSyMidITF0Rrpw4MXmOqds8v3UKowsGcJ+3d0xB1WaS7LjP5IbvWQ3LpS2k4Q/I=
      POSTGRES_PASSWORD: AgBNOqErCHiEbgVZmEpKxxB+FTaZ38hXqKlNpYqekBD5E5WeGdnJNHUXBKpUD+vX3PDVVBbgrZ9QNltyua8McF9wX5SCg/eZb4NHww2Ho91nAStgEqu+Bi8kETcyUtnNqAk50padJqAn8WHd3y4jpj2WQvkJuvzTactZduYZSTvJanNvwArJepYoNscWj749KAVfRJjHZQ99v6pc1Z2If07NS0aYdyHFJoOOKDOARC/QP1db53lvDtao8Z7mPSFkKdvLFo0GwZJc7WR13/dqjRgILvNTGKD7J5wr3mzB/Ux2mRdIiZRt9ObWIeSjiRtS+yc9UkIDcpAOA4PNENY2rC7H8pd6o7W57Gzp2w4p+3rsyWtlLIP+USBBUOU8+lOoOlHh96INHNKeyAOzNclUjpYEdfv9BbeshUm9MSNvisedqD6OgNo2fKzB84MZJ3yqRgzB40PX+yP7BBQkhPnpQWpPQhR185jlC0DwMx9zPml7GnQdT13Xszjb+QVBzPy5CJ9Cmmz/OjS5g1OM+xdghLlbi37QskM+0KxIk7oLc0vMB4ExkuQLwctW8zef2nn6GaY1/+3RVSkb1TWIVkGq588jN/Te/meqIHRPlTc2c+E92wbdygx1dVmfDxwLd120+/QhPKuxKdIbgU6XWo31fUxaE/LaURv1ibWFgy+yE/vp+kN/m8iguus316Gt1GCQtjSaNpPM+OkC7rbl6nj7Y9oNIwJlWIAfoaS1NRMm3EQIE0hg4tL3nhgTD2HxzA==
      POSTGRES_USER: AgApagc5wwg0z2kDiMBHzBWqABmxyBPjN3yh9eQi+L01R7afrNlqsjMP+wjQMvG37voNMAOXOkJMLuNkZxTjEE5eC4Sn9p5hg9e+7mNLcYjvXoaNBXJh3hkdVUIFNLbIP5e0LOiIXLfgmGVdVwNhxs5j+LWmm/XQwURnxibev/tLGQQSRXUf+vFsGz74oVl1949BNXRowv96eNz/fgmvxP5HShoV7GkM2dFtY4950oZenm5ua83u9BfnCppCUtZp+EAXIz0JgGRYTGWdE5HHBGBVVa9YNQuhwE97YpJnXBHCmGv5qXYFd2KumNGycBWKQxNnUfqfh2kR01W1I5BfsGYMnMpEacG35PerNRQFxx6fYOEdLyNn0ijjX2z1SgBTJnBWdA+KmVFIH0aD0bRIe1vvm3MIK+fK+lZmwuRmbGRoQB0gyK+a3i+Z9CBVzGi43Frs5AdlESGAtB/H8Vs9cQqKL7/kvOvL87TcCPWx4tzgXflFgnrSjA80eQH7/iXcG2TyXmbFwp/Uro+6SjtC3YfweNIg6ppNjIc9QyHm3O4F9tp+gVu05ETrrUf/ZddyfQLj/H5PH+acyKldfKVkwThlCJdZ0VfQHRx7qn684iyPvHqNSxxABxekKDysDT6Mcori8Zz60jjYo/zQTOhWREtJ1EwXuTMRQnXaoxGogb5V+TvYTVZWcMpXgGxSsjvLOsXrDgLlvoS739JD
      REDIS_HOST: AgANduJJ3+cDfUOZwKhJvaQOSjw42+vGhrNNvigJ0xbBgHWPExev0MRDQB4QngOdasutOMvJNDHNgxZbrTdPXvr6Ibg8F0YOak8oT7WmvizsncGig+wEsEAH6OhWms5seFxl7QUW119L1CGF/4sH1dcjj0jmODe6xicFMj3z68xMN25Ks0JRHJJ7hKZsTQYAv1v4VJrXMRabZITg5hYN2tTdt6vlf/bMDRoMZviXV/4tMxzfQl0/eyPwdY+xGBXnyLOtEFIl6xAOM4qs+hWHmWWcnWKtE2dNV5BbSteZl9xSpRaeFHiyYjub3rEYCIrGVFzAwdmTF2q2Md/l6bKeWyoP+Ccr+UMRYDrTqTSVQsas+ECgpLtDfBPjZA9h+Zd71ry4yM176+SsqKwuPjnA88HgRz9M2kuECIoTa2Lzsrrpic6ccjUaWrN4C35YcO2L8Zw70qPJGKR75cZ2JbhDRuZg/IG+gevLYxGzGxqsVa/r4Xr6SE2ZU/EP9XvkW5bkdfGs49W9oevrZidfzqC2Mk+DjLn0bgyRHehzrV0tdZN9WRVB5OAbe0BsdFs4yX2sprwTkWUmmgg+CDIbvxezboS/a99kzGVEs77SBjAE1ZTVpW5lByNyfG9qEOMBBRQXdC5/Vsfj0GEk27Euge6KQHJwr2+y59CfKBC11hxE+H8oY/kypPWsYwrDoCAqOaW4G6teXIejl7de+J0p5MISv/0+MQhS91Ir8kU=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
service:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8080
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
