env: prod
atlasSchema:
  - name: database-schema
    runsOn: database-database
    schemaCMKey: schema.sql
    schemaCMName: database-config
    secretKey: url
    secretName: database-credentials
configMap:
  - name: database-config
    runsOn: database-schema
    schemas:
      schema.sql: |
        CREATE TABLE roles (
            role_id     SERIAL PRIMARY KEY,
            role_name   VARCHAR(50) NOT NULL UNIQUE,
            sleep       BOOLEAN NOT NULL,
            awake       BOOLEAN NOT NULL,
            regen       BOOLEAN NOT NULL,
            update      BOOLEAN NOT NULL,
            kill        BOOLEAN NOT NULL,
            summon      BOOLEAN NOT NULL,
            users       BOOLEAN NOT NULL
        );
        
        CREATE TABLE users (
            user_id     SERIAL PRIMARY KEY,
            role_id     INT NOT NULL REFERENCES roles(role_id),
            user_name   VARCHAR(50) NOT NULL UNIQUE,
            pass        VARCHAR(255) NOT NULL,
            hmac_token  VARCHAR(64) NOT NULL
        );
      seed.sql: |
        INSERT INTO roles (role_name, sleep, awake, regen, update, kill, summon, users)
        VALUES
            ('admin',      TRUE, TRUE, TRUE, TRUE, TRUE,  TRUE,  TRUE),
            ('moderator',  TRUE, TRUE, TRUE, TRUE, TRUE,  TRUE,  FALSE),
            ('maintainer', TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE)
        ON CONFLICT (role_name) DO NOTHING;
database:
  - cluster: database-cluster
    databaseReclaimPolicy: retain
    name: database-database
deployment:
  - component: server
    containerPort: 8080
    envSecretRefs:
      - web-server-envs
    image: ghcr.io/b-zago/rikami-api/webserver:af4e2b1
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: golang
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
route:
  - host: rikami-api.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data: 
      ADMIN_HMAC: AgCvkScMA+SuHMZkNbB/u+CNUnKOW3VDsKHCWVukiS7nGQtjnL86JmD5Ue8FCfa6THw4IrGPB4lCsqjbkvTDxfCQMJpfBptlwkqaFn6SS6wZpLHJga/Qs5FBTM+vwtwN5cjjnyB7JRI7FtSg2PB1ySkdsbZhVPVcwcJZ6OgSD+h9AS6Skxe+29ROnQpBiQV5ft2b8ktsYzdxK+Aq4Ja9i6XNXYugmIlx5g43t/sjH66/V2KdLxpMWTQT50/IuNYLiIkvHr2NvvtTfuH+hcPT6vYw45dot6c+X8k5KJqc5nLfOiXOFKoFeB+Z1CvJ9kV1vt86MSSv4I67RrvRI3ngkKlwsmjFad57yn7jjxuIlmDZY3WvIZBN9C1aTGTo+PERGSoHUEaiQfOQjsw606iczt5+Dut1SgNHj4VIvb+WWhOJGjMIpyqJp8PugY2GK/wlWappYRXbw1czQrJYm9kUihLlulOuIJ7gyCwxLp1QeAg1jHtC3k1Edf7SnmDneb42Y5235oorxCddSU9W+ONbRr/YDs5kdKD3ZkNJDLsAZPV/lJbyKQvuic9ZqXmZCyEW9L3VscXmL1h1/IsV8JElCCFgiCqFrXe9Vajn4IHCQWrKXEmbaTCKdRuK8hZOSke49C/vB5XntQrNiQnyVMZv95TAEX9HGfHdXHAkcwMdc6VD8hn7ybh5SKKbsf+KKXi8BeD8WZgX8dlQaJwTir7tKCUmhzb5jPWlRLgPAvUf89kJa9DKCShIBWHOphu7Og==
      ADMIN_PASSWORD: AgBz+7lH5IPK0XFWuUyjdOEKH8tnFF3LISBxDf/OC02oSXs0co7250RGBXgaasYEMyph3pPtzXuJGlQ0PmSJzhTTz2GE0xsEnib5/KHWfAjCxJt5wE/ykWSqEpoHjwsl0SVHZc4sgjDDLNGvHzMXu4HJoiG2WZ+4YSxx/MJABnQBBJbG865HFh6xqWhWlnJ4s/r+HYOz0AQukMbiXXrognNiE/0warnAtzkoQiPXmtAuwATZEHscrTXnrBchEsCFN0k6jklFV3Tu/89187EjHnuoek8mP9xe9DFRIfgI5JMxROxBofJ7FnuzY9dpqeQuBtBfF2n9M8l1XHkB3HxPm/ECD72jrEotXptbLEr7J3K/eHbe5OckkND5EX+/bv8cjg1F0HTF/3USY6gy/lv7FmVqrHVrGoA/fx4xGReOG1w3gmOSbbGkLciA0tzE3HqxCHSAkgZe8JUrAKOteFXWR2Ay52lhdnQEWikHhex6NzvjoR/qVXrsNROJHQqmDavnyoODsIZFCOEDI9VqFbX52lozMzMZOkDahmgqxJi12SqudCjYk8eAVebd06xReHvV26hlfi2qHajaijDafW7v324pPoZWeFEAGKSzG6SNxG8Wwb6bHh+qSDcCVfmlTOF5VI+SrQ/dOPkG4HLCGjqd/QK4+f2JC4p06Rhy85XYw2tDxCW+qiqsPBRtAcWVBtasyTEn6F+JLYIt
      ADMIN_USER: AgBG+2zznbUwDreNEqUXlmnIzF5mNtXj8FepLAU7QlwyZKD3Pke7H1IdPYYeR6ZCgU1mwoLeDcdHQYm8dKAp6oPh7Q2UCpUj1tSvWc9OPGO1edF938qe4vkCHNzgGUFnNf8sbu005RBL9ACJUotvva7t94S5B+hGCRLiz5mbsIJiue9zqWROiizBTlVGlo5lnxy5uBfIXyf2+EZgDRaVAZsw9dFEdPX95urZksatLM22ej52Bb8x4Ff+ReTrr49or5lwKsxcr1zUsZ/eDe87ite4vF1YgwEBM5gSF1V6QNIIKfFlA3uXDt6aSWihmp33eTQkOiV6jQkRFz1/2RGIAZ7xbMrc9FnalRPXQdsTQi/pCMFGQh4JrOk3dshH2hrtmNlAHoz8Cd/aEH+p5KS7r96JTeo3GE33ilMJEdX9fXXjM+XdQUuzZWYCZaw/8sTjdUAnUM+K735S6UKMVt/0E3YKse4/A+HAMviRhXBVoNu+0DeaZWQd8nfOG6H7lHW2NH7O2/WWI68TIbGOzVdeL22Uw6b2H6NF6AjzivJwpUD3fsB1ulucNQyg+07jnO0BKZLaeBDsKS9IsITcVq2yD0P45BKQTK3NBhjcWqv2pWajhMT2xj77+gdGv5bW4XsNm3gVrN4nRA7Jlv7s8yVe7ha6ppgFO89SYU+/GJamuZJMiZ17YyTN9o+Bc657Yy5GZ52dkYxm
      IN_CLUSTER_CERT_URL: AgB+6oqA2BVKPMkH28nrQ6E2fthADYou3gAoCr/ZDB9f4iWFe6x/604XO/wll1Xh+eQ7rOS2ToSPs9WLNvLdQipzDD0T3C5H77m66cm6briOir+AFYrBTEbXdjFn34oHnL2+4eKASWMWOAVcTwZCIfoARWuf65VhjULQZMPRjEVySODCix4M7XcIVa6iqOaVJmOpzjGiBBndTnyjn278WoE3E8y7bmqsDy86npOuPh67A5/l/rB3Cuk6St4ErtZ7mbO+/lXUAUGfp8pJE62wliarsZgxeEyTZOth2DsVLEblJNCJEoRhM8zsWNYOap8Py/X4XoJHiOR6CE+DhB629eyXpQXK9hpjdXUVWWig4nz9LjeTSTnkUcUcvugfr3QDXPmcbhgNVtWs8eNna0JuUrJ48YWrJG2AGhqDbe9mFrFOfstZmepknLCjDN4ZD4PR97XR8gKqru7IkIDdkTlVhKOnZAsRutdtg7KSfmgrMpSXnk7iIC2KZ2DJvPNmaCYsUuYM491lzyE8pJtrkDKtMBEUfHXHk5CYPS8jfa1/RBa4pZm1nSxSFv/E5WklJbtkS3aRuyIg6QlSA2sQ4JRKXw0hMsRI9ZeNLOFaA35cYQ+3Wd7I10Ie6HvHMaEOzi3Juudn5sky6miCigB3kCsTCCTXmP+PClRv89Xk/JugVYsvVgoowbwo2gPLgBA3JHzYLns1eGV7B6nyOHbHPxnuWFzpXmeilxoyQgnP013VKH9g30Ku8txy+Wq9vm0QcCFDOGlh2e7oI1KIOSVv8w4n8x8JJcTk0g==
      POSTGRES_DB: AgBzy972BVcu7W04uoGkup3j62SN8HOHnTtSU2r3LGTDepMQYy9Z3LX27z5UIamD8GjsuJq0Al3x8OMlPnguPWAQz41SsLkvA7F8tGr4eofom5QFaHtg/TY7Fcd3yUcbRhlM1Or7fuf5fYOSZR7+8m32rIBnDjxP9kvkLyP2b/cwBn05WdR5VaXfOfl3eX50AxEk8Low818/o1/qzTaipe0Au86JUjOIM0CS9EjKgHXaEVcw/SKeh2YyW3rPi3gakiSGGGLo3/5CpssCf/lsyLTxCpJiPk5WB99+cxZk/xRzNalWxijpZudjdFBIg+SxZbWuHPkdEir4GiMlKTD5mAAoxlwGZ1RxrsbjQzXmSEq0Bb1jewu+03r3ZKismaZEORJJLPUmBq4nPoofyvtxEtF1maflrtfwIsZt8T2rIvhHrgEU8bsanSZMX6VF06DehLvD9BCCorNGvaOCAIR/UeFTYVSqWsXKVNCtjYOQ6nxK3g0oFshGrrWqKKvQm40Tht7isN7vHQ5dR5xW0kdAFjN8Ppx2l/xHNXlxWSwI1LccTbeNpoluwkHYZvKo5fmuNy44cAraArkRkJyisPIzw5BaxIn7uWMoJrn+/488raTMko2BAZY1uZMLvPgvz5dYQT74rYluuGlRXTurDJFUlLNcSoldofBc4CTp0SooszBFp5iSK68LJgVZAFS2IMKTqH3Mf+Qwh5MOoG/D
      POSTGRES_HOST: AgDQtzcoh/mMOJKYWMvZ5Rgsii19w1pNpyL4z7TTfFsAHPwg2SnwN734BqYYx4cCzR0rDXro1xb74l3SyXir0etN0oEPsMUqmrlehLO3Y3Dl7sQynQuZ7bRPuEKqj6TmM0EKsZDxTuCtwsu3bup0mhT0ppfKp57U52nqF2B8L4p9gdJT5w45frgLQVWpO0D6sa1hJhFOJi/UZBn+rRKEHJ4hAJlkdCYHhv4NKigo9lmo664o/mLSV+Js1wGb+Th5X7js9C89SYkmRFEVdOemieQbugAoWSe5nN7lafa0XJcAX/o3HiAtmkYaW1aJjoTOvTSiOW2r4Zgnk5Y3OFp893vD7wG7CNgZZcUWRYto9i7i63nMyh9OzO9j5UGzkGr137v2/LFfpeUS4i47pDD7cjGDhlhCbv3nZKiMHVkYhOmJY54AG62J3YLNJWoFHOBYC/wpPd6sDoPIFStb/FcNcBacqo2eLPv2IpOi9gyUSwrPkPyIeKyaoPwN14e/GfBX3VGzfm6rkThHxwkXmc63kK+4KCdBoBbMCivrZHIYxMWjQzMZPhx8TemNoGiWOCaQb3taksws1VxK9smP03hcxv7xeFhSpn+xi9AsIf+TCDVrE00iOdMqMExRzP3SA6mpYWRl62IRqfG5kGO5RWts5wGeOOucMT2y1hn4wEa9Yz+/XamFuQYrefeuC8eHF8KTZFBIsH8/CNvhDjS5Eomxykun7AKSnRLV/MqoG0kOzZTB+GFv86VjcMkZzsM=
      POSTGRES_PASSWORD: AgB4LMmErpJGy17DSIWcdoUcR2IkN+ZwUOay7ryh7efp10hyqh+f2nEAjdCmzZYgD359LFdIDcDIBQ2Le+UjgWSclYq1Em5y9AtrUAE9quPAn8Iqvu6naw8nA3422Q2H+4cBx9/yKDjstsCDlPA+UJ6aajT6g8t2zuSgcSb0VJAIxFj4LXFC2QlYUItzbp7s3o04Svmx3DGerYCmnBIKpHuo7UNH0kKVfBRJb8q1smZnj3ylXb+fjlRnuuNZ9aZz5NeX+GOz02sAJKun4h2qUxjNK7qaceYckoX9/w7eMR3E9+8wS3xEA2+2k6RriV2wrpeVVML5IAe8kGYCehwjmu3nvPWF5mOTqDWT3CUroxtHbw5WPjOw+6u8XtPK3sRFCmn57IpuxhHsVp2SJBQk7PSHAQZaarm7UEyqY15VgAGV7Krn/Q0aF7sJBzVTJ5DUvQSvijeMUD9lKaZYlyDVvAvQo/3aOEpNY2R3FmpmlAOIudx1X4FGhUVeQUXjBIqeHpYRwbtYOPgXuys9dsHbV+jdJ9GMYfWme3bvAB/eSBwO+ReRs7y/Spn7S7YGXbgNtdxj0UFLNcMGjgMRv0dTqGRD6ovaTgJjRTyZfZmBh7K0xJjHa5O5xCexAh2r3prrX4Ips0jP6YpkccJiO6Hf7p6Vh7u88ZwAJUJhuIPJwcIveD1mrxG9QYtlS8mAWT/q4uE6eyIclQ1sx+Eec4SM0/RPCS79IGN0USf/Sdg00hxezgVk1AjllHjBoMppvw==
      POSTGRES_USER: AgA5v4slLoBvV/TGv4BA16NvIL1hymZbmxIwToLgjOLncVOAu/yk6OQYqrIpQIXAERgl/BD8VHI7wIwL0zve2yaBwcrVceJPjCMkmWykNhtkpmR6kY5AiB+v/2/YZb5XJKuDqXOrdrJf9jqYtMPJHdJxcn0QB+xmAvYiyIHQwmqW8QQyl6fVc2L3pJAy3rvpShmqVfa8l1fvzsCqWRaGA71h9Zs3w3auOVl8iAHD1ugdkKmDJXcdB0YhJFQ8NP5Apq/YvcKJsSgkf6X30vieuTlbHL5glJEs+TWkRefNGvjNMzEbOkrD+gQzvYP9wBVtSaKA4hhvo40hTVvvMFHqpipTZgn4S+147Z4HY2L4Jw/J7qe1/OKzTorYRXtHtjKYwgiCMzh55NH3esnMHAMJvJVjl3i5+Vei3mv+aphSuhqaYs5KK903ZIBHA1unTmE0UjACMdcuurCgxHZH/eGoJ/caHi9m76d6eyHC7r7/Uzs6VsDIvyGMHQ55Y+gvzCYk9hz/nCWm/YC6Dt6oGtoov51xOkYjrCJrH8QbXTaWTmCOIlUjgDU/Ad/ymmC6fAtIvWj+IhelBAnnZJQsYxGLAK073pPNe7tdR7z1OrORLDxhB9WHqJm0EeAxrwWVW+jiMDp0crcsL8YjK1FY0RPUAuzSbOEtfMWvDG1lMpcSIUApH2StE0BnYaRpUVWiLLXixDF1aQfIdRDjOnb0
      REDIS_HOST: AgB76U0bCT75H8KU7YBfeq3HIvuA3pzXMZJYJ4YFQ6f5QE56LA9V4n9LUy/VioAXZl8iSFWjFatUmpOlUGgAJNtI7mn4qUKwCUeLztEpLOiNE+XotRUZI6R5lzhrQmztpGktCQB3TrXXuyYlExj3VoRRKVY/dQ9oXO21Jlgdk71vB1YC9cL2OXOISyH8W4lPa5iDxrc9Yqio9GOkU3hK5fyERKNeqUR0Mqw4BY8c6n4qvxzLpc4Koi15af7XNKZP6ykDNAHkdLbP0nj4mpWtloHkwp49VpszaaUVGemdvSYr2rFa25TEdmXBJx9QRPfsKa8eTf+bAAHuZ/Pe7+GaQWkJlvMZsxP5TRSp+Dlm+8iHT2IdpzxxyT4YbIzVAMZcy+PReF2Qv/Bvi41lGhnkEi72kK/n+6febwxRLqly4vjMC4L61927aOKdcUaNZogqfpswH44NuJ7BB8NdSKEnNLc+3gAieDpJ21oUZ3/WWiWpfbDKh5UhuuqkqqPM9zAJbWPHKl4QVQwKFkCtj6GtwMXodtKY/gpY0MlSCH6Y/C8d6lb0udP70JzUrhGXKfa/yGjZQVYtZA8CppcYS18bZLPCLf13gDIWwVy+Duu76PEHNu22D32AeTXCle0UTl0F0HpYrktx0Vn9K5LQV1L+WBdluKZvKXGE4c6Cc3SAX7+o7T88tqHCwAsXiadXLt8mQoqLzeoE+UnN/1dYZeGhqaV4i8PItZas7VA=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
  - data:
      url: AgAk/ACt6hUYW7pOdZbvvigny0DkkHH5273IhJnpl2VZP/dvHgEmZ1JnZxuDr+aXgS2j2NssTQoNg7TNLQN9e0rOuNNTB0ItQU/s4Vh4kemNhDH0jy5NWheqK3S2dCjHwyPb1J/wlAavFGNMSYBH4g1bc7TSV9zVs94253GHPHf+a66zek5CRHbahXqyDZOVnPIq5+YC2Ij6p3l+mSMT9f4HuCaRexrmJT1VoDXnlBx2J0ZP/aLw0X3uqyi5jNeYadtxer7VZFB6HeVqu7VXWoUej1HKF7R8o2+/zOgBfU4zl1r0543T6ICfanunlRB5fQB10LAQV8vhb9d0SsKRb7RVUt34iHHTLQkmhsV6eg9G9xLBsxtGH7SMMElxJFsJ15jIjOjj4xxhKGUh/SKwgMFmOO7oT8pba87uMm4k5sOPmoRyE1wzCEVTB3rkBwXhN4kJ5tlbd8/IPkf11To7wb19oL1muo3sr4DwNXwD1OZOv2YPZXS6PsvQNpw4t0s0g7vSJMI0pGLd4RAdnFKx+VoZ83ISt3dNZp9N378Cvy8c1jxqy7gM2nEilLYXTEy1Auu7IIaJpJgkOelU3aSa62u/nih283VakD47nqjjB5XbtlrIATs7h+LEXE+qraVhkvHiKVMIvinYSnm+GK72UhhX67IOA+78lTP4YbbyGwa5PPtwTylsFVNy4vnqS3NnsIH+IxO3VBlb1KILRpNVD3Wo1LyD4Slkdwi+h8f83aj6mmSYGKcQdLsA4EKX9+myfG0hC8M0yemIJC2ZI9Gy70IFgg4KktAiXS1bkZryTIqx9EBacRYwLLPDRCw0d8Mqe1nBGxzOXmNOQSdMguRZwWO5EgzpElOIbzt+eTvjlYpFO9ji+pvkDpxzU+42siP9AMn7c+GsQw==
    name: database-credentials
    runsOn: database-schema
    runsOnList:
      - database-schema
seedPgJob:
  - cmName: database-config
    name: database-seed
    runsOn: database-database
    secretName: database-credentials
service:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8080
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
