env: prod
atlasSchema:
  - name: database-schema
    runsOn: database-database
    schemaCMKey: schema.sql
    schemaCMName: database-config
    secretKey: url
    secretName: database-credentials
configMap:
  - name: database-config
    runsOn: database-schema
    schemas:
      schema.sql: |
        CREATE TABLE roles (
            role_id     SERIAL PRIMARY KEY,
            role_name   VARCHAR(50) NOT NULL,
            sleep       BOOLEAN NOT NULL,
            awake       BOOLEAN NOT NULL,
            regen       BOOLEAN NOT NULL,
            update      BOOLEAN NOT NULL,
            kill        BOOLEAN NOT NULL,
            summon      BOOLEAN NOT NULL,
            users       BOOLEAN NOT NULL
        );
        
        CREATE TABLE users (
            user_id     SERIAL PRIMARY KEY,
            role_id     INT NOT NULL REFERENCES roles(role_id),
            user_name   VARCHAR(50) NOT NULL UNIQUE,
            pass        VARCHAR(255) NOT NULL,
            hmac_token  VARCHAR(64) NOT NULL
        );
        
        INSERT INTO roles (role_name, sleep, awake, regen, update, kill, summon, users)
        VALUES
            ('admin', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
            ('moderator', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
            ('maintainer',TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE);
database:
  - cluster: database-cluster
    databaseReclaimPolicy: retain
    name: database-database
deployment:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: server
    containerPort: 8080
    envSecretRefs:
      - rikami-api-web-server-envs
    image: ghcr.io/b-zago/rikami-api/webserver:latest
    imagePullSecrets: ghcr-creds
    name: web-server
    runsOn: golang
route:
  - host: rikami-api.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secret:
  - data: 
      ADMIN_HMAC: AgBTIaaQAQxkXu8HgjTLHe/ytaGpQ6VtXBla/SpaxtEUGhJrG+32psdPe1FpZOdhfYEiJ8q5KTraxXc9ivO0/htORMFnPy8RUJLkS5l2WRYDYeylWiQBBWjFtdBpT7lwpZQxDvdWJR4RA8H+0uDOZgiBzOKlQipXiYTR980ZIUFF/hYBRM4qUH+PyzM9s6T6EPHX0FrXvvhfjienV6ugiUl+IN80bYxtPl7hwJbzb0IpIpf5wwcsLGNlmjESd6pMZ5VbpaajWl6e/Dpp1wHl/BVI1KHfcWUf7P2oMHTAjvtWdHYX3VLrG4q3nsckzH7GQS+rEyiXOj+1oHt17GYgG6a33giiex/1PHwzYHgXXuvcCkdGdLK6d59MtipTxjswLuaOL/cR5xQTzWZRD1iHKFzyapcyct8Vw373BBlMiqluWUpa9YtM4UzMF/3yShaQJq2XJI23iwrJmuqKB9Hnz23VzF8wOGNikAsaUKIE8UXkQaFIs3hzN3xYGtrtBEhiC+Qh2Zk4aYXeD9P9/oh9G88huiOhoAiSx4qeoVPyLuKB8LEn0ssQ6Y6bGy+pFHd3wbLjvVB8yk40A6GQMkcPxtTucSwRwG918uW3tKXqPAZ3hHk252P6ydDO7MbT4AbwZzIyxBXpOuYyh24TNxBdmAIE8U21XT6DOvBTHXZs2ZAE1IgKvvxV1Okx0/onATXhaqcnUeTFYXmSru/C4vAsJjSjfSCnM6W/lQj8F5Fy3V6n1MZgA+p0a1R2MfuCGw==
      ADMIN_PASSWORD: AgBumzglzEYjfjlAQ5b4PDp2xPjBm0A5bPT/rH9N9tCQQYX7DJtxY+Oif+WiOt69+7nyEmpvNGBFYYHI30HJnjc6vgJZ5Se3cwpCUlt7sEx/23dapDglND0kNjjp1luDmb5yH5d9Ncaaxi8drCFrjmzZEdvzBaTqOTu5KZ4eVaWUO3Xv0YCgowPPmUJHn6hCJI3AB9uhbMr8C08Vof4G7tdh7ge/iAPY2JeZVr+FJSJFMRsveaTnDPML/7Jd9xVOq/v1xShAGsULvHwjKOc54JI/WGMW3IZNf04//ZG/V5Ihaog0Vi89CA9zmFgRiWcMAhW1BehNyoLdLh6oQNF8ELMC0XE95cBgewf3bc2MNtCbVJqm5YJ51sUqbhOgEjrjbOZTI1WKf93QHv0fjAD29nQw0lqgx9PmG+TpDKSICctnFzlfcBZ2sTEZ4ECefMpwcvI4t/+KOyzFdrbpwBgpUd6DF3nigfiUlAwvRtQTuteq36datz5l8Gj8y6tV8EdW8ap0N6O/0ShtNBjafWma9dx9C0YmZ+gaHecemHHRj/uWtrw+0g/6WihjI5ZrZNVaSTopK0OiZ9JJH2wnE40FMNYHGR9BGs1UbeJDvB97xLUnrfZbu+r//XM6NaTrYX72u/vz2hhLn1mQza80E932opwX4MXyspRd+WBlQ8ju4QGUMUCEryuxO68h2VcMjapIjIHMF1OlAYId
      ADMIN_USER: AgANelypmngfxHr32bFURpwd4k23+3qsKFq2dS+vR3rVrCJ7Swsyya7ulg3dA2zOzafqqBGie+006sl3NVPmbtqVt561QApCdiW9lJE5G9ar6l52w3gAIojns+WIKxwkPilDZSk2dxBkWTktSEIp9NzX2+GUBg5x+GieIyaE8I0cAP5XJuqK78zqRlsaULQaCl+shBz2U/KD/JLkhv0OzvRmklkJOqQ+CVJwLyarqqL+0O8A9jsXZECT+4clOsCDgbPTrFF9VG32HPDPmDkBy+AWJNQAFrr7p4z+ZGATkLftsN1p3RzXSJqphMC0BpbmUzNsbZlAlH85yD2OYZCDw5Ig+nOGAju9QhayJuvBHW6iSrwaT03NZ22XSSTVk7ra0GX77zIfSyCr29qPk4JGComlQL09pqIOAoJZbqsVQGFOlGmpOQu+t9aeO+cqLEBM/P32+lPWotCji1fde6rzvFdpVrNu0nQP4Od3B7q0H7j2iXgOiCoh907BQtpRRxn2k8aDk7qbyRNQNrjUPlMNiy9Qf8/klJGROHtsMTprqsMFjazIekXo3JQGT+dDOtLMIg3x0N7TUk+JZ2UJlPHqMti1+6dTdlbFUcSI4PxWds7TTFS6RlzW7G1hEkh4tMJ1TeRscyVVN30DXHve6oEBWfJkqqYCtb2cEL6Ll4S2lOT8KJlX0rOIx4hUIHFRnFLhqldVw8Gy
      POSTGRES_DB: AgAq8W+k+C4eNLlSdc1v7sAiGR0SO2KiNlKEdJa7O1UjsF4dN1mFRmBhUL4xsI21KY9OEij2WpieQmeyq5yOnAA8jerVtjDZ56xjFT0GH7Ukf5iHcNQ25LdhEXp+ykJLn0hJtg6KhAUOQwqgeDASJjwO/Co99XfEqPNNNwAYc40UwyvlBzXUKXIS7wXO1JEn1uwxoRF2n2f615GIx8WxmgiA8hCgohY0lXnOCNSoGCG9EMv9W0qZdWDDyxGIg+njarINkSHllWa6ybo7JytnnJQxkQlt4luC2CPAeX3QT8S7uw/2zPdwtEdAWIQGt90S4JUOuTLE5wuQNGNkoWBnXMlHEeFISmHFm7zxcqhs4MTBbEBQWvO50P9AxP6syzJ2UnckfeGUf6M0G+h99rrJv1EnQiwu2WhJw+n9UjVb+zj/teRPm1XuM+W83sjfTvSBQVNljemBEfRzHp2CI2zrVVyAtZcXYcLAJzoxvTwsWbEmHQwyXG+VhtvuwlGPRTFxWA9m/luFh1fesaK28D9RIF4GgIiihUsha1enNpffq0ETb7/FnXg4EKAypcn5NR1M/iizaYndgGt3WLSCyR9Cf45a8193g0RUtGJcSqhkKE1WUXH05tHqpU+8Q2v+vTNJgG888fRFMCHIjXk4v9XAvkhe8iZvl0b/VFmLzuvfIKvUqevZ+wYjRpZMVNd36wyc0OU6b5moHwXdpyHVotZbIXZ1ReBy
      POSTGRES_HOST: AgAajl+lBHMc71JWlvFtUjvrn0Vq9j6aVNpZIP32m8ng2EcT2dZZjqTyKWsy6lUmevMpE8wYfcoi+GxbX7Zwn6vzmsnhYyvD4uYDbbtwQsYEYpV8xF1Rys/GalKU890Y8mBE9sVMc9g52Pd7+FeACiBWSpwk2HSq0gMeIubRUYKsCCRYaV9KuTrB+iNWVqhgckbb4SLRQ8QFyZhz4XCnplMt0k+PaVLp7VKLaZMilzIZbLhdBf4lPgmQtXxTP/qfIi/Siv2Z02hrvuKQIRmhRtJyOzOUNsxiFZrh/cAU2h1gclcKHDj4zDVKhzV4WCfARcZHYIiqW698trMxxpc3Q4OtoZ4MRKkXF7vtwigzl3lE//d74DoRVuZV7ixVQ86dsbKMqYyXIaDRM2PP2AfJCwcI1+IbZvEBKPwi41Vk8pgO4hgDGtjgLm/VOWrqG4TyK1MJauJ9IwEQNvW+yCyhpXI+KMxUFnM6a8FyRPH26gHL6BGGyOBRso8PJztgL+GCHoFtyg3cjYf56WfzjIDIeXs5gcc7atzHOae0g5rm5Wl7LPngFU6sp1Bm7JXS6soNIi6emowZYvP78sikZ6BeWTFF0r50YplQJJWdI5IQXNWR5F8fVy5PP/1grhXx4b/18ssFbl+sdEAKOmrtcVZwSYb8t0IDaY44zG7Juy+CIS9pvL4lOmznrt+P5wfN34/71iuTCYEGxLNP46V5k8D9ropos0Ak
      POSTGRES_PASSWORD: AgB1eGK+Lkpw/Nz8bMz9p/X3KOxQ9z4qbDq2Wj6HFkp3laM2rgWOeHu6t2IDQk5MZzokMi/xhRIKBAteoY+XPFUhwjwl/D+S2wA2v/Dn/FBv4pKEeB9evRWw3nA5qkWBKjROG7t8avgT9AAkgn6m3Fp/PuaSo9OCvz38KUmtvznYItMethlLDrV3ie9H9FehUfnqIjz6Cld04PrLE6SdepEIFz3AjnD0JC/6dH16B4I5175STAe0BJiW5XIP4zkQFzIQS8OeuzUpGXYOlTAPYzFfPA7nL6rGM6QzAO6J2v2CmiKO/O36CVcf8L9HLhiMpxPEke29DAlH301PbN5+pRkKkfR+wueFYcSzhjiePVU0w1bEe18SQc8yfoPaRhP0nZOoefYPU9nBi50JN62C+JBLAqSWmCYCm0sYKFiPItlPDuC2vUqMu480SfskMOncfNg90YS8PV1TcruLlNfDUKyAoCPG/eEldc5e5O+iV9MQCjG0fjuOgGg9/KIkY5dUoH5MjyAbYfAEJad3yJJm4/XngqxCCHIg53epCvwW2eoBVso7fuWkY2U/ds8/YQ1KXQQp/L6VJbSQpxiQnaAeMzzbGIQ7cflBoEJF0bwqh8xfzUsFKefBUdk6OsXHjtP19ewR+1Ce42Nxv/xMPwvq4oxu9tHyIligZQ3PvlDmdITKDt8P6Huw75EzdCVnusNZrOxWmFTU3j00YTHX13f1NYBZAtnTBC4ZuRrOAvxE8DpH8KYGpjl+T29Yuw0FYQ==
      POSTGRES_USER: AgCQdWzt9rEiXqHPkfW/g6k0yCsYTmbaoatBSwQ/Qu0BedwDGJDRV3QJ42sTU48JejQHdI9sIJm9FHIQrsB7G1aJXfQ3yBEiKrw0xxiPHCZSFMDjofYTLuRTCWdd1HcXan3V0GMC0F2X4uoLeQbnJ90bYk0SO0ax9/YKwEgEfOS35gkFBapbD7wfamaBciEx4i+r7YRC99n8y+TafW6YGvVdateBLyH3hh1/O0FjXP9CvvdltWuXjAQHJVkHBOIqiaeQyCzsfrnFgjEmRlQUSwT7kfyigj+73HQu67jGunNwcTYhpsnnEzCIFYSK59LmOdT1jY/EP/iVw2ur0bkA/Qjm5+/ynmxdXtewmQ1ghkqWzWnI9+76//IkQUExJ+9MWByfaVXItVRn7FwkZLy6hTKnwtopz/YSDCGIz89bVFkdmtKe/lq5rsY+pXofXdEhOu+WQp8mNcfISr2XR4N3/mDGnugZfwNOpJbJ1f9z6YPZRjaEbIATnU9oclRCQ15QunX3+/pDD5JpYh7AlZh33miGTtn2T8nmrDSi/Rq6VByd9PGiW3YUatmPoQlot4GfVZsHnMBhRMOyC7ZQxPtQ43dRfVe+bYRMJrqX+d+Lt00UslMcNFG4b0RtlAR/uYI93bA3J9ZLsherTIWIAuBY2jZMSYFClqkShq0Pzvjz/1Sbixz5K5OtZX7oFMp1+4h8KrOZMnB8ypY=
      REDIS_HOST: AgAmAyEuN5DXGIRNFB28qGVLbWoDtzlqUKAKuGGZsng2hSJsfHmyY27M/YSJ8y16NYBe06JESWXkTWAgz28KMJxymT/F8cqGM5M71QgyVS4+wwmiRPJh/PhCDc3EowRu2bR5/heTd444b2Ik+bh2wXKOQaAi2AyVxe9N+bPdOe0+gcr+NxJeTUmW2ttoH383AhP7jxwgKgKaMLIabqurlAR86QMSUe1v7pTID7/ReCYJak72DN6dpbhfaYaE1FeaDE4QNoMmv0mw8LTw0QsjsmQ430JbXnc7xU3Z8NV+DqvNC+4jtW40u4PmHX1KxANSWGueOmV27VqqSxhXDNNPWgaWFolesMpf0WUA1cY8vYRa6jmWqr8VDaxQ+M73BoI5GbiZegxwpKTjhClBCH/BAoJ9vqZQYctt4sGaPqeM757YZMcYaHr3q/6vIeucCYzxi5IC3BK3RGfgx1bfoZsumeF18snDdsPjuo+94xhjE6CGLqtOxgK+lPJQHBq6nCSz+XMnpjQ9akZhdU93ecOcTtxr5PLTzAAX/sXyGakTSP2CmqeB8NTMRZIQPJG1jEQlhxenVrsIUJq9wkcRYuPeS5J+lDO5Pbt6XmQLYdmWVuo6Ye/jP7Q7Iufa0/dFGTy51xiYF+l8P+ijYFehrsMprmLr/7ii+lNrKNKcWHTLGVpkhNcyWTV5rdOBUV2zK/8qphbTNkaQueZ8SMO9DS8HnfRdGAhrO+zsAQs=
    name: web-server-envs
    runsOn: web-server
    runsOnList:
      - web-server
  - data:
      url: AgCPIuEzkNRkXPmYF9vWBhUU0+4Rl53cX6MsCTj4B8r0VLIb/n+2s0F4yP0bYxsR1nIcKhue80+qo6U0gVkGFw8p0de3okMOSO/wyA9dDv88iS/vE+wVEVdg6jcukBphHiF8oddkE2VKr2LOeD8+jn5CqYg+BeLT+TqAAEGVFDp4mxge3TQZHjrnEs5DXXSEFvF+1j5t3YOyybTgt1RJvo12dzZoNRUMz4ksuuqoj5VH8xOKuI8iWZNA+DwObyFcG7UB/RacnhcEBwDhooo79s5AB6ztrVrI1bhj1Lml5/tH3hl9fakf8PGF2KLxQYoTUpMLCsd9uw9kKpaU9/zxAvfD3fp/q7y02DtKo/4CtES+nRgOw8w9yy4N1M6GGFYdvl9cqFmm3eFOPsH0VrCVUuUDu65pjH1Sle8c5IR9NfnJzpvoEfLowMcCMNQqE4ykSusdWUvkHC+1FD1/MBptYWnzbDzCCl8G6DrWRTJjaqDwogviQ1/LbOxR4A3ZIhWZawcfXBv7EtKqgn7OeuGToCnuxO8solOrLwdMdfS2bo6+McDE/XD32fkSpq6O2U0iAcgV4bEE6L2Cx43Br0SMffNN4lfIjrF6Egv/EY2UIR1Ypd/cokgG+UvplOM2DTheYFNsJp3L53qob1urYiLxJEWzWqU6Bj6Gc3pNJ8OVlXe0PbaVNCKqg0husxMSnuIJJ3zdYHsPPjveSh2ahv/4FN9GqftsWqLAIk3DsWBb+r5vcIvnnxCKVXVo/XAQLBxRRihVSoQWO2CABOA+xmYA3OkRtPpyFfIWY4NPkDKu9oB5cFfvYBYBcYrv3TXu2WtNMUbzxGTvKYD3U08qefdafVmH0cxPIqmOmQEB4HkKedzvpyb06vTJE61aNm/LqdXlFhSC8RJ4GFY=
    name: database-credentials
    runsOn: database-schema
    runsOnList:
      - database-schema
service:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8080
